src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>Mapped from the Lead</description>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Unit</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Drawdown__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Drawdowns</relationshipLabel>
        <relationshipName>Drawdowns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Admin Fee</fullName>
                </value>
                <value>
                    <fullName>Cheque</fullName>
                </value>
                <value>
                    <fullName>e-Transfer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reference_Notes__c</fullName>
        <label>Reference Notes</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Payment_Method__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Admin Fee</fullName>
                </value>
                <value>
                    <fullName>Admin Fee charged up front</fullName>
                </value>
                <value>
                    <fullName>Bad Debt</fullName>
                </value>
                <value>
                    <fullName>EFT Reject</fullName>
                </value>
                <value>
                    <fullName>EFT Reprocessed</fullName>
                </value>
                <value>
                    <fullName>EFT to Client</fullName>
                </value>
                <value>
                    <fullName>Fee</fullName>
                </value>
                <value>
                    <fullName>Loan Payout</fullName>
                </value>
                <value>
                    <fullName>Other Fee</fullName>
                </value>
                <value>
                    <fullName>Partial Payment</fullName>
                </value>
                <value>
                    <fullName>Payment Rejected</fullName>
                </value>
                <value>
                    <fullName>Payment Re-processed</fullName>
                </value>
                <value>
                    <fullName>Payment Shortfall</fullName>
                </value>
                <value>
                    <fullName>Payment Surplus</fullName>
                </value>
                <value>
                    <fullName>Payment to Client</fullName>
                </value>
                <value>
                    <fullName>Payment to Lawyer</fullName>
                </value>
                <value>
                    <fullName>Payment to other lender</fullName>
                </value>
                <value>
                    <fullName>Payment to Third-Party</fullName>
                </value>
                <value>
                    <fullName>Payment to Treatment - Service Provider</fullName>
                </value>
                <value>
                    <fullName>Referral Fee</fullName>
                </value>
                <value>
                    <fullName>Waived Fee</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Conga_Finance_Loan_Progression_Print_All__c.field-meta.xml
<CustomField>
    <fullName>Conga_Finance_Loan_Progression_Print_All__c</fullName>
    <formula>&quot;/apex/APXTConga4__Conga_Composer?SolMgr=1&amp;serverUrl=&quot;&amp;$Api.Partner_Server_URL_370&amp;&quot;&amp;Id=&quot;&amp;Id&amp;&quot;&amp;QueryId=[financeloanpprint]a0p19000002LYxr%3Fpv0%3D&quot;&amp;Conga_Finance_Loan_Progression_StartDate__c&amp;&quot;~pv1%3D&quot;&amp;Conga_Finance_Loan_Progression_EndDate__c&amp;&quot;&amp;TemplateId=a0x19000000sR96&amp;DS7=3&quot;</formula>
    <label>Conga Finance Loan Progression Print All</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Conga_Finance_Loan_Progression_View_All__c.field-meta.xml
<CustomField>
    <fullName>Conga_Finance_Loan_Progression_View_All__c</fullName>
    <formula>&quot;/apex/APXTConga4__Conga_Composer?SolMgr=1&quot; 
&amp;&quot;&amp;serverUrl=&quot;&amp;$Api.Partner_Server_URL_370 
&amp;&quot;&amp;Id=&quot;&amp;Id&amp;&quot;&amp;QueryId=[financeloanadv]a0p1F000000xqBHQAY%3Fpv0%3D&quot;&amp;Conga_Finance_Loan_Progression_StartDate__c&amp;&quot;~pv1%3D &quot;&amp; Conga_Finance_Loan_Progression_EndDate__c&amp;&quot;~pv2%3D&quot;&amp;IF(  $Setup.FinanceLoanProgression__c.Business_Unit__c = &#39;Consolidated&#39;,&#39;&#39;,$Setup.FinanceLoanProgression__c.Business_Unit__c)
&amp;&quot;&amp;TemplateId=a0x1F000001Ut4YQAS&quot; 
&amp;&quot;&amp;DS7=3&quot;</formula>
    <label>Conga Finance Loan Progression View All</label>
    <type>Text</type>
</CustomField>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Stage_Status__c</fullName>
        <label>Stage Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>1st Week</fullName>
                </value>
                <value>
                    <fullName>2nd Week</fullName>
                </value>
                <value>
                    <fullName>File for Review</fullName>
                </value>
                <value>
                    <fullName>Add&apos;l Docs Required</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>F/U with PC/Facility</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Assessor Declined</fullName>
                </value>
                <value>
                    <fullName>Legal Representative Declined</fullName>
                </value>
                <value>
                    <fullName>Non-Responsive (Legal Representative/Plaintiff)</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Contact Sheet Completed; Part I of App Sent to Lead for Signature</fullName>
                </value>
                <value>
                    <fullName>Part II of App Sent to Firm w/ Request for Supporting Docs</fullName>
                </value>
                <value>
                    <fullName>Waiting for Additional Supporting Documents</fullName>
                </value>
                <value>
                    <fullName>Waiting for Payout From Other Lender</fullName>
                </value>
                <value>
                    <fullName>File Sent to Assessors Review</fullName>
                </value>
                <value>
                    <fullName>Awaiting Final Client Signature</fullName>
                </value>
                <value>
                    <fullName>Funds Advanced/Awaiting Signed Loan Documents</fullName>
                </value>
                <value>
                    <fullName>Awaiting Final Lawyer Signature</fullName>
                </value>
                <value>
                    <fullName>File Sent for EFT</fullName>
                </value>
                <value>
                    <fullName>See Notes</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Bad Debt</fullName>
                </value>
                <value>
                    <fullName>Paid Off</fullName>
                </value>
                <value>
                    <fullName>Payments Halted</fullName>
                </value>
                <value>
                    <fullName>Partial Payment</fullName>
                </value>
                <value>
                    <fullName>Shortfall</fullName>
                </value>
                <value>
                    <fullName>Surplus</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <formula>TEXT(Account.Business_Unit__c)</formula>
    <label>Business Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ELFI</fullName>
    </customValue>
    <customValue>
        <fullName>Rhino</fullName>
    </customValue>
    <customValue>
        <fullName>Seahold</fullName>
    </customValue>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LoanProgressionReportCtlr.cls
public with sharing class LoanProgressionReportCtlr {
    public class FinancialYear {
        
        @AuraEnabled
        Public String Year; 
        
        @AuraEnabled
        public Decimal totalAdvanceLoanAmountElfi;
        @AuraEnabled
        public Decimal totalAdvanceLoanAmountRhino;
        @AuraEnabled
        Public Decimal totalLoanLosesAmountElfi;
        @AuraEnabled
        Public Decimal totalLoanLosesAmountRhino;
        
        @AuraEnabled
        Public Integer totalNumberOfLoansElfi;
        @AuraEnabled
        Public Integer totalNumberOfLoansRhino;
        
        @AuraEnabled
        Public Decimal lossesPercentageElfi;
        @AuraEnabled
        Public Decimal lossesPercentageRhino;
        
        @AuraEnabled        
        Public List<FinancialQuarter> quarters;
        
        public FinancialYear(){
            totalAdvanceLoanAmountElfi = 0;
            totalAdvanceLoanAmountRhino = 0;
            totalLoanLosesAmountElfi = 0;
            totalLoanLosesAmountRhino = 0;
            totalNumberOfLoansElfi = 0;
            totalNumberOfLoansRhino = 0;
            lossesPercentageElfi = 0;
            lossesPercentageRhino = 0;
            quarters = new List<FinancialQuarter>();
            
        }
        
        
    }
    
    Public class FinancialQuarter{
        @AuraEnabled
        Public String Quarter;
        
        @AuraEnabled
        Public Decimal elfiAdvanceLoanAmount;        
        @AuraEnabled
        Public Integer elfiNumberOfLoans;
        @AuraEnabled
        Public Decimal elfiLoanLosesAmount;
        @AuraEnabled
        Public Integer elfiNumberOfLoanLoses;
        
        @AuraEnabled
        Public Decimal rhinoAdvanceLoanAmount;        
        @AuraEnabled
        Public Integer rhinoNumberOfLoans;
        @AuraEnabled
        Public Decimal rhinoLoanLosesAmount;
        @AuraEnabled
        Public Integer rhinoNumberOfLoanLoses;
    }
    
    @AuraEnabled
    public static List <String> getPickListValues(String objectType, String field)
    {
        return OpportunityViewComponentCtlr.getPickListValues(objectType, field);
    }
    
    @AuraEnabled
    public static FinanceLoanProgression__c getCustomSettings(){
        FinanceLoanProgression__c fLP = FinanceLoanProgression__c.getOrgDefaults();
        return fLP;        
    }
    
    @AuraEnabled
    public static void saveCustomSettings(String startDate, String endDate, String businessUnit){
        try{
            Date startDt = Date.valueOf(startDate);
            Date endDt = Date.valueOf(endDate);
            
            FinanceLoanProgression__c flp = FinanceLoanProgression__c.getOrgDefaults();
            
            flp.End_date__c = endDt;
            flp.Start_Date__c = startDt;
            flp.Business_Unit__c = businessUnit;
            
            upsert flp; 
        }catch(Exception ex){
            
            throw new AuraHandledException(ex.getMessage());
        }
    }
    
    @AuraEnabled
    public static List<FinancialYear> getProgressionReportData(String startDate, String endDate, string BusinessUnit)
    {
        List<FinancialYear> result = new List<FinancialYear>();
        try{
            
            Date startDt = Date.valueOf(startDate);
            Date endDt = Date.valueOf(endDate);
            
            String strQuery = '';
            string eTransfer = 'e-Transfer';
            string Cheque = 'Cheque';
            string AdminFee = 'Admin Fee';
            String ClosedWithLoan = 'Closed With Loan';
            String active = 'Active'; 
            String activePartial = 'Active - Partial Payment';
            String closedPaid = 'Closed - Paid';
            String closedSurplus = 'Closed - Surplus';
            String closedShortfall = 'Closed - Shortfall';
            String closedBadDebt = 'Closed - Bad Debt';
            String badDebt = 'Bad Debt';
            
            
            strQuery += 'SELECT CALENDAR_YEAR(Date__c) year, CALENDAR_QUARTER(Date__c) quarter,';
            strQuery += ' COUNT_Distinct(Opportunity__c) loans, Sum(Amount__c) amt, Opportunity__r.Account.Business_Unit__c unit';
            strQuery += ' FROM Drawdown__c WHERE Date__c >= :startDt';
            strQuery += ' AND Date__c <= :endDt'; 
            strQuery += ' AND Opportunity__r.StageName =:ClosedWithLoan AND ((Payment_Method__c =:eTransfer)';
            strQuery += ' OR (Payment_Method__c =:Cheque)';
            strQuery += ' OR (Payment_Method__c =:AdminFee))';
            strQuery += ' AND (Opportunity__r.Stage_Status__c =:active OR Opportunity__r.Stage_Status__c =:activePartial';
            strQuery += ' OR Opportunity__r.Stage_Status__c =:closedPaid OR Opportunity__r.Stage_Status__c =:closedSurplus';
            strQuery += ' OR Opportunity__r.Stage_Status__c =:closedShortfall OR Opportunity__r.Stage_Status__c =:closedBadDebt)';
            strQuery += BusinessUnit == 'Consolidated' ? '' : ' AND Opportunity__r.Account.Business_Unit__c = :BusinessUnit';
            strQuery += ' Group by CALENDAR_YEAR(Date__c), CALENDAR_QUARTER(Date__c), Opportunity__r.Account.Business_Unit__c';
            strQuery += ' order by CALENDAR_YEAR(Date__c), CALENDAR_QUARTER(Date__c) NULLS LAST';
            
            List<AggregateResult> aggResultAdvances = Database.query(strQuery);
            
            
            //Loan losses
            //Stage status = bad debt
            strQuery = 'SELECT CALENDAR_YEAR(Date__c) year, CALENDAR_QUARTER(Date__c) quarter,';
            strQuery += ' COUNT_Distinct(Opportunity__c) loans, Sum(Amount__c) amt, Opportunity__r.Account.Business_Unit__c unit';
            strQuery += ' FROM Drawdown__c WHERE Date__c >= :startDt';
            strQuery += ' AND Date__c <= :endDt'; 
            //strQuery += ' AND Opportunity__r.StageName =:ClosedWithLoan AND ((Payment_Method__c =:eTransfer)';
            //strQuery += ' OR (Payment_Method__c =:Cheque)';
            //strQuery += ' OR (Payment_Method__c =:AdminFee))';
            //strQuery += ' AND Opportunity__r.Stage_Status__c =:closedBadDebt';
            strQuery += ' AND Reference_Notes__c =:badDebt';
            strQuery += BusinessUnit == 'Consolidated' ? '' : ' AND Opportunity__r.Account.Business_Unit__c = :BusinessUnit';
            strQuery += ' Group by CALENDAR_YEAR(Date__c), CALENDAR_QUARTER(Date__c), Opportunity__r.Account.Business_Unit__c';
            strQuery += ' order by CALENDAR_YEAR(Date__c), CALENDAR_QUARTER(Date__c) NULLS LAST';
            
            List<AggregateResult> aggResultLosses = Database.query(strQuery);
            Set<String> years = new Set<String>();
            List<String> quarters = new List<String>();
           
            Map<String, AggregateResult> aggrMapAdvances = new Map<String,AggregateResult>();            
            if(!aggResultAdvances.isEmpty()){                
                for(AggregateResult res : aggResultAdvances){
                    String key = res.get('year') + '-' + res.get('quarter') + '-' + (String)res.get('unit');
                    aggrMapAdvances.put(key, res);
                    years.add('' + res.get('year'));
                    
                    if(!quarters.contains('' + res.get('quarter')))
                        quarters.add('' + res.get('quarter'));
                }
            }
            
            Map<String, AggregateResult> aggrMapLosses = new Map<String, AggregateResult>();
            if(!aggResultLosses.isEmpty()){                
                for(AggregateResult res : aggResultLosses){
                    String key = res.get('year') + '-' + res.get('quarter') + '-' + (String)res.get('unit');
                    aggrMapLosses.put(key, res);
                    years.add('' + res.get('year'));
                    
                    if(!quarters.contains('' + res.get('quarter')))
                        quarters.add('' + res.get('quarter'));
                }
            }
            
            quarters.sort();
            
            Map<String,List<FinancialQuarter>> financialQuarterList = new Map<String,List<FinancialQuarter>>();
            FinancialYear financialYear;
            if(!years.isEmpty()){
                List<FinancialQuarter> fQuarterList = new List<FinancialQuarter>();
                for(String year : years){
                    financialYear = new FinancialYear();
                    fQuarterList.clear();
                    financialYear.Year = year;
                    for(String quarter : quarters){
                        String key = year + '-' + quarter;
                        
                        FinancialQuarter fQuarter = new FinancialQuarter();
                        fQuarter.Quarter = 'Q' + quarter;
                        
                        // ELFI 
                        fQuarter.elfiAdvanceLoanAmount = aggrMapAdvances.containsKey(key + '-ELFI') ? Double.valueOf(aggrMapAdvances.get(key + '-ELFI').get('amt')) : 0;
                        fQuarter.elfiNumberOfLoans = aggrMapAdvances.containsKey(key + '-ELFI') ? Integer.valueOf(aggrMapAdvances.get(key + '-ELFI').get('loans')) : 0;
                        fQuarter.elfiLoanLosesAmount = aggrMapLosses.containsKey(key + '-ELFI') ? Double.valueOf(aggrMapLosses.get(key + '-ELFI').get('amt')) : 0;
                        fQuarter.elfiNumberOfLoanLoses = aggrMapLosses.containsKey(key + '-ELFI') ? Integer.valueOf(aggrMapLosses.get(key + '-ELFI').get('loans')) : 0;
                        
                        // Rhino 
                        fQuarter.rhinoAdvanceLoanAmount = aggrMapAdvances.containsKey(key + '-Rhino') ? Double.valueOf(aggrMapAdvances.get(key + '-Rhino').get('amt')) : 0;
                        fQuarter.rhinoNumberOfLoans = aggrMapAdvances.containsKey(key + '-Rhino') ? Integer.valueOf(aggrMapAdvances.get(key + '-Rhino').get('loans')) : 0;
                        fQuarter.rhinoLoanLosesAmount = aggrMapLosses.containsKey(key + '-Rhino') ? Double.valueOf(aggrMapLosses.get(key + '-Rhino').get('amt')) : 0;
                        fQuarter.rhinoNumberOfLoanLoses = aggrMapLosses.containsKey(key + '-Rhino') ? Integer.valueOf(aggrMapLosses.get(key + '-Rhino').get('loans')) : 0;
                        
                        fQuarterList.add(fQuarter);
                        
                        financialYear.totalAdvanceLoanAmountElfi += fQuarter.elfiAdvanceLoanAmount;
                        financialYear.totalAdvanceLoanAmountRhino += fQuarter.rhinoAdvanceLoanAmount;
                        financialYear.totalLoanLosesAmountElfi += fQuarter.elfiLoanLosesAmount;
                        financialYear.totalLoanLosesAmountRhino += fQuarter.rhinoLoanLosesAmount;
                        financialYear.totalNumberOfLoansElfi += fQuarter.elfiNumberOfLoans;
                        financialYear.totalNumberOfLoansRhino += fQuarter.rhinoNumberOfLoans;
                        
                    }  
                    
                    financialYear.lossesPercentageElfi = (financialYear.totalLoanLosesAmountElfi / (financialYear.totalAdvanceLoanAmountElfi > 0? financialYear.totalAdvanceLoanAmountElfi : 1 ));
                    financialYear.lossesPercentageRhino = (financialYear.totalLoanLosesAmountRhino / (financialYear.totalAdvanceLoanAmountRhino > 0? financialYear.totalAdvanceLoanAmountRhino : 1 ));
                    financialYear.quarters.addAll(fQuarterList);
                    result.add(financialYear);
                }
            }
            
            
        }catch(Exception e){
            system.debug('exception ' + e.getMessage() + ' ' + e.getStackTraceString());
            throw new AuraHandledException(e.getMessage());
        }
        
        saveCustomSettings(startDate, endDate, BusinessUnit);
        return result;
        
    }
    @AuraEnabled
    public static list<Drawdown__c> getDrawdownCongaURLs(){
        
        list<Drawdown__c> drawdown_conga_url = [select id, Conga_Finance_Loan_Progression_View_All__c, Conga_Finance_Loan_Progression_Print_All__c
                                                from Drawdown__c limit 1];
        return drawdown_conga_url;
    }

}