src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>Mapped from the Lead</description>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Unit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the key person to contact about inquiries related to this account: loan related, additional information, payments, receivables, etc.</inlineHelpText>
        <label>Primary Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>There are no contacts under this account that matches the search criteria.</errorMessage>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <infoMessage>Please select the contact that will serve as primary contact for this account.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Date_Financing_Statement_Expires__c</fullName>
        <label>Date Financing Statement Expires</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Loan_Requests__c</fullName>
        <label>Loan Requests</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1st Loan</fullName>
                </value>
                <value>
                    <fullName>2nd Loan</fullName>
                </value>
                <value>
                    <fullName>3rd Loan</fullName>
                </value>
                <value>
                    <fullName>4th Loan</fullName>
                </value>
                <value>
                    <fullName>5th Loan</fullName>
                </value>
                <value>
                    <fullName>6th Loan</fullName>
                </value>
                <value>
                    <fullName>7th Loan</fullName>
                </value>
                <value>
                    <fullName>8th Loan</fullName>
                </value>
                <value>
                    <fullName>9th Loan</fullName>
                </value>
                <value>
                    <fullName>10th Loan</fullName>
                </value>
                <value>
                    <fullName>11th Loan</fullName>
                </value>
                <value>
                    <fullName>12th Loan</fullName>
                </value>
                <value>
                    <fullName>13th Loan</fullName>
                </value>
                <value>
                    <fullName>14th Loan</fullName>
                </value>
                <value>
                    <fullName>15th Loan</fullName>
                </value>
                <value>
                    <fullName>16th Loan</fullName>
                </value>
                <value>
                    <fullName>17th Loan</fullName>
                </value>
                <value>
                    <fullName>18th Loan</fullName>
                </value>
                <value>
                    <fullName>19th Loan</fullName>
                </value>
                <value>
                    <fullName>20th Loan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Primary Contact)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_of_Loan__c</fullName>
        <label>Type of Loan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Facility Loan</fullName>
                </value>
                <value>
                    <fullName>Lump-Sum</fullName>
                    <default>true</default>
                    <label>Lump-Sum</label>
                </value>
                <value>
                    <fullName>Treatment Loan</fullName>
                </value>
                <value>
                    <fullName>Treatment Loan 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <formula>TEXT(Account.Business_Unit__c)</formula>
    <label>Business Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_No__c.field-meta.xml
<CustomField>
    <fullName>Loan_No__c</fullName>
    <formula>IF(LEN(LEFT(TEXT(Loan_Requests__c),LEN(TEXT(Loan_Requests__c))-7)) == 1, &apos;0&apos;+LEFT(TEXT(Loan_Requests__c),LEN(TEXT(Loan_Requests__c))-7), LEFT(TEXT(Loan_Requests__c),LEN(TEXT(Loan_Requests__c))-7))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loan No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ELFI</fullName>
    </customValue>
    <customValue>
        <fullName>Rhino</fullName>
    </customValue>
    <customValue>
        <fullName>Seahold</fullName>
    </customValue>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PpsaExpiryReportComponentCtrlTest.cls
@isTest(SeeAllData=true)
public class PpsaExpiryReportComponentCtrlTest {
    @isTest static void mentod1(){
        Test.startTest();
            Account TestAcc = new Account();
            TestAcc.Name = 'Test Account';
            TestAcc.Business_Unit__c = 'ELFI';
            Insert TestAcc;
            
            Contact TestCon = new Contact();
            TestCon.FirstName = 'Test';
            TestCon.LastName = 'Contact';
            Insert TestCon;
            
            Opportunity TestOpp = new Opportunity();
            TestOpp.Date_Financing_Statement_Expires__c = Date.valueOf('2023-01-06');
            TestOpp.Primary_Contact__c = TestCon.Id;
            TestOpp.AccountId = TestAcc.Id;
            TestOpp.Type_of_Loan__c = 'Facility Loan';
            TestOpp.Loan_Requests__c = '1st Loan';
            TestOpp.Registration_Number__c = '757098306';
        	TestOpp.Name = 'Test Opportunity';
        	TestOpp.StageName = 'Closed No Loan';
        	TestOpp.CloseDate = Date.valueOf('2019-08-01');
            Insert TestOpp;
        
        	String startdate = '2019-08-01';
            String enddate = '2023-08-01';
            String field = 'Loan_No__c';
            String direction = 'DESC';
            String BusinessUnit = 'Consolidated';
            String searchByName = '';
            String typeOfLoan = 'Consolidated';
        
        	PpsaExpiryReportComponentCtrl.getPPSExpiryLoans(startDate, endDate, field, direction, BusinessUnit, searchByName, typeOfLoan);
        	PpsaExpiryReportComponentCtrl.getCustomSetting();
        	PpsaExpiryReportComponentCtrl.getPickListValues('Opportunity', 'Type_of_Loan__c');
        	PpsaExpiryReportComponentCtrl.saveCustomSettings(startdate, enddate, BusinessUnit, typeOfLoan, searchByName);
        	PpsaExpiryReportComponentCtrl.getSummarizeData(startDate, endDate, BusinessUnit, typeOfLoan);
        Test.stopTest();
    }
}