src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>Mapped from the Lead</description>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Unit</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Law_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Law Firm</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>Account.Account_Type__c</field>
                <operation>equals</operation>
                <value>Lawyer, Law Firm</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Law Firm</value>
            </filterItems>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Law Firm</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Clients</relationshipLabel>
        <relationshipName>Clients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payout_Date__c</fullName>
        <formula>$Setup.Conga_batch_setting__c.Payout_Date_Lawyer_Summary_Report__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payout Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Report_Date__c</fullName>
        <formula>$Setup.Conga_batch_setting__c.Report_Date_Lawyer_Summary_Report__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Report Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Conga_Batch_Assessment_Loans_Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Conga_Batch_Assessment_Loans_Lawyer__c</fullName>
    <formula>&quot;&amp;solmgr=1&quot; &amp;
&quot;&amp;id=&quot; &amp; Id &amp; 
&quot;&amp;queryid=&quot; &amp; IF($Setup.Assessment_Summary_Report__c.Business_Unit__c = &quot;ELFI&quot; , &quot;[LawyerActiveClient]a0p0L00000KAmx2QAD&quot;, &quot;[LawyerActiveClient]a0p0L00000KAmxHQAT&quot;)
&amp; &quot;?pv0=&quot; &amp; Id &amp;

&quot;,[aggregate]&quot; &amp; IF($Setup.Assessment_Summary_Report__c.Business_Unit__c = &quot;ELFI&quot; , &quot;a0p0L00000KAmy0QAD&quot;, &quot;a0p0L00000KAmxMQAT&quot;)
&amp;&quot;&amp;%3Fpv0%3D=&quot; &amp; Id &amp;

&quot;&amp;templateid=&quot; &amp;  IF($Setup.Assessment_Summary_Report__c.Business_Unit__c  = &quot;Rhino&quot;, &quot;a0x0L00000PEzSPQA1&quot;, &quot;a0x0L00000PEzSUQA1&quot;) &amp;
&quot;&amp;defaultpdf=1&quot; &amp;
&quot;&amp;attachmentparentid=&quot; &amp; Id &amp;
&quot;&amp;ac0=1&quot; &amp;
&quot;&amp;sc0=1&quot; &amp;
&quot;&amp;sc1=SalesforceFile&quot; &amp;
&quot;&amp;DS7=5&quot; &amp;
&quot;&amp;qmode=Attachments&quot; &amp;
&quot;&amp;returnpath=/lightning/n/Assessment_Loans?0.source=alohaHeader&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Conga Batch Assessment Loans Lawyer</label>
    <type>Text</type>
</CustomField>

src/objects/Drawdown__c.object
<CustomObject>
    <fields>
        <fullName>Payout_Date__c</fullName>
        <description>The Payout Date pulled down from the Opportunity to work around calculated field length limitations.  Do not update directly here, update on Opportunity instead and let it replicate down.</description>
        <inlineHelpText>Expected or Actual Payout Date of the Drawdown.  Do not update directly here, update on Opportunity instead and let it replicate down to here.</inlineHelpText>
        <label>Payout Date</label>
        <type>Date</type>
    </fields>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Conga_Assessment_Summary_Report_Print__c.field-meta.xml
<CustomField>
    <fullName>Conga_Assessment_Summary_Report_Print__c</fullName>
    <formula>&quot;/apex/APXTConga4__Conga_Composer?SolMgr=1&quot;&amp; 
&quot;&amp;serverUrl=&quot;&amp;$Api.Partner_Server_URL_370&amp; 
&quot;&amp;Id=&quot;&amp;Id&amp; 
&quot;&amp;QueryId=[assessments]&quot; &amp; 
IF($Setup.Assessment_Summary_Report__c.Selected_Ids__c = &#39;&#39;, $Setup.Assessment_Summary_Report__c.Conga_Print_Report_Query_Id__c ,  $Setup.Assessment_Summary_Report__c.Conga_Search_Print_Query_Id__c )&amp;
&quot;%3Fpv0%3D&quot;&amp; 
IF($Setup.Assessment_Summary_Report__c.Business_Unit__c = &#39;Consolidated&#39;, &#39;&#39;, $Setup.Assessment_Summary_Report__c.Business_Unit__c) &amp;
&quot;&amp;TemplateId=&quot; &amp; $Setup.Assessment_Summary_Report__c.Conga_Print_Report_Template_Id__c &amp; &quot;&amp;DS7=3&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Conga Assessment Summary Report Print</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Conga_Assessment_Summary_Report_View_All__c.field-meta.xml
<CustomField>
    <fullName>Conga_Assessment_Summary_Report_View_All__c</fullName>
    <formula>&quot;/apex/APXTConga4__Conga_Composer?SolMgr=1&quot;&amp; 
&quot;&amp;serverUrl=&quot;&amp;$Api.Partner_Server_URL_370&amp; 
&quot;&amp;Id=&quot;&amp;Id&amp; 
&quot;&amp;QueryId=[assessments]&quot;&amp;
IF($Setup.Assessment_Summary_Report__c.Selected_Ids__c = &#39;&#39;, $Setup.Assessment_Summary_Report__c.Conga_View_All_Query_Id__c,  $Setup.Assessment_Summary_Report__c.Conga_Search_View_All_Query_Id__c)&amp; 
&quot;%3Fpv0%3D&quot;&amp; 
IF($Setup.Assessment_Summary_Report__c.Business_Unit__c = &#39;Consolidated&#39;, &#39;&#39;, $Setup.Assessment_Summary_Report__c.Business_Unit__c) &amp;
&quot;&amp;TemplateId=&quot; &amp; $Setup.Assessment_Summary_Report__c.Conga_View_All_Template_Id__c &amp; &quot;&amp;DS7=3&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Conga Assessment Summary Report View All</label>
    <type>Text</type>
</CustomField>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Admin_Fee_Roll_up__c</fullName>
        <label>Admin Fee Roll-up</label>
        <summarizedField>Drawdown__c.Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Drawdown__c.Payment_Method__c</field>
            <operation>equals</operation>
            <value>Admin Fee</value>
        </summaryFilterItems>
        <summaryForeignKey>Drawdown__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Drawdown_Total_wo_Payment__c</fullName>
        <label>Drawdown Total w/o Payment</label>
        <summarizedField>Drawdown__c.Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Drawdown__c.Payment_Method__c</field>
            <operation>notEqual</operation>
            <value>Payment</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Drawdown__c.Reference_Notes__c</field>
            <operation>notEqual</operation>
            <value>Payment Rejected, Payment Re-processed, Referral Fee</value>
        </summaryFilterItems>
        <summaryForeignKey>Drawdown__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Law_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Law Firm</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Referred Cases</relationshipLabel>
        <relationshipName>Referred_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lawyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lawyer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referred Cases</relationshipLabel>
        <relationshipName>Referred_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payout_Date__c</fullName>
        <label>Payout Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Stage_Status__c</fullName>
        <label>Stage Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>1st Week</fullName>
                </value>
                <value>
                    <fullName>2nd Week</fullName>
                </value>
                <value>
                    <fullName>File for Review</fullName>
                </value>
                <value>
                    <fullName>Add&apos;l Docs Required</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>F/U with PC/Facility</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Assessor Declined</fullName>
                </value>
                <value>
                    <fullName>Legal Representative Declined</fullName>
                </value>
                <value>
                    <fullName>Non-Responsive (Legal Representative/Plaintiff)</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Contact Sheet Completed; Part I of App Sent to Lead for Signature</fullName>
                </value>
                <value>
                    <fullName>Part II of App Sent to Firm w/ Request for Supporting Docs</fullName>
                </value>
                <value>
                    <fullName>Waiting for Additional Supporting Documents</fullName>
                </value>
                <value>
                    <fullName>Waiting for Payout From Other Lender</fullName>
                </value>
                <value>
                    <fullName>File Sent to Assessors Review</fullName>
                </value>
                <value>
                    <fullName>Awaiting Final Client Signature</fullName>
                </value>
                <value>
                    <fullName>Funds Advanced/Awaiting Signed Loan Documents</fullName>
                </value>
                <value>
                    <fullName>Awaiting Final Lawyer Signature</fullName>
                </value>
                <value>
                    <fullName>File Sent for EFT</fullName>
                </value>
                <value>
                    <fullName>See Notes</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Bad Debt</fullName>
                </value>
                <value>
                    <fullName>Paid Off</fullName>
                </value>
                <value>
                    <fullName>Payments Halted</fullName>
                </value>
                <value>
                    <fullName>Partial Payment</fullName>
                </value>
                <value>
                    <fullName>Shortfall</fullName>
                </value>
                <value>
                    <fullName>Surplus</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Loan__c</fullName>
        <label>Type of Loan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Facility Loan</fullName>
                </value>
                <value>
                    <fullName>Lump-Sum</fullName>
                    <default>true</default>
                    <label>Lump-Sum</label>
                </value>
                <value>
                    <fullName>Treatment Loan</fullName>
                </value>
                <value>
                    <fullName>Treatment Loan 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <formula>TEXT(Account.Business_Unit__c)</formula>
    <label>Business Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ELFI</fullName>
    </customValue>
    <customValue>
        <fullName>Rhino</fullName>
    </customValue>
    <customValue>
        <fullName>Seahold</fullName>
    </customValue>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AssessmentSummaryReportCtlr.cls
public with sharing class AssessmentSummaryReportCtlr {
    
    public class AssessmentWrapper{
        @AuraEnabled
        public string lawyer {get; set;}
        @AuraEnabled
        public string lawyerId {get; set;}
        @AuraEnabled
        public string firm {get; set;}
        @AuraEnabled
        public string firmId {get; set;}
        @AuraEnabled
        public decimal approvedCredit {get; set;}
        @AuraEnabled
        public decimal utilizedCreditElfi {get; set;}
        @AuraEnabled
        public decimal utilizedCreditRhino {get; set;}
        @AuraEnabled
        public decimal availableCredit {get; set;}
        @AuraEnabled
        public Boolean checked {get; set;}
        @AuraEnabled
        public String attachmentId{get; set;}

        public AssessmentWrapper(){
            lawyer = '';
            lawyerId = '';
            firm = '';
            firmId = '';
            approvedCredit = 0;
            utilizedCreditElfi = 0;
            utilizedCreditRhino = 0;
            availableCredit = 0;
            checked = false;
            attachmentId = '';

        }
    }
    
    @AuraEnabled
    public static List < String > getPickListValues(String objectType, String field)
    {
        return OpportunityViewComponentCtlr.getPickListValues(objectType, field);
    }
    
    @AuraEnabled
    public static Assessment_Summary_Report__c getCustomSetting(){
        Assessment_Summary_Report__c aSR = Assessment_Summary_Report__c.getInstance(UserInfo.getUserId());
        return aSR;
    }

    @AuraEnabled 
    public static Drawdown__c getDrawdown(){
        List<Drawdown__c> congaUrlHolder = [Select Conga_Assessment_Summary_Report_View_All__c,
                                            Conga_Assessment_Summary_Report_Print__c
                                            from Drawdown__c limit 1];
        return congaUrlHolder[0];
    }

    @AuraEnabled
    public static void setCustomSetting(String BusinessUnit, String searchByName){
        Assessment_Summary_Report__c aSR = Assessment_Summary_Report__c.getInstance(UserInfo.getUserId());
        aSR.Business_Unit__c = !String.isEmpty(BusinessUnit) && BusinessUnit != null? BusinessUnit : 'ELFI';
        aSR.Search_by_Name__c = !String.isEmpty(searchByName) && searchByName != null? searchByName : '';        
        upsert aSR;
    }
    
    @AuraEnabled 
    public static List<AssessmentWrapper> getAssessmentData(String searchByName, String BusinessUnit, String field, String direction){
        
        List<Opportunity> assessmentOpps = new List<Opportunity>();
        Set<Id> lawyersIdSet = new Set<Id>();
        Map<String, AssessmentWrapper> lawyerAssessmentMap = new Map<String, AssessmentWrapper>();
        Map<String,String> lawyersAttachmentsMap = new Map<String,String>();

        try{
            
            String filterByBusinessUnit = '';
            string Rhino = 'Rhino';
            string Elfi = 'ELFI';
            String assessment = 'Assessment';
            
            if(BusinessUnit == 'ELFI'){                
                filterByBusinessUnit = 'ELFI';
            }else if(BusinessUnit == 'Rhino'){                
                filterByBusinessUnit = 'Rhino';
            }else if(BusinessUnit == 'Consolidated'){                
                filterByBusinessUnit = 'Consolidated';
            }
            
            String strQuery = '';            
            strQuery = 'SELECT Id, Lawyer__c, Lawyer__r.Name, Law_Firm__c, Law_Firm__r.Name, Lawyer__r.Approved_Credit_Limit__c,';
            strQuery += ' Drawdown_Total_wo_Payment__c, Account.Business_Unit__c, Principal_Repaid_Roll_up__c, Admin_Fee_Roll_up__c';
            strQuery += ' FROM Opportunity';
            strQuery += ' WHERE Type_of_Loan__c =:assessment';
            strQuery += (filterByBusinessUnit == 'Consolidated') ? 
                ' AND (Account.Business_Unit__c =:Elfi OR Account.Business_Unit__c =:Rhino)':
            ' AND Account.Business_Unit__c =:filterByBusinessUnit';            
            strQuery += !String.isEmpty(searchByName) && searchByName != null ? ' AND (Lawyer__r.Name LIKE \'%' + searchByName + '%\''  : '';
            strQuery += !String.isEmpty(searchByName) && searchByName != null ? ' OR Law_Firm__r.Name LIKE \'%' + searchByName + '%\')'  : '';
            strQuery += ' order by ' + field + ' ' + direction + ' NULLS LAST';
            
            system.debug('Query');
            system.debug(strQuery);
            
            assessmentOpps = Database.query(strQuery);

            for(Opportunity opp : assessmentOpps){
                lawyersIdSet.add(opp.lawyer__c);
            }

            //query to retrive attached payout attachements
            if(!lawyersIdSet.isEmpty()){
                for(Attachment attach : [SELECT Id, ParentId FROM Attachment Where ParentId In :lawyersIdSet
                                        AND name like '%List of Clients%' 
                                        AND createddate = today order by createddate desc]){
                    if(!lawyersAttachmentsMap.containsKey(attach.ParentId))
                        lawyersAttachmentsMap.put(attach.ParentId, attach.Id);
                }
            }            
            

            if(!assessmentOpps.isEmpty()){
                String key = '';
                
                for(Opportunity opp : assessmentOpps){
                    key = opp.Lawyer__c + '-' + opp.Law_Firm__c;
                    AssessmentWrapper wrapper = null;
                    if(!lawyerAssessmentMap.containsKey(key))
                        lawyerAssessmentMap.put(key, new AssessmentWrapper());

                    
                    
                    wrapper = lawyerAssessmentMap.get(key);

                    wrapper.attachmentId = '';

                    if(lawyersAttachmentsMap.containsKey(opp.Lawyer__c))
                        wrapper.attachmentId = '' + lawyersAttachmentsMap.get(opp.Lawyer__c);
                    
                    wrapper.lawyerId =  opp.Lawyer__c;
                    wrapper.lawyer = opp.Lawyer__r.Name;
                    wrapper.firm = opp.Law_Firm__r.Name;
                    wrapper.firmId = opp.Law_Firm__c;
                    wrapper.approvedCredit = opp.Lawyer__r.Approved_Credit_Limit__c != null? opp.Lawyer__r.Approved_Credit_Limit__c : 0;
                    
                    Decimal principalRepaidAmnt = opp.Principal_Repaid_Roll_up__c;
                    Decimal drawdownTotalAmntWoPymnt = opp.Drawdown_Total_wo_Payment__c;
                    //Drawdown_Total_wo_Payment__c
                    
                    wrapper.utilizedCreditElfi += opp.Account.Business_Unit__c == 'ELFI'? drawdownTotalAmntWoPymnt != null? drawdownTotalAmntWoPymnt : 0  : 0;
                    //wrapper.utilizedCreditElfi += opp.Account.Business_Unit__c == 'ELFI'? opp.Admin_Fee_Roll_up__c !=null? opp.Admin_Fee_Roll_up__c :0 : 0;
                    
                    wrapper.utilizedCreditElfi -= opp.Account.Business_Unit__c == 'ELFI'? principalRepaidAmnt != null? principalRepaidAmnt : 0  : 0;
                    
                    wrapper.utilizedCreditRhino += opp.Account.Business_Unit__c == 'Rhino'? drawdownTotalAmntWoPymnt != null? drawdownTotalAmntWoPymnt : 0 : 0;
                    //wrapper.utilizedCreditRhino += opp.Account.Business_Unit__c == 'Rhino'? opp.Admin_Fee_Roll_up__c !=null? opp.Admin_Fee_Roll_up__c :0 : 0;
                    
                    wrapper.utilizedCreditRhino -= opp.Account.Business_Unit__c == 'Rhino'? principalRepaidAmnt != null? principalRepaidAmnt : 0  : 0;
                    
                    lawyerAssessmentMap.put(key, wrapper);
                }
            }
            if(!lawyerAssessmentMap.isEmpty()){

                for(String key : lawyerAssessmentMap.keySet()){
                    AssessmentWrapper wrapper = lawyerAssessmentMap.get(key);
                    wrapper.availableCredit = wrapper.approvedCredit - (wrapper.utilizedCreditElfi + wrapper.utilizedCreditRhino);
                    lawyerAssessmentMap.put(key, wrapper);
                }
        
            }
            
        }catch(Exception e){
            system.System.debug(e.getMessage() + ' ' + e.getLineNumber());
            system.System.debug(e.getStackTraceString());
            throw new AuraHandledException(e.getMessage() + ' ' + e.getLineNumber());
        }

        setCustomSetting(BusinessUnit, searchByName);
        return lawyerAssessmentMap.values();
    }

     /******************* Method to generate the payout balance *********************/
    public static void generatePayoutBalance(Date payoutDate, String businessUnitFilter, String ids){
        try{

            String assessment = 'Assessment';
            String paidOff = 'Paid Off';

            String strQueryOpportunity = '';
            strQueryOpportunity = 'SELECT Id, Name, Payout_Date__c, Lawyer__c';
            strQueryOpportunity += ' FROM Opportunity';
            strQueryOpportunity += ' WHERE Type_of_Loan__c =:assessment';
            strQueryOpportunity += ' AND isClosed = true AND isWon = true';
            strQueryOpportunity += ' AND Stage_Status__c !=:paidOff';            
            strQueryOpportunity += (!String.isEmpty(businessUnitFilter) && businessUnitFilter != null) ? 
                ' AND Account.Business_Unit__c =:businessUnitFilter': '';
            if(!String.isEmpty(ids))
                strQueryOpportunity += ' AND Lawyer__c in (' + ids +')';

            List<Opportunity> opportunities = Database.query(strQueryOpportunity);

            for(Opportunity opp : opportunities){
                opp.Payout_Date__c = payoutDate;
            }
            
            if(!opportunities.isEmpty())
                update opportunities;

        }catch(Exception e){
            throw new AuraHandledException('Error Message' + e.getMessage()+e.getStackTraceString());
        }
    }

    @AuraEnabled
    public static Id generate(List<String> selectedIds, String payoutDate, String reportDate, String businessUnitFilter){
        try{
            APXT_BPM__Conductor__c conductor;
            APXTConga4__Conga_Merge_Query__c congaQuery;        
            String ids = '';
            String query = '';
            String assessment = 'Assessment';            

            if(!selectedIds.isEmpty()) {
                ids = String.Join(selectedIds,',');
                query = 'select id from contact WHERE Id in ('+ ids +')';
            }else{
                query = 'SELECT Id FROM contact where id in (SELECT lawyer__c from opportunity WHERE Type_of_Loan__c = :assessment)';
            }
            
            Assessment_Summary_Report__c customSettings = Assessment_Summary_Report__c.getInstance(UserInfo.getUserId());        
            customSettings.Payout_Date__c = (!String.isEmpty(payoutDate) && payoutDate != null) ? Date.valueOf(payoutDate) : customSettings.Payout_Date__c;
            customSettings.Report_Date__c = (!String.isEmpty(reportDate) && reportDate != null) ? Date.valueOf(reportDate) : customSettings.Report_Date__c;
            customSettings.Business_Unit__c = (!String.isEmpty(businessUnitFilter) && businessUnitFilter != null) ? businessUnitFilter : 'ELFI';

            generatePayoutBalance(customSettings.Payout_Date__c, customSettings.Business_Unit__c, ids);
            
            if(String.isEmpty(customSettings.Conga_Conductor_Id__c)){
                congaQuery = new APXTConga4__Conga_Merge_Query__c(APXTConga4__Name__c = 'Assessment Lawyer query - ' + UserInfo.getName(),
                                                                  APXTConga4__Description__c = 'Query of assessment loan summary for conga conductor.',
                                                                  APXTConga4__Query__c = query);
                insert congaQuery;
                conductor = new APXT_BPM__Conductor__c(APXT_BPM__Title__c = 'Mass Assessment Lawyer - ' + UserInfo.getName(), APXT_BPM__Query_Id__c = congaQuery.Id,
                                                       APXT_BPM__URL_Field_Name__c = 'Conga_Batch_Assessment_Loans_Lawyer__c');
                insert conductor;            
                customSettings.Conga_Conductor_Id__c = conductor.Id;
            }else{
                conductor = [SELECT Id, APXT_BPM__Query_Id__c, APXT_BPM__URL_Field_Name__c FROM APXT_BPM__Conductor__c WHERE Id =:customSettings.Conga_Conductor_Id__c];
                congaQuery = [SELECT Id, APXTConga4__Query__c FROM APXTConga4__Conga_Merge_Query__c WHERE Id =:conductor.APXT_BPM__Query_Id__c];
                conductor.APXT_BPM__URL_Field_Name__c = 'Conga_Batch_Assessment_Loans_Lawyer__c';
                update conductor;
                congaQuery.APXTConga4__Query__c = query;
                update congaQuery;
            }
            upsert customSettings;
            return conductor.id;	
        }
        catch(Exception e){
            throw new AuraHandledException('Error Message' + e.getMessage()+e.getStackTraceString());
        }
    }
}