src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospective Client</fullName>
                </value>
                <value>
                    <fullName>Prospective Lawyer</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Lawyer</fullName>
                </value>
                <value>
                    <fullName>Law Firm</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Treatment Provider Firm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the key person to contact about inquiries related to this account: loan related, additional information, payments, receivables, etc.</inlineHelpText>
        <label>Primary Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>There are no contacts under this account that matches the search criteria.</errorMessage>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <infoMessage>Please select the contact that will serve as primary contact for this account.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Client Accounts</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Prospective Client</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Lawyer</fullName>
                </value>
                <value>
                    <fullName>Law Firm</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Law_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Law Firm</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>Account.Account_Type__c</field>
                <operation>equals</operation>
                <value>Lawyer, Law Firm</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Law Firm</value>
            </filterItems>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Law Firm</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Clients</relationshipLabel>
        <relationshipName>Clients</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Lawyers</fullName>
        <active>true</active>
        <description>Use this record type to track lawyers</description>
        <label>Lawyers</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Drawdown__c.object
<CustomObject>
    <fields>
        <fullName>Compounding_Interest__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The opportunity__r.compounding_Interest__c field has been replicated here to avoid exceeding cross object formula lmits.   Field was transformed to a checkbox to simplify usage in formulas as well.</description>
        <inlineHelpText>Indicates if loan interest is compounding or simple.</inlineHelpText>
        <label>Compounding Interest</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Interest_Deferral_Period__c</fullName>
        <description>The Interest Deferral Period from the Opportunity, replicated here to avoid cross object formula size limitations.  Also converted to an number from a picklist value so it&apos;s readily usable in formulas.</description>
        <inlineHelpText>The months to defer interest on this Drawdown.</inlineHelpText>
        <label>Interest Deferral Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <description>The interest rate pulled down from the Opportunity.  Duplicated here to allow formulas to access without exceeding limits.</description>
        <inlineHelpText>Loan Interest Rate</inlineHelpText>
        <label>Interest Rate</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Minimum_Interest_Period__c</fullName>
        <description>The minimum Interest period from the Opportunity.   Replicated here to avoid exceeding cross object formula limitations.</description>
        <inlineHelpText>The number of months of interest which must be charged at a minimum.</inlineHelpText>
        <label>Minimum Interest Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <formula>TEXT( Account.Account_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Compounding_Interest__c</fullName>
        <label>Interest Compounding Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Interest_Compounding_Period__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-Annual</fullName>
                </value>
                <value>
                    <fullName>Annual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interest_Compounding_Period__c</fullName>
        <label>Interest Compounding Period</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Simple Interest</fullName>
                </value>
                <value>
                    <fullName>Compounding Interest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <label>Annual Interest Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Law_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Law Firm</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Referred Cases</relationshipLabel>
        <relationshipName>Referred_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lawyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lawyer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referred Cases</relationshipLabel>
        <relationshipName>Referred_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Minimum_Interest_Period__c</fullName>
        <label>Minimum Interest Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0 months</fullName>
                </value>
                <value>
                    <fullName>1 month</fullName>
                </value>
                <value>
                    <fullName>2 months</fullName>
                </value>
                <value>
                    <fullName>3 months</fullName>
                </value>
                <value>
                    <fullName>4 months</fullName>
                </value>
                <value>
                    <fullName>5 months</fullName>
                </value>
                <value>
                    <fullName>6 months</fullName>
                    <default>true</default>
                    <label>6 months</label>
                </value>
                <value>
                    <fullName>7 months</fullName>
                </value>
                <value>
                    <fullName>8 months</fullName>
                </value>
                <value>
                    <fullName>9 months</fullName>
                </value>
                <value>
                    <fullName>10 months</fullName>
                </value>
                <value>
                    <fullName>11 months</fullName>
                </value>
                <value>
                    <fullName>12 months</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Primary Contact)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage_Status__c</fullName>
        <label>Stage Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>1st Week</fullName>
                </value>
                <value>
                    <fullName>2nd Week</fullName>
                </value>
                <value>
                    <fullName>File for Review</fullName>
                </value>
                <value>
                    <fullName>Add&apos;l Docs Required</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>F/U with PC/Facility</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Assessor Declined</fullName>
                </value>
                <value>
                    <fullName>Legal Representative Declined</fullName>
                </value>
                <value>
                    <fullName>Non-Responsive (Legal Representative/Plaintiff)</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Contact Sheet Completed; Part I of App Sent to Lead for Signature</fullName>
                </value>
                <value>
                    <fullName>Part II of App Sent to Firm w/ Request for Supporting Docs</fullName>
                </value>
                <value>
                    <fullName>Waiting for Additional Supporting Documents</fullName>
                </value>
                <value>
                    <fullName>Waiting for Payout From Other Lender</fullName>
                </value>
                <value>
                    <fullName>File Sent to Assessors Review</fullName>
                </value>
                <value>
                    <fullName>Awaiting Final Client Signature</fullName>
                </value>
                <value>
                    <fullName>Funds Advanced/Awaiting Signed Loan Documents</fullName>
                </value>
                <value>
                    <fullName>Awaiting Final Lawyer Signature</fullName>
                </value>
                <value>
                    <fullName>File Sent for EFT</fullName>
                </value>
                <value>
                    <fullName>See Notes</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Bad Debt</fullName>
                </value>
                <value>
                    <fullName>Paid Off</fullName>
                </value>
                <value>
                    <fullName>Payments Halted</fullName>
                </value>
                <value>
                    <fullName>Partial Payment</fullName>
                </value>
                <value>
                    <fullName>Shortfall</fullName>
                </value>
                <value>
                    <fullName>Surplus</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Loan__c</fullName>
        <label>Type of Loan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Facility Loan</fullName>
                </value>
                <value>
                    <fullName>Lump-Sum</fullName>
                    <default>true</default>
                    <label>Lump-Sum</label>
                </value>
                <value>
                    <fullName>Treatment Loan</fullName>
                </value>
                <value>
                    <fullName>Treatment Loan 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/ApplyPaymentQueueableTest.cls
@isTest
public class ApplyPaymentQueueableTest {
    @TestSetup
    static void initailizeTestData(){
        // Account
        Id RecordTypeIdAccount = 
            Schema.SObjectType.Account.getRecordTypeInfosByName().get('General Business').getRecordTypeId();
        
        
        Account generalBusinessAcc = new Account();
        generalBusinessAcc.Name='account';
        generalBusinessAcc.BillingStreet = 'Testtest';
        generalBusinessAcc.BillingState = 'CA';
        generalBusinessAcc.BillingCity = 'City';
        generalBusinessAcc.BillingPostalCode = '10001';
        generalBusinessAcc.Billingcountry='Canada';
        generalBusinessAcc.ShippingStreet = 'Test';
        generalBusinessAcc.ShippingState = 'New York';
        generalBusinessAcc.ShippingCountry = 'UNITED STATES';
        generalBusinessAcc.ShippingPostalCode = '10001';
        generalBusinessAcc.ShippingCity = 'Lake Trees';
        generalBusinessAcc.Account_Type__c = 'Treatment Provider Firm';
        generalBusinessAcc.RecordTypeId = RecordTypeIdAccount;
        
        
        // Account # 2
        Id RecordTypeIdAccount2 = 
            Schema.SObjectType.Account.getRecordTypeInfosByName().get('Law Firm').getRecordTypeId();
        
        
        Account lawfirm = new Account();
        lawfirm.Name='Test Lawfirm';
        lawfirm.BillingStreet = 'sample';
        lawfirm.BillingState = 'AK';
        lawfirm.BillingCity = 'City1';
        lawfirm.BillingPostalCode = '987654';
        lawfirm.Billingcountry='Uganda';
        lawfirm.ShippingStreet = 'Test1';
        lawfirm.ShippingState = 'Los Angeles';
        lawfirm.ShippingPostalCode = '123456';
        lawfirm.ShippingCity = 'Lake View';
        lawfirm.Account_Type__c = 'Treatment Provider Firm';
        lawfirm.RecordTypeId = RecordTypeIdAccount2;
        //insert lawfirm;
        
        Account lawfirm2 = new Account();
        lawfirm2.Name='example account';
        lawfirm2.BillingStreet = 'example';
        lawfirm2.BillingState = 'SC';
        lawfirm2.BillingCity = 'example city';
        lawfirm2.BillingPostalCode = '012457';
        lawfirm2.Billingcountry='Pakistan';
        lawfirm2.ShippingStreet = 'Test1';
        lawfirm2.ShippingState = 'New Jersey';
        lawfirm2.ShippingPostalCode = '654321';
        lawfirm2.ShippingCity = 'Lake View Park';
        lawfirm2.Account_Type__c = 'Treatment Provider Firm';
        lawfirm2.RecordTypeId = RecordTypeIdAccount2;
        //insert lawfirm2;
        //
        Id RecordTypeIdAccount3 = 
            Schema.SObjectType.Account.getRecordTypeInfosByName().get('Assessment Provider').getRecordTypeId();
        
        
        Account assessmentProviderAcc = new Account();
        assessmentProviderAcc.Name='Test Assessment Provider';        
        assessmentProviderAcc.RecordTypeId = RecordTypeIdAccount3;
        
        insert (new SObject[]{generalBusinessAcc, assessmentProviderAcc, lawfirm, lawfirm2});          
        
        // Contact
        Id RecordTypeIdContact = 
            Schema.SObjectType.Contact.getRecordTypeInfosByName().get('General Contact').getRecordTypeId();
        
        Contact primaryContct = new Contact();
        
        primaryContct.lastname = 'testtest';
        primaryContct.email = 'testtest@testtest.com';
        primaryContct.AccountId = generalBusinessAcc.id;
        primaryContct.RecordTypeId = RecordTypeIdContact;
        
        //insert primaryContct;
        
        // Contact # 2
        Id RecordTypeIdContact2 = 
            Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Lawyers').getRecordTypeId();
        
        Contact lawyerContact = new Contact();
        
        lawyerContact.lastname = 'test';
        lawyerContact.email = 'test@test.com';
        lawyerContact.AccountId = lawfirm.id;
        lawyerContact.RecordTypeId = RecordTypeIdContact2;
          
        
        insert (new SObject[]{primaryContct, lawyerContact});
        
        
        // Opportunity 
        Opportunity Opp = new Opportunity();
        Opp.Name = 'Test Opportunity';
        Opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Client Opportunity Record Type').getRecordTypeId();
        Opp.AccountId = generalBusinessAcc.Id;
        Opp.Lawyer__c = lawyerContact.Id;
        Opp.CloseDate = Date.today().addDays(14);
        Opp.StageName = 'Closed With Loan';
        Opp.Law_Firm__c = lawfirm.Id;        
        Opp.Stage_Status__c = 'Approved';
        Opp.Type_of_Loan__c = 'Facility Loan';
        Opp.Primary_Contact__c = primaryContct.Id;
        Opp.Interest_Rate__c = 1.0;
        Opp.Minimum_Interest_Period__c = '12 months';
        Opp.Compounding_Interest__c = 'Annual';
        Opp.Interest_Compounding_Period__c = 'Simple Interest';
        Opp.Interest_Deferral_Period__c = '0';
        Opp.Re_Assessed_Loan__c = null;
        Opp.Amount = 5.0;
        //insert Opp; 
        
        insert (new SObject[]{Opp});
                
        // Drawdown
        Drawdown__c drw = new Drawdown__c();
        
        drw.Opportunity__c = Opp.id;
        drw.Amount__c = 1000;
        drw.Date__c = Date.today().addDays(-30);
        drw.Payment_Method__c = 'e-Transfer';
        drw.Reference_Notes__c = 'Payment to Client';
        
        insert (new SObject[]{drw});
        
    }
    public static testmethod void testPaymentQueueable(){
        
        Account acc = [select id, Is_Async_Processing__c from account where name = 'account' limit 1];  
        acc.Is_Async_Processing__c = true;
        update acc;
        String oppId = [select id from opportunity where name = 'Test Opportunity'].id;
        test.startTest();
        PaymentInfo info = new PaymentInfo();
        info.accountId = acc.Id;
        info.payoutDate = '2018-01-01';
        info.searchType = 'Payout';
        info.oppId = oppId;
        info.action = 'Partial Payment';
        info.OppBadDebts = '';
        System.enqueueJob(new ApplyPaymentQueueable(acc.Id, new List<PaymentInfo>{info}));        
        test.stopTest();
        acc = [select id, Is_Async_Processing__c from account where name = 'account' limit 1]; 
        System.assertEquals(false, acc.Is_Async_Processing__c);
    }

}