src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>Mapped from the Lead</description>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Unit</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Exclude_from_Payout__c.field-meta.xml
<CustomField>
    <fullName>Exclude_from_Payout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exclude from Payout</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Conga_batch_setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom conga batch setting to store Report Date, Payout Date, Email body and conga template query selector</description>
    <fields>
        <fullName>Conductor_Id_Lawyer_Summary_Report__c</fullName>
        <label>Conductor Id Lawyer Summary Report</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Additional_Notes_Lawyer_Summary__c</fullName>
        <label>Email Additional Notes Lawyer Summary</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Conga batch setting</label>
</CustomObject>

force-app/main/default/objects/Conga_batch_setting__c/fields/Lawyer_Count_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Lawyer_Count_Business_Unit__c</fullName>
    <label>Lawyer Count Business Unit</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Conga_batch_setting__c/fields/Lawyer_Count_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Lawyer_Count_End_Date__c</fullName>
    <label>Lawyer Count End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Conga_batch_setting__c/fields/Lawyer_Count_Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Lawyer_Count_Payout_Date__c</fullName>
    <label>Lawyer Count Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Conga_batch_setting__c/fields/Lawyer_Count_Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Lawyer_Count_Report_Date__c</fullName>
    <label>Lawyer Count Report Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Conga_batch_setting__c/fields/Lawyer_Count_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Lawyer_Count_Start_Date__c</fullName>
    <label>Lawyer Count Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Conga_batch_setting__c/fields/Lawyer_Count_Type_Of_Loan__c.field-meta.xml
<CustomField>
    <fullName>Lawyer_Count_Type_Of_Loan__c</fullName>
    <label>Lawyer Count Type Of Loan</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Conga_batch_setting__c/fields/Query_Selector_Lawyer_Count_Report__c.field-meta.xml
<CustomField>
    <fullName>Query_Selector_Lawyer_Count_Report__c</fullName>
    <label>Query Selector Lawyer Count Report</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Lawyers</fullName>
        <active>true</active>
        <description>Use this record type to track lawyers</description>
        <label>Lawyers</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Conga_Batch_Lawyer_Count__c.field-meta.xml
<CustomField>
    <fullName>Conga_Batch_Lawyer_Count__c</fullName>
    <formula>&quot;&amp;solmgr=1&quot; &amp;
&quot;&amp;id=&quot; &amp; Id &amp;
&quot;&amp;queryid=&quot; &amp; IF($Setup.Conga_batch_setting__c.Query_Selector_Lawyer_Count_Report__c = &quot;Active&quot;, &quot;[LawyerActiveClient]a0pL0000007q7SWIAY&quot;,&quot;[LawyerClient]a0pL0000007q7Sb&quot;) &amp; &quot;?pv0=&quot; &amp; Id &amp;
&quot;~pv1%3D&quot;&amp; $Setup.Conga_batch_setting__c.Lawyer_Count_Business_Unit__c &amp;
&quot;~pv2%3D&quot;&amp; $Setup.Conga_batch_setting__c.Lawyer_Count_Type_Of_Loan__c &amp;
&quot;&amp;templateid=&quot; &amp; IF( $Setup.Conga_batch_setting__c.Lawyer_Count_Business_Unit__c = &quot;&apos;Rhino&apos;&quot;, &quot;a0x0L00000PH6QI&quot;, IF( $Setup.Conga_batch_setting__c.Lawyer_Count_Business_Unit__c = &quot;&apos;Seahold&apos;&quot;, &quot;a0x0L00000QCQoYQAX&quot;, &quot;a0x0L00000PVUFQ&quot;)) &amp;
&quot;&amp;defaultpdf=1&quot; &amp;
&quot;&amp;attachmentparentid=&quot; &amp; Id &amp;
&quot;&amp;ac0=1&quot; &amp;
&quot;&amp;sc0=1&quot; &amp;
&quot;&amp;sc1=SalesforceFile&quot; &amp;
&quot;&amp;DS7=5&quot; &amp;
&quot;&amp;qmode=Attachments&quot; &amp;
&quot;&amp;returnpath=/lightning/n/Custom_Reports?0.source=alohaHeader&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Conga Batch Lawyer Count</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Conga_Batch_Lawyer_Count_Send_Email__c.field-meta.xml
<CustomField>
    <fullName>Conga_Batch_Lawyer_Count_Send_Email__c</fullName>
    <formula>SUBSTITUTE( Conga_Batch_Lawyer_Count__c , &quot;&amp;qmode=Attachments&quot;, &quot;&amp;qmode=SendEmail&quot;) &amp;
&quot;&amp;CongaEmailTemplateId=a0o0L00000L4wsr&quot;&amp;
&quot;&amp;EmailToId=&quot;&amp; BLANKVALUE( $Setup.Conga_batch_setting__c.Test_Recipient_of_Lawyer_Summary__c , Id )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Conga Batch Lawyer Count Send Email</label>
    <type>Text</type>
</CustomField>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Drawdown_Total__c</fullName>
        <label>Drawdown Total</label>
        <summarizedField>Drawdown__c.Amount__c</summarizedField>
        <summaryForeignKey>Drawdown__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Law_Firm_Lawyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Law Firm Lawyer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Onboarding Opportunity</relationshipLabel>
        <relationshipName>Onboarding_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lawyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lawyer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referred Cases</relationshipLabel>
        <relationshipName>Referred_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan_Available_to_Drawdown__c</fullName>
        <formula>CASE(
TEXT(Type_of_Loan__c), 
&quot;Facility Loan&quot;, Amount - Drawdown_Total__c,
&quot;Lum-Sum&quot;, 0,
&quot;Treatment Loan&quot;, Amount - Total_Paid_Service_Provider__c,
&quot;Treatment Loan 2&quot;, Amount - Total_Paid_Service_Provider__c,
0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Loan Available to Drawdown</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Stage_Status__c</fullName>
        <label>Stage Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>1st Week</fullName>
                </value>
                <value>
                    <fullName>2nd Week</fullName>
                </value>
                <value>
                    <fullName>File for Review</fullName>
                </value>
                <value>
                    <fullName>Add&apos;l Docs Required</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>F/U with PC/Facility</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Assessor Declined</fullName>
                </value>
                <value>
                    <fullName>Legal Representative Declined</fullName>
                </value>
                <value>
                    <fullName>Non-Responsive (Legal Representative/Plaintiff)</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Contact Sheet Completed; Part I of App Sent to Lead for Signature</fullName>
                </value>
                <value>
                    <fullName>Part II of App Sent to Firm w/ Request for Supporting Docs</fullName>
                </value>
                <value>
                    <fullName>Waiting for Additional Supporting Documents</fullName>
                </value>
                <value>
                    <fullName>Waiting for Payout From Other Lender</fullName>
                </value>
                <value>
                    <fullName>File Sent to Assessors Review</fullName>
                </value>
                <value>
                    <fullName>Awaiting Final Client Signature</fullName>
                </value>
                <value>
                    <fullName>Funds Advanced/Awaiting Signed Loan Documents</fullName>
                </value>
                <value>
                    <fullName>Awaiting Final Lawyer Signature</fullName>
                </value>
                <value>
                    <fullName>File Sent for EFT</fullName>
                </value>
                <value>
                    <fullName>See Notes</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Bad Debt</fullName>
                </value>
                <value>
                    <fullName>Paid Off</fullName>
                </value>
                <value>
                    <fullName>Payments Halted</fullName>
                </value>
                <value>
                    <fullName>Partial Payment</fullName>
                </value>
                <value>
                    <fullName>Shortfall</fullName>
                </value>
                <value>
                    <fullName>Surplus</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type_of_Loan__c</fullName>
        <label>Type of Loan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Facility Loan</fullName>
                </value>
                <value>
                    <fullName>Lump-Sum</fullName>
                    <default>true</default>
                    <label>Lump-Sum</label>
                </value>
                <value>
                    <fullName>Treatment Loan</fullName>
                </value>
                <value>
                    <fullName>Treatment Loan 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <formula>TEXT(Account.Business_Unit__c)</formula>
    <label>Business Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ELFI</fullName>
    </customValue>
    <customValue>
        <fullName>Rhino</fullName>
    </customValue>
    <customValue>
        <fullName>Seahold</fullName>
    </customValue>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LawyerCountController.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 08-18-2020
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   08-13-2020   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public class LawyerCountController {
    /******************* Method to return all lawyers *********************/
    @AuraEnabled
    public static List<ContactInfo> getLawyersContacts(String strQuery, String LoanFilter, List<String> businessUnitFilter, List<String> typeofloans, String startDate, String endDate) {
        try{
            LoanFilter = String.isEmpty(LoanFilter) ? 'All' : LoanFilter;
            
            // Initializing the contact variable
            List<ContactInfo> contactInfo = new List<ContactInfo>();
            List<Contact> contacts = new List<Contact>();
                   
            // *** Still need to handle exceptions ***
            // Executing the query to retrieve the account information
            contacts = Database.query(strQuery);        

            Date startDt = Date.valueOf(startDate);
            Date endDt = Date.valueOf(endDate);

            Report_Settings__c reportSettings = Report_Settings__c.getOrgDefaults();
            reportSettings.Start_Date__c=startDt;
            reportSettings.End_Date__c=endDt;
            upsert reportSettings;
            
            
            Set<Id> contactIds = new Map<Id,Contact>(contacts).keySet();
            for(contact con : contacts)
            {
                System.debug('## getLawyersContacts - RESULT: ' + con.Id);
            }


            
            strQuery = 'Select Law_Firm_Lawyer__c, Lawyer__c, AccountId, Loan_Available_to_Drawdown__c from Opportunity where Lawyer__c in :contactIds ';
            strQuery += (typeofloans.isEmpty()) ? '' : ' AND Type_of_Loan__c IN :typeofloans';
            strQuery += ' AND StageName = \'Closed With Loan\' AND Account.Exclude_from_Payout__c = false AND Drawdown_Total__c > 0 AND Stage_Status__c LIKE \'%Active%\'';
            // strQuery += LoanFilter == 'Active'? ' AND isClosed = true AND isWon = true AND Stage_Status__c != \'Paid Off\'' : '';
            strQuery += (businessUnitFilter.isEmpty()) ? '' : ' AND Account.Business_Unit__c IN :businessUnitFilter';
            List<Opportunity> oppties = new List<Opportunity>();
            oppties = Database.query(strQuery);
            System.debug('Oppty: Query: '+strQuery);
            Map<Id,Set<Id>> lawyerToClients = new Map<Id,Set<Id>>();
            
            for(Opportunity opp : oppties)
            {
                if(!lawyerToClients.containsKey(opp.Lawyer__c))
                {
                    lawyerToClients.put(opp.Lawyer__c, new Set<Id>());
                }
                lawyerToClients.get(opp.Lawyer__c).add(opp.AccountId);
            }
            for(contact c : contacts)
            {
                ContactInfo info = new ContactInfo();
                info.contact = c;
                info.noOfFiles = lawyerToClients.containsKey(c.Id) ? lawyerToClients.get(c.Id).size() : 0;
                if(info.noOfFiles > 0)
                {
                    contactInfo.add(info);
                }
            }
            return contactInfo;
        }
        catch(Exception e){
            throw new AuraHandledException('Error Message' + e.getMessage());
        }
    }  
    /******************* Method to get all picklists values for Account *********************/  
    @AuraEnabled
    public static List < String > getPickListValues(String objectType, String field)
    {
        return OpportunityViewComponentCtlr.getPickListValues(objectType, field);
    }
    @AuraEnabled
    public static Id send(String query, List<String> selectedIds, String payoutDate, String reportDate, String emailBody, String LoanFilter, List<String> businessUnitFilter, List<String> typeofloans){       
        try{
            system.debug('-Here in Send function -');
            system.debug(selectedIds);
            APXT_BPM__Conductor__c conductor;
            APXTConga4__Conga_Merge_Query__c congaQuery;        
            String ids = '';
            
            if(String.isEmpty(query) || query == null) {
                ids = String.Join(selectedIds,',');
                query = 'select id from contact WHERE Id in ('+ ids +')';
            }
            
            Conga_batch_setting__c customSettings = Conga_batch_setting__c.getInstance(UserInfo.getUserId());        
            customSettings.Lawyer_Count_Payout_Date__c = (!String.isEmpty(payoutDate) && payoutDate != null) ? Date.valueOf(payoutDate) : customSettings.Lawyer_Count_Payout_Date__c;
            customSettings.Lawyer_Count_Report_Date__c = (!String.isEmpty(reportDate) && reportDate != null) ? Date.valueOf(reportDate) : customSettings.Lawyer_Count_Report_Date__c;
            customSettings.Lawyer_Count_Business_Unit__c = String.join(businessUnitFilter, '|');
            customSettings.Email_Additional_Notes_Lawyer_Summary__c = emailBody;
            customSettings.Query_Selector_Lawyer_Count_Report__c = LoanFilter;
            customSettings.Lawyer_Count_Type_Of_Loan__c = String.join(typeofloans, '|');        
            
            if(String.isEmpty(customSettings.Conductor_Id_Lawyer_Summary_Report__c)){
                congaQuery = new APXTConga4__Conga_Merge_Query__c(APXTConga4__Name__c = 'Lawyer summary conductor query - ' + UserInfo.getName(),
                                                                  APXTConga4__Description__c = 'Query of lawyer summary custom report for conga conductor.',
                                                                  APXTConga4__Query__c = query);
                insert congaQuery;
                conductor = new APXT_BPM__Conductor__c(APXT_BPM__Title__c = 'Mass Lawyer Summary - ' + UserInfo.getName(), APXT_BPM__Query_Id__c = congaQuery.Id,
                                                       APXT_BPM__URL_Field_Name__c = 'Conga_Batch_Lawyer_Count_Send_Email__c');
                insert conductor;            
                customSettings.Conductor_Id_Lawyer_Summary_Report__c = conductor.Id;
            }else{
                conductor = [SELECT Id, APXT_BPM__Query_Id__c, APXT_BPM__URL_Field_Name__c FROM APXT_BPM__Conductor__c WHERE Id =:customSettings.Conductor_Id_Lawyer_Summary_Report__c];
                congaQuery = [SELECT Id, APXTConga4__Query__c FROM APXTConga4__Conga_Merge_Query__c WHERE Id =:conductor.APXT_BPM__Query_Id__c];
                conductor.APXT_BPM__URL_Field_Name__c = 'Conga_Batch_Lawyer_Count_Send_Email__c';
                update conductor;
                congaQuery.APXTConga4__Query__c = query;
                update congaQuery;
            }
            upsert customSettings;
            return conductor.id;
        }
        catch(Exception e){
            throw new AuraHandledException('Error Message' + e.getMessage()+e.getStackTraceString());
        }
    }

    @AuraEnabled
    public static void SaveCustomSettings(String startdate, String enddate, String payoutDate, String reportDate, List<String> typeofloans, List<String> businessUnitFilter, String LoanFilter){
        
        Conga_batch_setting__c customSettings = Conga_batch_setting__c.getInstance(UserInfo.getUserId());
        customSettings.Lawyer_Count_Start_Date__c = (!String.isEmpty(startdate) || startdate != null) ? Date.valueOf(startdate) : customSettings.Lawyer_Count_Start_Date__c;
        customSettings.Lawyer_Count_End_Date__c = (!String.isEmpty(enddate) || enddate != null) ? Date.valueOf(enddate) : customSettings.Lawyer_Count_End_Date__c;
        customSettings.Lawyer_Count_Payout_Date__c = (!String.isEmpty(payoutDate) && payoutDate != null) ? Date.valueOf(payoutDate) : customSettings.Lawyer_Count_Payout_Date__c;
        customSettings.Lawyer_Count_Report_Date__c = (!String.isEmpty(reportDate) && reportDate != null) ? Date.valueOf(reportDate) : customSettings.Lawyer_Count_Report_Date__c;
        customSettings.Lawyer_Count_Type_Of_Loan__c = String.join(typeofloans, '|');
        customSettings.Lawyer_Count_Business_Unit__c = String.join(businessUnitFilter, '|');
        customSettings.Query_Selector_Lawyer_Count_Report__c = LoanFilter;
        upsert customSettings;

    }
    
    @AuraEnabled
    public static Conga_batch_setting__c GetCustomSettings(){
        Conga_batch_setting__c customSettings = Conga_batch_setting__c.getInstance(UserInfo.getUserId());
        return customSettings;
    }

    @AuraEnabled
    public static Id generate(String query, List<String> selectedIds, String payoutDate, String reportDate, String LoanFilter, List<String> businessUnitFilter, List<String> typeofloans){
        try{
            APXT_BPM__Conductor__c conductor;
            APXTConga4__Conga_Merge_Query__c congaQuery;        
            String ids = '';
            
            if(String.isEmpty(query) || query == null) {
                ids = String.Join(selectedIds,',');
                query = 'select id from contact WHERE Id in ('+ ids +')';
            }
            
            Conga_batch_setting__c customSettings = Conga_batch_setting__c.getInstance(UserInfo.getUserId());        
            customSettings.Lawyer_Count_Payout_Date__c = (!String.isEmpty(payoutDate) && payoutDate != null) ? Date.valueOf(payoutDate) : customSettings.Lawyer_Count_Payout_Date__c;
            customSettings.Lawyer_Count_Report_Date__c = (!String.isEmpty(reportDate) && reportDate != null) ? Date.valueOf(reportDate) : customSettings.Lawyer_Count_Report_Date__c;
            customSettings.Lawyer_Count_Business_Unit__c = String.join(businessUnitFilter, '|');
            customSettings.Lawyer_Count_Type_Of_Loan__c = String.join(typeofloans, '|');
            customSettings.Query_Selector_Lawyer_Count_Report__c = LoanFilter;
            
            if(String.isEmpty(customSettings.Conductor_Id_Lawyer_Summary_Report__c)){
                congaQuery = new APXTConga4__Conga_Merge_Query__c(APXTConga4__Name__c = 'Lawyer summary conductor query - ' + UserInfo.getName(),
                                                                  APXTConga4__Description__c = 'Query of lawyer summary custom report for conga conductor.',
                                                                  APXTConga4__Query__c = query);
                insert congaQuery;
                conductor = new APXT_BPM__Conductor__c(APXT_BPM__Title__c = 'Mass Lawyer Summary - ' + UserInfo.getName(), APXT_BPM__Query_Id__c = congaQuery.Id,
                                                       APXT_BPM__URL_Field_Name__c = 'Conga_Batch_Lawyer_Count__c');
                insert conductor;            
                customSettings.Conductor_Id_Lawyer_Summary_Report__c = conductor.Id;
            }else{
                conductor = [SELECT Id, APXT_BPM__Query_Id__c, APXT_BPM__URL_Field_Name__c FROM APXT_BPM__Conductor__c WHERE Id =:customSettings.Conductor_Id_Lawyer_Summary_Report__c];
                congaQuery = [SELECT Id, APXTConga4__Query__c FROM APXTConga4__Conga_Merge_Query__c WHERE Id =:conductor.APXT_BPM__Query_Id__c];
                conductor.APXT_BPM__URL_Field_Name__c = 'Conga_Batch_Lawyer_Count__c';
                update conductor;
                congaQuery.APXTConga4__Query__c = query;
                update congaQuery;
            }
            upsert customSettings;
            return conductor.id;	
        }
        catch(Exception e){
            throw new AuraHandledException('Error Message' + e.getMessage()+e.getStackTraceString());
        }
    }
    
    public class ContactInfo{
        @AuraEnabled
        public Contact contact{get;set;}
        
        @AuraEnabled
        public Integer noOfFiles{get;set;} 
        
        @AuraEnabled
        public Boolean checked{get;set;} 
    }
}