src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>All_Payout_Balance__c</fullName>
        <label>All Payout Balance</label>
        <summarizedField>Opportunity.Payout_Balance__c</summarizedField>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>Mapped from the Lead</description>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Unit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Name_Formula__c</fullName>
        <formula>IF(CONTAINS( TRIM(Name)   , &apos;- Account # &apos;),  SUBSTITUTE(Name, &apos;- Account # &apos;, &apos;- 0000&apos;),  IF(CONTAINS( TRIM(Name)   , &apos;-Account # &apos;), SUBSTITUTE(Name, &apos;-Account # &apos;, &apos;- 0000&apos;), IF(CONTAINS( TRIM(Name)   , &apos;- Account #&apos;), SUBSTITUTE(Name, &apos;- Account #&apos;, &apos;- 0000&apos;),  IF(CONTAINS( TRIM(Name)   , &apos;-Account #&apos;), SUBSTITUTE(Name, &apos;-Account #&apos;, &apos;- 0000&apos;), TRIM(Name)) ) ) )</formula>
        <label>Name Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProvinceResidency__c</fullName>
        <label>Province of Residency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Provinces</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Client Accounts</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Law_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Law Firm</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>Account.Account_Type__c</field>
                <operation>equals</operation>
                <value>Lawyer, Law Firm</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Law Firm</value>
            </filterItems>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Law Firm</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Clients</relationshipLabel>
        <relationshipName>Clients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name_Formula__c</fullName>
        <description>contacts having middle name cannot be queried using name like&apos;%Patricia Jean Shroeder%&apos; This field is desgned to be used in where clause of contact query in custom lookup LEX component.</description>
        <formula>IF( ISBLANK( FirstName ), &apos;&apos; , FirstName &amp; &apos; &apos; )&amp;
IF( ISBLANK( MiddleName ), &apos;&apos; , MiddleName &amp; &apos; &apos; )&amp;
IF( ISBLANK( LastName ), &apos;&apos; , LastName )</formula>
        <label>Name Formula</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Law_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Law Firm</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Referred Cases</relationshipLabel>
        <relationshipName>Referred_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lawyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lawyer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referred Cases</relationshipLabel>
        <relationshipName>Referred_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan_Requests__c</fullName>
        <label>Loan Requests</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1st Loan</fullName>
                </value>
                <value>
                    <fullName>2nd Loan</fullName>
                </value>
                <value>
                    <fullName>3rd Loan</fullName>
                </value>
                <value>
                    <fullName>4th Loan</fullName>
                </value>
                <value>
                    <fullName>5th Loan</fullName>
                </value>
                <value>
                    <fullName>6th Loan</fullName>
                </value>
                <value>
                    <fullName>7th Loan</fullName>
                </value>
                <value>
                    <fullName>8th Loan</fullName>
                </value>
                <value>
                    <fullName>9th Loan</fullName>
                </value>
                <value>
                    <fullName>10th Loan</fullName>
                </value>
                <value>
                    <fullName>11th Loan</fullName>
                </value>
                <value>
                    <fullName>12th Loan</fullName>
                </value>
                <value>
                    <fullName>13th Loan</fullName>
                </value>
                <value>
                    <fullName>14th Loan</fullName>
                </value>
                <value>
                    <fullName>15th Loan</fullName>
                </value>
                <value>
                    <fullName>16th Loan</fullName>
                </value>
                <value>
                    <fullName>17th Loan</fullName>
                </value>
                <value>
                    <fullName>18th Loan</fullName>
                </value>
                <value>
                    <fullName>19th Loan</fullName>
                </value>
                <value>
                    <fullName>20th Loan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Primary Contact)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecordTypeDev__c</fullName>
        <formula>RecordType.DeveloperName</formula>
        <label>RecordTypeDev</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Loan_Re_Assessment_Opportunity</fullName>
        <active>true</active>
        <businessProcess>Client Sales Fast-Track Process</businessProcess>
        <description>Use this record type to track the loan re-assessment process</description>
        <label>Loan Re-Assessment Opportunity</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <formula>TEXT(Account.Business_Unit__c)</formula>
    <label>Business Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ELFI</fullName>
    </customValue>
    <customValue>
        <fullName>Rhino</fullName>
    </customValue>
    <customValue>
        <fullName>Seahold</fullName>
    </customValue>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DuplicateRecordsCompCtlr.cls
/**
 * @description       : 
 * @author            : fahad.khan@toptal.com
 * @group             : 
 * @last modified on  : 10-27-2020
 * @last modified by  : fahad.khan@toptal.com
 * Modifications Log 
 * Ver   Date         Author                  Modification
 * 1.0   10-27-2020   fahad.khan@toptal.com   Initial Version
**/
public with sharing class DuplicateRecordsCompCtlr {
    @AuraEnabled
    public static List<Contact> getPotentialDuplicatesForAccount(String accountId){

        List<Account> PotentialDuplicates = new List<Account>();
        List<Contact> contactList = new List<Contact>();

        Set<String> mailingCities = new Set<String>();
        Set<String> mailingStates = new Set<String>();
        Set<String> mailingPostalCodes = new Set<String>();
        
        Contact conObj = [SELECT AccountId, Account.Formula_Name__c, Account.ProvinceResidency__c,
                          Id, Name, Name_Formula__c, MailingCity, MailingState, MailingPostalCode
                          FROM Contact
                          WHERE AccountId =:accountId 
                          ORDER BY CreatedDate DESC
                          LIMIT 1];

        String strQuery = 'SELECT Id, AccountId, Account.AccountNumber, Account.Name, Account.Business_Unit__c, Account.All_Payout_Balance__c,';
        strQuery += ' Name, Name_Formula__c, MailingCity, MailingState, MailingPostalCode,';
        strQuery += ' (Select Id, Lawyer__c, Law_Firm__c, Lawyer__r.Name, Law_Firm__r.Name from Opportunities1__r WHERE RecordTypeDev__c != \'Loan_Re_Assessment_Opportunity\''; 
        strQuery += ' ORDER BY Loan_Requests__c DESC LIMIT 1)';
        strQuery += ' FROM Contact WHERE (Account.Formula_Name__c LIKE \'%' + conObj.Account.Formula_Name__c + '%\'';
        strQuery += ' OR Name_Formula__c LIKE \'%' + conObj.Name + '%\')';
        strQuery += ' AND AccountId != \'' + accountId + '\'';
        strQuery += conObj.Account.ProvinceResidency__c != null? (' AND Account.ProvinceResidency__c = \'' + conObj.Account.ProvinceResidency__c + '\'') : '';
        strQuery += conObj.MailingCity != null? (' AND MailingCity = \'' + conObj.MailingCity +'\'') : '';
        strQuery += conObj.MailingState != null? (' AND MailingState = \'' + conObj.MailingState +'\'') : '';
        strQuery += conObj.MailingPostalCode != null? (' AND MailingPostalCode = \'' + conObj.MailingPostalCode +'\'') : '';
        strQuery += ' AND RecordType.Name LIKE \'%Client%\'';

        contactList = Database.query(strQuery);

        return contactList;

    }
}