src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Authorization_Clause__c</fullName>
        <description>This field is used to dynamically show the &apos;conflict/interest&apos; clause in the loan document.</description>
        <label>Authorization Clause</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the key person to contact about inquiries related to this account: loan related, additional information, payments, receivables, etc.</inlineHelpText>
        <label>Primary Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>There are no contacts under this account that matches the search criteria.</errorMessage>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <infoMessage>Please select the contact that will serve as primary contact for this account.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Client Accounts</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Law_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Law Firm</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>Account.Account_Type__c</field>
                <operation>equals</operation>
                <value>Lawyer, Law Firm</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Law Firm</value>
            </filterItems>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Law Firm</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Clients</relationshipLabel>
        <relationshipName>Clients</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Lawyers</fullName>
        <active>true</active>
        <description>Use this record type to track lawyers</description>
        <label>Lawyers</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Drawdown__c.object
<CustomObject>
    <fields>
        <fullName>Compounding_Interest__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The opportunity__r.compounding_Interest__c field has been replicated here to avoid exceeding cross object formula lmits.   Field was transformed to a checkbox to simplify usage in formulas as well.</description>
        <inlineHelpText>Indicates if loan interest is compounding or simple.</inlineHelpText>
        <label>Compounding Interest</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Interest_Deferral_Period__c</fullName>
        <description>The Interest Deferral Period from the Opportunity, replicated here to avoid cross object formula size limitations.  Also converted to an number from a picklist value so it&apos;s readily usable in formulas.</description>
        <inlineHelpText>The months to defer interest on this Drawdown.</inlineHelpText>
        <label>Interest Deferral Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <description>The interest rate pulled down from the Opportunity.  Duplicated here to allow formulas to access without exceeding limits.</description>
        <inlineHelpText>Loan Interest Rate</inlineHelpText>
        <label>Interest Rate</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Minimum_Interest_Period__c</fullName>
        <description>The minimum Interest period from the Opportunity.   Replicated here to avoid exceeding cross object formula limitations.</description>
        <inlineHelpText>The number of months of interest which must be charged at a minimum.</inlineHelpText>
        <label>Minimum Interest Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lump-Sum Admin Fee</fullName>
                </value>
                <value>
                    <fullName>Lump-Sum Amount Paid to Borrower</fullName>
                </value>
                <value>
                    <fullName>Facility Drawdown</fullName>
                    <default>true</default>
                    <label>Facility Drawdown</label>
                </value>
                <value>
                    <fullName>Treatment Loan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Compounding_Interest__c</fullName>
        <label>Interest Compounding Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Interest_Compounding_Period__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-Annual</fullName>
                </value>
                <value>
                    <fullName>Annual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interest_Compounding_Period__c</fullName>
        <label>Interest Compounding Period</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Simple Interest</fullName>
                </value>
                <value>
                    <fullName>Compounding Interest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interest_Deferral_Period__c</fullName>
        <label>Interest Deferral Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>48</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <label>Annual Interest Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Law_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Law Firm</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Referred Cases</relationshipLabel>
        <relationshipName>Referred_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lawyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lawyer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referred Cases</relationshipLabel>
        <relationshipName>Referred_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Minimum_Interest_Period__c</fullName>
        <label>Minimum Interest Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0 months</fullName>
                </value>
                <value>
                    <fullName>1 month</fullName>
                </value>
                <value>
                    <fullName>2 months</fullName>
                </value>
                <value>
                    <fullName>3 months</fullName>
                </value>
                <value>
                    <fullName>4 months</fullName>
                </value>
                <value>
                    <fullName>5 months</fullName>
                </value>
                <value>
                    <fullName>6 months</fullName>
                    <default>true</default>
                    <label>6 months</label>
                </value>
                <value>
                    <fullName>7 months</fullName>
                </value>
                <value>
                    <fullName>8 months</fullName>
                </value>
                <value>
                    <fullName>9 months</fullName>
                </value>
                <value>
                    <fullName>10 months</fullName>
                </value>
                <value>
                    <fullName>11 months</fullName>
                </value>
                <value>
                    <fullName>12 months</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Primary Contact)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage_Status__c</fullName>
        <label>Stage Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>1st Week</fullName>
                </value>
                <value>
                    <fullName>2nd Week</fullName>
                </value>
                <value>
                    <fullName>File for Review</fullName>
                </value>
                <value>
                    <fullName>Add&apos;l Docs Required</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>F/U with PC/Facility</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Assessor Declined</fullName>
                </value>
                <value>
                    <fullName>Legal Representative Declined</fullName>
                </value>
                <value>
                    <fullName>Non-Responsive (Legal Representative/Plaintiff)</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Contact Sheet Completed; Part I of App Sent to Lead for Signature</fullName>
                </value>
                <value>
                    <fullName>Part II of App Sent to Firm w/ Request for Supporting Docs</fullName>
                </value>
                <value>
                    <fullName>Waiting for Additional Supporting Documents</fullName>
                </value>
                <value>
                    <fullName>Waiting for Payout From Other Lender</fullName>
                </value>
                <value>
                    <fullName>File Sent to Assessors Review</fullName>
                </value>
                <value>
                    <fullName>Awaiting Final Client Signature</fullName>
                </value>
                <value>
                    <fullName>Funds Advanced/Awaiting Signed Loan Documents</fullName>
                </value>
                <value>
                    <fullName>Awaiting Final Lawyer Signature</fullName>
                </value>
                <value>
                    <fullName>File Sent for EFT</fullName>
                </value>
                <value>
                    <fullName>See Notes</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Bad Debt</fullName>
                </value>
                <value>
                    <fullName>Paid Off</fullName>
                </value>
                <value>
                    <fullName>Payments Halted</fullName>
                </value>
                <value>
                    <fullName>Partial Payment</fullName>
                </value>
                <value>
                    <fullName>Shortfall</fullName>
                </value>
                <value>
                    <fullName>Surplus</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Loan__c</fullName>
        <label>Type of Loan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Facility Loan</fullName>
                </value>
                <value>
                    <fullName>Lump-Sum</fullName>
                    <default>true</default>
                    <label>Lump-Sum</label>
                </value>
                <value>
                    <fullName>Treatment Loan</fullName>
                </value>
                <value>
                    <fullName>Treatment Loan 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/PaymentSummaryItemHelperTest.cls
@isTest
public class PaymentSummaryItemHelperTest {    
    @TestSetup
    static void initailizeTestData(){        
        List<Account> accountList = new List<Account>();
        List<Contact> contactList = new List<Contact>();
        
        accountList.add( new Account(Name = 'Test Client Account', Authorization_Clause__c = 'No', 
                                             RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId()));
        accountList.add( new Account(Name = 'Test LawFirm Account', Authorization_Clause__c = 'No', 
                                             RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Law Firm').getRecordTypeId()));
        
        insert accountList;       
        
        contactList.add( new Contact(LastName = 'Test Client Contact', AccountId = accountList[0].Id,
                                            RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Client Contact').getRecordTypeId()));
        contactList.add( new Contact(LastName = 'Test Lawyer Contact', AccountId = accountList[1].Id,
                                            RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Lawyers').getRecordTypeId()));
        insert contactList;
        
        Opportunity Opp = new Opportunity(Name = 'Test Opportunity', RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Client Opportunity Record Type').getRecordTypeId(),
                                          AccountId = accountList[0].Id);
        Opp.Lawyer__c = contactList[1].Id;
        Opp.CloseDate = Date.today().addDays(14);
        Opp.StageName = 'Closed With Loan';
        Opp.Law_Firm__c = accountList[1].Id;        
        Opp.Stage_Status__c = 'Approved';
        Opp.Type_of_Loan__c = 'Facility Loan';
        Opp.Primary_Contact__c = contactList[0].Id;
        Opp.Minimum_Interest_Period__c = '0 months';
        Opp.Compounding_Interest__c = 'Monthly';
        Opp.Interest_Rate__c = 15.0;
        Opp.Interest_Compounding_Period__c = 'Simple Interest';
        Opp.Interest_Deferral_Period__c = '0';
        insert Opp;        
    }
    
    public static void insertDrawdowns(String OppId){
        List<Drawdown__c> drawdownList = new List<Drawdown__c>();
        for(Integer i=0; i < 1; i++){
            drawdownList.add(new Drawdown__c(Type__c = 'Facility Drawdown', Date__c = Date.today(), Opportunity__c = OppId,
                                            Amount__c = 2000 + (i * 50)));
        }
        if(drawdownList.size() > 0){
            insert drawdownList;
        }
    }
    public static testMethod void testFillRealPaymentSummaryItem(){
        PaymentSummaryItem paymentSummaryItem = new PaymentSummaryItem();
        PaymentSummaryItemHelper.fillRealPaymentSummaryItem(paymentSummaryItem, 100.0, 50.0, 40.0, true);
        System.assertEquals('Partial Payment', paymentSummaryItem.referenceNotes);
        System.assertEquals(50.0, paymentSummaryItem.principal);
        System.assertEquals(40.0, paymentSummaryItem.interest);
    }
    public static testMethod void testFillRealPaymentSummaryItem1(){
        PaymentSummaryItem paymentSummaryItem = new PaymentSummaryItem();
        PaymentSummaryItemHelper.fillRealPaymentSummaryItem(paymentSummaryItem, 0.0, 50.0, 40.0, true);
        System.assertEquals('Loan Payout', paymentSummaryItem.referenceNotes);
        System.assertEquals(50.0, paymentSummaryItem.principal);
        System.assertEquals(40.0, paymentSummaryItem.interest);
    }    
    public static testMethod void testFillSurplusPaymentSummaryItem(){
        PaymentSummaryItem paymentSummaryItem = new PaymentSummaryItem();
        PaymentSummaryItemHelper.fillSurplusPaymentSummaryItem(paymentSummaryItem, -100.0);
        System.assertEquals('Payment Surplus', paymentSummaryItem.referenceNotes);
        System.assertEquals(100.0, paymentSummaryItem.surplus);        
    } 
    public static testMethod void testFillShortfallPaymentSummaryItem(){
        PaymentSummaryItem paymentSummaryItem = new PaymentSummaryItem();
        PaymentSummaryItemHelper.fillShortfallPaymentSummaryItem(paymentSummaryItem, -100.0, 0.0, 0.0);
        System.assertEquals('Payment Surplus', paymentSummaryItem.referenceNotes);
        System.assertEquals(100.0, paymentSummaryItem.surplus);        
    }
    public static testMethod void testFillShortfallPaymentSummaryItem1(){
        PaymentSummaryItem paymentSummaryItem = new PaymentSummaryItem();
        PaymentSummaryItemHelper.fillShortfallPaymentSummaryItem(paymentSummaryItem, 200.0, 100.0, 100.0);
        System.assertEquals('Payment Shortfall', paymentSummaryItem.referenceNotes);
        System.assertEquals(100.0, paymentSummaryItem.shortfallPrincipal);        
        System.assertEquals(100.0, paymentSummaryItem.shortfallInterest);        
    }
    public static testMethod void testFillBadDebtPaymentSummaryItem(){
        PaymentSummaryItem paymentSummaryItem = new PaymentSummaryItem();
        PaymentSummaryItemHelper.fillBadDebtPaymentSummaryItem(paymentSummaryItem, -100.0, 50.0, 40.0);
        System.assertEquals('Payment Surplus', paymentSummaryItem.referenceNotes);
        System.assertEquals(100.0, paymentSummaryItem.surplus);        
    }    
    public static testMethod void testFillBadDebtPaymentSummaryItem1(){
        PaymentSummaryItem paymentSummaryItem = new PaymentSummaryItem();
        PaymentSummaryItemHelper.fillBadDebtPaymentSummaryItem(paymentSummaryItem, 90.0, 50.0, 40.0);
        System.assertEquals('Bad Debt', paymentSummaryItem.referenceNotes);
        System.assertEquals(50.0, paymentSummaryItem.badDebtPrincipal);        
        System.assertEquals(40.0, paymentSummaryItem.badDebtInterest);        
    }
    public static testMethod void testFillBadDebtRecoveryPaymentSummaryItem(){
        PaymentSummaryItem paymentSummaryItem = new PaymentSummaryItem();
        PaymentSummaryItemHelper.fillBadDebtRecoveryPaymentSummaryItem(paymentSummaryItem, 100.0, 50.0);
        System.assertEquals('Bad Debt Recovery', paymentSummaryItem.referenceNotes);
        System.assertEquals(50.0, paymentSummaryItem.badDebtRecovery);       
    }
    public static testMethod void testFillOtherPaymentSummaryItem(){
        PaymentSummaryItem paymentSummaryItem = new PaymentSummaryItem();
        Drawdown__c d = new Drawdown__c(Payment_Method__c = 'Payment', Reference_Notes__c = 'Client Rebate', Amount__c = 100.0, Date__c = Date.today(), Principal_Repaid__c = 60.0, Interest_Repaid__c = 40.0);
        PaymentSummaryItemHelper.fillOtherPaymentSummaryItem(paymentSummaryItem, d);
        System.assertEquals('Client Rebate', paymentSummaryItem.referenceNotes);
    }
    public static testMethod void testGetPaymentSummaryItemWithReserve(){
        Opportunity opp = new Opportunity(Name = 'OppName');
        Drawdown__c drawdown = new Drawdown__c(Date__c = Date.today(), Payment_Method__c = 'Payment', Reference_Notes__c = 'Partial Payment');
        PaymentSummaryItem paymentSummaryItem = PaymentSummaryItemHelper.getPaymentSummaryItemWithReserve(drawdown, opp, 50.0, 50.0, 100.0, 0.0, 50.0, 50.0, true);
        System.assertEquals('Partial Payment', paymentSummaryItem.referenceNotes);
    }
    public static testMethod void testGetPaymentSummaryItemWithReserve1(){
        Opportunity opp = new Opportunity(Name = 'OppName');
        Drawdown__c drawdown = new Drawdown__c(Date__c = Date.today(), Payment_Method__c = 'Payment', Reference_Notes__c = 'Bad Debt');
        PaymentSummaryItem paymentSummaryItem = PaymentSummaryItemHelper.getPaymentSummaryItemWithReserve(drawdown, opp, 50.0, 50.0, 100.0, 0.0, 50.0, 50.0, true);
        System.assertEquals('Bad Debt', paymentSummaryItem.referenceNotes);
    }    
    public static testMethod void testGetPaymentSummaryItemWithReserve2(){
        Opportunity opp = new Opportunity(Name = 'OppName');
        Drawdown__c drawdown = new Drawdown__c(Date__c = Date.today(), Payment_Method__c = 'Payment', Reference_Notes__c = 'Payment Shortfall');
        PaymentSummaryItem paymentSummaryItem = PaymentSummaryItemHelper.getPaymentSummaryItemWithReserve(drawdown, opp, 50.0, 50.0, 100.0, 0.0, 50.0, 50.0, true);
        System.assertEquals('Payment Shortfall', paymentSummaryItem.referenceNotes);
    }  
    public static testMethod void testGetPaymentSummaryItemWithReserve3(){
        Opportunity opp = new Opportunity(Name = 'OppName');
        Drawdown__c drawdown = new Drawdown__c(Date__c = Date.today(), Payment_Method__c = 'Payment', Reference_Notes__c = 'Payment Surplus');
        PaymentSummaryItem paymentSummaryItem = PaymentSummaryItemHelper.getPaymentSummaryItemWithReserve(drawdown, opp, 50.0, 50.0, 100.0, 0.0, 50.0, 50.0, true);
        System.assertEquals('Payment Surplus', paymentSummaryItem.referenceNotes);
    }
    public static testMethod void testGetPaymentSummaryItemWithReserve4(){
        Opportunity opp = new Opportunity(Name = 'OppName');
        Drawdown__c drawdown = new Drawdown__c(Date__c = Date.today(), Payment_Method__c = 'Payment', Reference_Notes__c = 'Bad Debt Recovery');
        PaymentSummaryItem paymentSummaryItem = PaymentSummaryItemHelper.getPaymentSummaryItemWithReserve(drawdown, opp, 50.0, 50.0, 100.0, 0.0, 50.0, 50.0, true);
        System.assertEquals('Bad Debt Recovery', paymentSummaryItem.referenceNotes);
    } 
    public static testMethod void testGetPaymentSummaryItemWithReserve5(){
        Opportunity opp = new Opportunity(Name = 'OppName');
        Drawdown__c drawdown = new Drawdown__c(Date__c = Date.today(), Payment_Method__c = 'Payment', Reference_Notes__c = 'Payment Rejected');
        PaymentSummaryItem paymentSummaryItem = PaymentSummaryItemHelper.getPaymentSummaryItemWithReserve(drawdown, opp, 50.0, 50.0, 100.0, 0.0, 50.0, 50.0, true);
        System.assertEquals('Payment Rejected', paymentSummaryItem.referenceNotes);
    } 
    public static testMethod void testGetPaymentSummaryItemsWithReserve(){
        List<Opportunity> opps = new List<Opportunity>();
        opps.add(new Opportunity(Name = 'OppName', Is_Reserve_Applied__c = false));
        List<Drawdown__c> drawdowns = new List<Drawdown__c>();
        drawdowns.add(new Drawdown__c(Date__c = Date.today(), Payment_Method__c = 'Payment', Reference_Notes__c = 'Partial Payment', Principal_Repaid__c = 60.0, Interest_Repaid__c = 40.0));
        drawdowns.add(new Drawdown__c(Date__c = Date.today(), Payment_Method__c = 'Payment', Reference_Notes__c = 'Loan Payout', Principal_Repaid__c = 70.0, Interest_Repaid__c = 30.0));
        List<PaymentSummaryItem> items = PaymentSummaryItemHelper.getPaymentSummaryItemsWithReserve(opps, drawdowns);
        System.assertEquals(2, items.size());
        System.assertEquals(60.0, items[0].principal);
        System.assertEquals(40.0, items[0].interest);
        System.assertEquals(70.0, items[1].principal);
        System.assertEquals(30.0, items[1].interest);
    }     
    
    public static testMethod void testGetPaymentSummaryItems() {       
        List<Opportunity> clientOpportunities = [SELECT AccountId, Payout_Date__c, Reserve_Date__c, Reserve_Amount__c, Is_Reserve_Applied__c FROM Opportunity  LIMIT 1];
        insertDrawdowns(clientOpportunities[0].Id);
        List<Map<String, Object>> reserveInfos = new List<Map<String, Object>>();
        reserveInfos.add( new Map<String, Object>() );
        reserveInfos[0].put('Id', clientOpportunities[0].Id);
        reserveInfos[0].put('Is_Reserve_Applied__c', true);                
        reserveInfos[0].put('Reserve_Date__c', Date.today().addDays(10));
        List<Opportunity> opps = ReserveHelper.applyReserveOpps(reserveInfos);
        Drawdown__c drawdown = new Drawdown__c(Opportunity__c = clientOpportunities[0].Id, Date__c = Date.today().addDays(300), Payment_Method__c = 'Payment', Reference_Notes__c = 'Partial Payment', Amount__c = 10000.0);
        insert drawdown;
        Test.startTest();                
        List<PaymentSummaryItem> items = PaymentSummaryItemHelper.getPaymentSummaryItems(clientOpportunities[0].AccountId);
        System.assertEquals(1, items.size());
        System.assertEquals(2000.0, items[0].principal);
        System.assertEquals(247.40, items[0].interest);
        Test.stopTest();    
    }
    public static testMethod void testGetPaymentSummaryItems1() {       
        List<Opportunity> clientOpportunities = [SELECT AccountId, Payout_Date__c, Reserve_Date__c, Reserve_Amount__c, Is_Reserve_Applied__c FROM Opportunity  LIMIT 1];
        insertDrawdowns(clientOpportunities[0].Id);
        List<Map<String, Object>> reserveInfos = new List<Map<String, Object>>();
        reserveInfos.add( new Map<String, Object>() );
        reserveInfos[0].put('Id', clientOpportunities[0].Id);
        reserveInfos[0].put('Is_Reserve_Applied__c', true);        
        reserveInfos[0].put('Stop_Interest__c', true);        
        reserveInfos[0].put('Reserve_Date__c', Date.today().addDays(10));
        List<Opportunity> opps = ReserveHelper.applyReserveOpps(reserveInfos);
        Drawdown__c drawdown = new Drawdown__c(Opportunity__c = clientOpportunities[0].Id, Date__c = Date.today().addDays(300), Payment_Method__c = 'Payment', Reference_Notes__c = 'Partial Payment', Amount__c = 10000.0);
        insert drawdown;
        Test.startTest();                
        List<PaymentSummaryItem> items = PaymentSummaryItemHelper.getPaymentSummaryItems(clientOpportunities[0].AccountId);
        System.assertEquals(1, items.size());
        System.assertEquals(2000.0, items[0].principal);
        System.assertEquals(9.04, items[0].interest);
        Test.stopTest();
    }    
    public static testMethod void testGetPaymentSummaryItems2() {       
        List<Opportunity> clientOpportunities = [SELECT AccountId, Payout_Date__c, Reserve_Date__c, Reserve_Amount__c, Is_Reserve_Applied__c FROM Opportunity  LIMIT 1];
        insertDrawdowns(clientOpportunities[0].Id);
        List<Map<String, Object>> reserveInfos = new List<Map<String, Object>>();
        reserveInfos.add( new Map<String, Object>() );
        reserveInfos[0].put('Id', clientOpportunities[0].Id);
        reserveInfos[0].put('Is_Reserve_Applied__c', true);        
        reserveInfos[0].put('Stop_Interest__c', true);        
        reserveInfos[0].put('Reserve_Date__c', Date.today().addDays(10));
        List<Opportunity> opps = ReserveHelper.applyReserveOpps(reserveInfos);        
        Drawdown__c drawdown = new Drawdown__c(Opportunity__c = clientOpportunities[0].Id, Date__c = Date.today().addDays(300), Payment_Method__c = 'Payment', Reference_Notes__c = 'Bad Debt', Amount__c = 2247.4);
        insert drawdown;
        Test.startTest();                
        List<PaymentSummaryItem> items = PaymentSummaryItemHelper.getPaymentSummaryItems(clientOpportunities[0].AccountId);
        System.assertEquals(1, items.size());
        System.assertEquals(2000.0, items[0].badDebtPrincipal);
        System.assertEquals(9.04, items[0].badDebtInterest);
        Test.stopTest();
    }
    
    public static testMethod void testGetLastPaymentSummaryItems() {          
        List<Opportunity> clientOpportunities = [SELECT AccountId, Payout_Date__c, Reserve_Date__c, Reserve_Amount__c, Is_Reserve_Applied__c FROM Opportunity  LIMIT 1];
        insertDrawdowns(clientOpportunities[0].Id);
        List<Map<String, Object>> reserveInfos = new List<Map<String, Object>>();
        reserveInfos.add( new Map<String, Object>() );
        reserveInfos[0].put('Id', clientOpportunities[0].Id);
        reserveInfos[0].put('Is_Reserve_Applied__c', true);        
        reserveInfos[0].put('Stop_Interest__c', true);        
        reserveInfos[0].put('Reserve_Date__c', Date.today().addDays(10));
        List<Opportunity> opps = ReserveHelper.applyReserveOpps(reserveInfos);        
        Drawdown__c drawdown = new Drawdown__c(Opportunity__c = clientOpportunities[0].Id, Date__c = Date.today().addDays(300), Payment_Method__c = 'Payment', Reference_Notes__c = 'Bad Debt', Amount__c = 2247.4);
        insert drawdown;
        Test.startTest();                
        List<Id> paymentIds = new List<Id>{drawdown.Id};        
        List<PaymentSummaryItem> items = PaymentSummaryItemHelper.getLastPaymentSummaryItems(clientOpportunities[0].AccountId, paymentIds);
        System.assertEquals(1, items.size());
        System.assertEquals(2000.0, items[0].badDebtPrincipal);
        System.assertEquals(9.04, items[0].badDebtInterest);
        Test.stopTest();
    }

}