src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Authorization_Clause__c</fullName>
        <description>This field is used to dynamically show the &apos;conflict/interest&apos; clause in the loan document.</description>
        <label>Authorization Clause</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the key person to contact about inquiries related to this account: loan related, additional information, payments, receivables, etc.</inlineHelpText>
        <label>Primary Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>There are no contacts under this account that matches the search criteria.</errorMessage>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <infoMessage>Please select the contact that will serve as primary contact for this account.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Client Accounts</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Is_Reserve_Applied__c.field-meta.xml
<CustomField>
    <fullName>Is_Reserve_Applied__c</fullName>
    <formula>Reserved_Loans_Count__c &gt; 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Reserve Applied</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Law_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Law Firm</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>Account.Account_Type__c</field>
                <operation>equals</operation>
                <value>Lawyer, Law Firm</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Law Firm</value>
            </filterItems>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Law Firm</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Clients</relationshipLabel>
        <relationshipName>Clients</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Lawyers</fullName>
        <active>true</active>
        <description>Use this record type to track lawyers</description>
        <label>Lawyers</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Compounding_Interest__c</fullName>
        <label>Interest Compounding Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Interest_Compounding_Period__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-Annual</fullName>
                </value>
                <value>
                    <fullName>Annual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interest_Compounding_Period__c</fullName>
        <label>Interest Compounding Period</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Simple Interest</fullName>
                </value>
                <value>
                    <fullName>Compounding Interest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interest_Deferral_Period__c</fullName>
        <label>Interest Deferral Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>48</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <label>Annual Interest Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Law_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Law Firm</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Referred Cases</relationshipLabel>
        <relationshipName>Referred_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lawyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lawyer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referred Cases</relationshipLabel>
        <relationshipName>Referred_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan_Status__c</fullName>
        <inlineHelpText>Use this field to indicate the current status of the loan.</inlineHelpText>
        <label>Loan Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Active - Partial Payment</fullName>
                </value>
                <value>
                    <fullName>Closed - Paid</fullName>
                </value>
                <value>
                    <fullName>Closed - Bad Debt</fullName>
                </value>
                <value>
                    <fullName>Closed - Bad Debt - Making Payments</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Minimum_Interest_Period__c</fullName>
        <label>Minimum Interest Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0 months</fullName>
                </value>
                <value>
                    <fullName>1 month</fullName>
                </value>
                <value>
                    <fullName>2 months</fullName>
                </value>
                <value>
                    <fullName>3 months</fullName>
                </value>
                <value>
                    <fullName>4 months</fullName>
                </value>
                <value>
                    <fullName>5 months</fullName>
                </value>
                <value>
                    <fullName>6 months</fullName>
                    <default>true</default>
                    <label>6 months</label>
                </value>
                <value>
                    <fullName>7 months</fullName>
                </value>
                <value>
                    <fullName>8 months</fullName>
                </value>
                <value>
                    <fullName>9 months</fullName>
                </value>
                <value>
                    <fullName>10 months</fullName>
                </value>
                <value>
                    <fullName>11 months</fullName>
                </value>
                <value>
                    <fullName>12 months</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Primary Contact)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage_Status__c</fullName>
        <label>Stage Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>1st Week</fullName>
                </value>
                <value>
                    <fullName>2nd Week</fullName>
                </value>
                <value>
                    <fullName>File for Review</fullName>
                </value>
                <value>
                    <fullName>Add&apos;l Docs Required</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>F/U with PC/Facility</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Assessor Declined</fullName>
                </value>
                <value>
                    <fullName>Legal Representative Declined</fullName>
                </value>
                <value>
                    <fullName>Non-Responsive (Legal Representative/Plaintiff)</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Contact Sheet Completed; Part I of App Sent to Lead for Signature</fullName>
                </value>
                <value>
                    <fullName>Part II of App Sent to Firm w/ Request for Supporting Docs</fullName>
                </value>
                <value>
                    <fullName>Waiting for Additional Supporting Documents</fullName>
                </value>
                <value>
                    <fullName>Waiting for Payout From Other Lender</fullName>
                </value>
                <value>
                    <fullName>File Sent to Assessors Review</fullName>
                </value>
                <value>
                    <fullName>Awaiting Final Client Signature</fullName>
                </value>
                <value>
                    <fullName>Funds Advanced/Awaiting Signed Loan Documents</fullName>
                </value>
                <value>
                    <fullName>Awaiting Final Lawyer Signature</fullName>
                </value>
                <value>
                    <fullName>File Sent for EFT</fullName>
                </value>
                <value>
                    <fullName>See Notes</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Bad Debt</fullName>
                </value>
                <value>
                    <fullName>Paid Off</fullName>
                </value>
                <value>
                    <fullName>Payments Halted</fullName>
                </value>
                <value>
                    <fullName>Partial Payment</fullName>
                </value>
                <value>
                    <fullName>Shortfall</fullName>
                </value>
                <value>
                    <fullName>Surplus</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Loan__c</fullName>
        <label>Type of Loan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Facility Loan</fullName>
                </value>
                <value>
                    <fullName>Lump-Sum</fullName>
                    <default>true</default>
                    <label>Lump-Sum</label>
                </value>
                <value>
                    <fullName>Treatment Loan</fullName>
                </value>
                <value>
                    <fullName>Treatment Loan 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Assessment_Provider__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Provider</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Assessment Provider account must be of type Assessment Provider</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Assessment Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assessment Provider Referred Cases</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_Reserve_Applied__c.field-meta.xml
<CustomField>
    <fullName>Is_Reserve_Applied__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Reserve Applied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reserve_Date__c.field-meta.xml
<CustomField>
    <fullName>Reserve_Date__c</fullName>
    <label>Reserve Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stop_Interest__c.field-meta.xml
<CustomField>
    <fullName>Stop_Interest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Stop Interest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHandlerTest.cls
@isTest
public class OpportunityTriggerHandlerTest {
    
    @isTest static void setDiscountscheduleTest(){
        Test.startTest();
        Account NewTestAcc = new Account();
        NewTestAcc.Name = 'Test LawFirm Account';
        NewTestAcc.Authorization_Clause__c = 'No';
        NewTestAcc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Law Firm').getRecordTypeId();
        Insert NewTestAcc;
        
        Account NewTestAccAssess = new Account();
        NewTestAccAssess.Name = 'Assessment Account';
        NewTestAccAssess.Authorization_Clause__c = 'No';
        NewTestAccAssess.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Assessment Provider').getRecordTypeId();
        Insert NewTestAccAssess;
        
        Contact NewTestCon = new Contact();
        NewTestCon.FirstName = 'Test';
        NewTestCon.LastName = 'Lawyer Contact';
        NewTestCon.AccountId = NewTestAcc.Id;
        NewTestCon.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Lawyers').getRecordTypeId();
        Insert NewTestCon;
        
        Contact ClientCon = new Contact();
        ClientCon.FirstName = 'Test';
        ClientCon.LastName = 'Client Contact';
        ClientCon.AccountId = NewTestAcc.Id;
        ClientCon.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Client Contact').getRecordTypeId();
        Insert ClientCon;
        
        Assessment_Provider_Schedule__c NewTestAps = new Assessment_Provider_Schedule__c();
        NewTestAps.Lawyer__c = NewTestCon.Id;
        NewTestAps.Assessment_Provider__c = NewTestAccAssess.Id;
        NewTestAps.Discount__c = 30;
        NewTestAps.Rebate_Discount__c = 10;
        Insert NewTestAps;
        
        Opportunity NewTestOpp = new Opportunity();
        NewTestOpp.Type_of_Loan__c = 'Assessment';
        NewTestOpp.Name = 'Test Opportunity';
        NewTestOpp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Client Opportunity Record Type').getRecordTypeId();
        NewTestOpp.Lawyer__c = NewTestCon.Id;
        NewTestOpp.CloseDate = Date.today().addDays(14);
        NewTestOpp.StageName = 'Closed With Loan';
        NewTestOpp.Law_Firm__c = NewTestAcc.Id;  
        NewTestOpp.Stage_Status__c = 'Approved';
        NewTestOpp.Primary_Contact__c = ClientCon.Id;
        NewTestOpp.Minimum_Interest_Period__c = '0 months';
        NewTestOpp.Compounding_Interest__c = 'Monthly';
        NewTestOpp.Interest_Rate__c = 15.0;
        NewTestOpp.Interest_Compounding_Period__c = 'Simple Interest';
        NewTestOpp.Interest_Deferral_Period__c = '0';
        NewTestOpp.Assessment_Provider__c = NewTestAccAssess.Id;
        Insert NewTestOpp;
        
        Account AccForUpdate = new Account();
        AccForUpdate.Name = 'New testing account';
        AccForUpdate.Authorization_Clause__c = 'No';
        AccForUpdate.RecordTypeId = NewTestAccAssess.RecordTypeId;
        Insert AccForUpdate;
        
        
        Opportunity Opps = [SELECT Id, Assessment_Provider__c FROM Opportunity Where Id =: NewTestOpp.Id];
        Opps.Assessment_Provider__c = AccForUpdate.Id;
        Update Opps;
        Test.stopTest();
    }
    
    @isTest static void lawyerAvailableCreditRollUpsTest1(){
        Test.startTest();
        Account NewTestAcc = new Account();
        NewTestAcc.Name = 'Test LawFirm Account';
        NewTestAcc.Authorization_Clause__c = 'No';
        NewTestAcc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Law Firm').getRecordTypeId();
        Insert NewTestAcc;
        
        Account NewTestAccAssess = new Account();
        NewTestAccAssess.Name = 'Assessment Account';
        NewTestAccAssess.Authorization_Clause__c = 'No';
        NewTestAccAssess.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Assessment Provider').getRecordTypeId();
        Insert NewTestAccAssess;
        
        Contact NewTestCon = new Contact();
        NewTestCon.FirstName = 'Test';
        NewTestCon.LastName = 'Lawyer Contact';
        NewTestCon.AccountId = NewTestAcc.Id;
        NewTestCon.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Lawyers').getRecordTypeId();
        Insert NewTestCon;
        
        Contact ClientCon = new Contact();
        ClientCon.FirstName = 'Test';
        ClientCon.LastName = 'Client Contact';
        ClientCon.AccountId = NewTestAcc.Id;
        ClientCon.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Client Contact').getRecordTypeId();
        Insert ClientCon;
        
        Assessment_Provider_Schedule__c NewTestAps = new Assessment_Provider_Schedule__c();
        NewTestAps.Lawyer__c = NewTestCon.Id;
        NewTestAps.Assessment_Provider__c = NewTestAccAssess.Id;
        NewTestAps.Discount__c = 30;
        NewTestAps.Rebate_Discount__c = 10;
        Insert NewTestAps;
        
        Opportunity NewTestOpp = new Opportunity();
        NewTestOpp.Type_of_Loan__c = 'Assessment';
        NewTestOpp.Name = 'Test Opportunity';
        NewTestOpp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Client Opportunity Record Type').getRecordTypeId();
        NewTestOpp.Lawyer__c = NewTestCon.Id;
        NewTestOpp.CloseDate = Date.today().addDays(14);
        NewTestOpp.StageName = 'Closed With Loan';
        NewTestOpp.Law_Firm__c = NewTestAcc.Id;  
        NewTestOpp.Stage_Status__c = 'Active';
        NewTestOpp.Primary_Contact__c = ClientCon.Id;
        NewTestOpp.Minimum_Interest_Period__c = '0 months';
        NewTestOpp.Compounding_Interest__c = 'Monthly';
        NewTestOpp.Interest_Rate__c = 15.0;
        NewTestOpp.Interest_Compounding_Period__c = 'Simple Interest';
        NewTestOpp.Interest_Deferral_Period__c = '0';
        NewTestOpp.Assessment_Provider__c = NewTestAccAssess.Id;
        Insert NewTestOpp;
        
        
        Test.stopTest();
    }
    
    @isTest static void lawyerAvailableCreditRollUpsTest2(){
        Test.startTest();
        Account NewTestAcc = new Account();
        NewTestAcc.Name = 'Test LawFirm Account';
        NewTestAcc.Authorization_Clause__c = 'No';
        NewTestAcc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Law Firm').getRecordTypeId();
        Insert NewTestAcc;
        
        Account NewTestAccAssess = new Account();
        NewTestAccAssess.Name = 'Assessment Account';
        NewTestAccAssess.Authorization_Clause__c = 'No';
        NewTestAccAssess.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Assessment Provider').getRecordTypeId();
        Insert NewTestAccAssess;
        
        Contact NewTestCon = new Contact();
        NewTestCon.FirstName = 'Test';
        NewTestCon.LastName = 'Lawyer Contact';
        NewTestCon.AccountId = NewTestAcc.Id;
        NewTestCon.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Lawyers').getRecordTypeId();
        Insert NewTestCon;
        
        Contact ClientCon = new Contact();
        ClientCon.FirstName = 'Test';
        ClientCon.LastName = 'Client Contact';
        ClientCon.AccountId = NewTestAcc.Id;
        ClientCon.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Client Contact').getRecordTypeId();
        Insert ClientCon;
        
        Assessment_Provider_Schedule__c NewTestAps = new Assessment_Provider_Schedule__c();
        NewTestAps.Lawyer__c = NewTestCon.Id;
        NewTestAps.Assessment_Provider__c = NewTestAccAssess.Id;
        NewTestAps.Discount__c = 30;
        NewTestAps.Rebate_Discount__c = 10;
        Insert NewTestAps;
        
        Opportunity NewTestOpp = new Opportunity();
        NewTestOpp.Type_of_Loan__c = 'Assessment';
        NewTestOpp.Name = 'Test Opportunity';
        NewTestOpp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Client Opportunity Record Type').getRecordTypeId();
        NewTestOpp.Lawyer__c = NewTestCon.Id;
        NewTestOpp.CloseDate = Date.today().addDays(14);
        NewTestOpp.StageName = 'Loan Approved';
        NewTestOpp.Law_Firm__c = NewTestAcc.Id;  
        NewTestOpp.Stage_Status__c = 'Invoice Pre-Approved';
        NewTestOpp.Primary_Contact__c = ClientCon.Id;
        NewTestOpp.Minimum_Interest_Period__c = '0 months';
        NewTestOpp.Compounding_Interest__c = 'Monthly';
        NewTestOpp.Interest_Rate__c = 15.0;
        NewTestOpp.Interest_Compounding_Period__c = 'Simple Interest';
        NewTestOpp.Interest_Deferral_Period__c = '0';
        NewTestOpp.Assessment_Provider__c = NewTestAccAssess.Id;
        Insert NewTestOpp;
        
        
        Test.stopTest();
    }
    
    public static testMethod void updateLoanStatusTest() {        
                Account NewTestAcc = new Account();
        NewTestAcc.Name = 'Test LawFirm Account';
        NewTestAcc.Authorization_Clause__c = 'No';
        NewTestAcc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Law Firm').getRecordTypeId();
        Insert NewTestAcc;
        
        Contact ClientCon = new Contact();
        ClientCon.FirstName = 'Test';
        ClientCon.LastName = 'Client Contact';
        ClientCon.AccountId = NewTestAcc.Id;
        ClientCon.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Client Contact').getRecordTypeId();
        Insert ClientCon;

        Opportunity NewTestOpp = new Opportunity();
        NewTestOpp.Type_of_Loan__c = 'Facility Loan';
        NewTestOpp.Name = 'Test Opportunity';
        NewTestOpp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Client Opportunity Record Type').getRecordTypeId();        
        NewTestOpp.CloseDate = Date.today().addDays(14);
        NewTestOpp.StageName = 'Closed With Loan';        
        NewTestOpp.Stage_Status__c = 'Active';
        NewTestOpp.Primary_Contact__c = ClientCon.Id;
        NewTestOpp.Minimum_Interest_Period__c = '0 months';
        NewTestOpp.Compounding_Interest__c = 'Monthly';
        NewTestOpp.Interest_Rate__c = 15.0;
        NewTestOpp.Interest_Compounding_Period__c = 'Simple Interest';
        NewTestOpp.Interest_Deferral_Period__c = '0';
        NewTestOpp.Is_Reserve_Applied__c = true;
        NewTestOpp.Reserve_Date__c = Date.today();
        Insert NewTestOpp;
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
        Test.startTest();
        opp.Stage_Status__c = 'Active - Collections';
        update opp;
        opp = [SELECT Id, Stage_Status__c, Loan_Status__c FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];        
        System.assertEquals('Active - Collections', opp.Loan_Status__c);
        Test.stopTest();
    }
    
    public static testMethod void sendEmailOnReserveChangeTest() {
        Account NewTestAcc = new Account();
        NewTestAcc.Name = 'Test LawFirm Account';
        NewTestAcc.Authorization_Clause__c = 'No';
        NewTestAcc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Law Firm').getRecordTypeId();
        Insert NewTestAcc;
        
        Contact ClientCon = new Contact();
        ClientCon.FirstName = 'Test';
        ClientCon.LastName = 'Client Contact';
        ClientCon.AccountId = NewTestAcc.Id;
        ClientCon.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Client Contact').getRecordTypeId();
        Insert ClientCon;

        Opportunity NewTestOpp = new Opportunity();
        NewTestOpp.Type_of_Loan__c = 'Facility Loan';
        NewTestOpp.Name = 'Test Opportunity';
        NewTestOpp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Client Opportunity Record Type').getRecordTypeId();        
        NewTestOpp.CloseDate = Date.today().addDays(14);
        NewTestOpp.StageName = 'Closed With Loan';        
        NewTestOpp.Stage_Status__c = 'Active';
        NewTestOpp.Primary_Contact__c = ClientCon.Id;
        NewTestOpp.Minimum_Interest_Period__c = '0 months';
        NewTestOpp.Compounding_Interest__c = 'Monthly';
        NewTestOpp.Interest_Rate__c = 15.0;
        NewTestOpp.Interest_Compounding_Period__c = 'Simple Interest';
        NewTestOpp.Interest_Deferral_Period__c = '0';
        insert NewTestOpp;
        Test.startTest();
		Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];        
        Map<String, Object> reserveInfoMap = new Map<String, Object>();
        reserveInfoMap.put('Id', opp.Id);
        reserveInfoMap.put('Is_Reserve_Applied__c', true);
        reserveInfoMap.put('Stop_Interest__c', true);
        reserveInfoMap.put('Reserve_Date__c', Date.today());
        reserveInfoMap.put('Reserve_Amount__c', 100.0);
        List<Map<String, Object>> reserveInfos = new List<Map<String, Object>>{reserveInfoMap};
        ReserveHelper.applyReserveOpps(reserveInfos);
        Test.stopTest();
    }
    
    public static testMethod void clearReserveAmountWhenClosedTest() {        
        Account NewTestAcc = new Account();
        NewTestAcc.Name = 'Test LawFirm Account';
        NewTestAcc.Authorization_Clause__c = 'No';
        NewTestAcc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Law Firm').getRecordTypeId();
        Insert NewTestAcc;
        
        Contact ClientCon = new Contact();
        ClientCon.FirstName = 'Test';
        ClientCon.LastName = 'Client Contact';
        ClientCon.AccountId = NewTestAcc.Id;
        ClientCon.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Client Contact').getRecordTypeId();
        Insert ClientCon;

        Opportunity NewTestOpp = new Opportunity();
        NewTestOpp.Type_of_Loan__c = 'Facility Loan';
        NewTestOpp.Name = 'Test Opportunity';
        NewTestOpp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Client Opportunity Record Type').getRecordTypeId();        
        NewTestOpp.CloseDate = Date.today().addDays(14);
        NewTestOpp.StageName = 'Closed With Loan';        
        NewTestOpp.Stage_Status__c = 'Active';
        NewTestOpp.Primary_Contact__c = ClientCon.Id;
        NewTestOpp.Minimum_Interest_Period__c = '0 months';
        NewTestOpp.Compounding_Interest__c = 'Monthly';
        NewTestOpp.Interest_Rate__c = 15.0;
        NewTestOpp.Interest_Compounding_Period__c = 'Simple Interest';
        NewTestOpp.Interest_Deferral_Period__c = '0';
        NewTestOpp.Is_Reserve_Applied__c = true;
        NewTestOpp.Reserve_Amount__c = 1000.0;
        NewTestOpp.Reserve_Date__c = Date.today();
        insert NewTestOpp;
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
        Test.startTest();
        opp.Stage_Status__c = 'Closed - Paid';
        update opp;
        opp = [SELECT Id, Reserve_Amount__c FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];        
        System.assertEquals(0.0, opp.Reserve_Amount__c);
        Test.stopTest();
    }
    
}