src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Is_Async_Processing__c.field-meta.xml
<CustomField>
    <fullName>Is_Async_Processing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Async Processing</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Drawdown__c.object
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/DeleteDrawdownQueueable.cls
public class DeleteDrawdownQueueable implements Queueable{
    public String drawdownId;	
    public String accountId;	
    public DeleteDrawdownQueueable(String drawdownId, String accountId){
        this.drawdownId = drawdownId;        
        this.accountId = accountId;        
    }
    public void execute(QueueableContext context) {
        try{
            Drawdown__c d = [select Id from Drawdown__c where Id=:drawdownId];
            delete d;
        }
        catch(Exception ex){
            
        }
        Account acc = [select Is_Async_Processing__c from Account where Id=:accountId];
        acc.Is_Async_Processing__c = false;
        update acc;   
    }
}