src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospective Client</fullName>
                </value>
                <value>
                    <fullName>Prospective Lawyer</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Lawyer</fullName>
                </value>
                <value>
                    <fullName>Law Firm</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Treatment Provider Firm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Client Accounts</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Conversion_Flag__c.field-meta.xml
<CustomField>
    <fullName>Conversion_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Conversion Flag</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Prospective Client</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Lawyer</fullName>
                </value>
                <value>
                    <fullName>Law Firm</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ELF_File_No__c</fullName>
        <label>File No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/Conversion_Flag__c.field-meta.xml
<CustomField>
    <fullName>Conversion_Flag__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Conversion Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHandler.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 09-17-2020
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   09-17-2020   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public class AccountTriggerHandler {
    public static void validateAccountCreation(List<Account> newAccounts){
        for (Account account : newAccounts){
            if (!account.Conversion_Flag__c && account.Account_Type__c == 'Client' && !Test.isRunningTest())
                account.addError('Please start with creating a Lead for adding new clients');
        }
    }
    
    public static void propagateFileNo(Boolean isInsert, Map<Id, Account> oldMap, List<Account> newAccounts){
        Map<Id, Account> selectedAccountsMap = new Map<Id, Account>();
        for (Account account : newAccounts){
            if (isInsert || account.AccountNumber != oldMap.get(account.Id).AccountNumber){
                System.debug('Propagate');
                selectedAccountsMap.put(account.Id, account);
            }
        }
        if (!selectedAccountsMap.isEmpty()){
            List<Contact> contacts = [select ELF_File_No__c, AccountId from Contact where AccountId in :selectedAccountsMap.keySet()];
            if (!contacts.isEmpty()){
                for (Contact contact : contacts){
                    System.debug('Propagate ' + selectedAccountsMap.get(contact.AccountId).AccountNumber);
                    contact.ELF_File_No__c = selectedAccountsMap.get(contact.AccountId).AccountNumber;
                }
                update contacts;
            }
        }
        
    }
    public static void fillFileNo(Boolean isInsert, Map<Id, Account> oldMap, List<Account> newAccounts){
        List<RecordType> recordTypes = [SELECT Id, Name FROM RecordType Where SobjectType = 'Account'];
        String query = 'select RecordTypeId';
        
    }
}