src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>Mapped from the Lead</description>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Unit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Name_Formula__c</fullName>
        <formula>IF(CONTAINS( TRIM(Name)   , &apos;- Account # &apos;),  SUBSTITUTE(Name, &apos;- Account # &apos;, &apos;- 0000&apos;),  IF(CONTAINS( TRIM(Name)   , &apos;-Account # &apos;), SUBSTITUTE(Name, &apos;-Account # &apos;, &apos;- 0000&apos;), IF(CONTAINS( TRIM(Name)   , &apos;- Account #&apos;), SUBSTITUTE(Name, &apos;- Account #&apos;, &apos;- 0000&apos;),  IF(CONTAINS( TRIM(Name)   , &apos;-Account #&apos;), SUBSTITUTE(Name, &apos;-Account #&apos;, &apos;- 0000&apos;), TRIM(Name)) ) ) )</formula>
        <label>Name Formula</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Client Accounts</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Drawdown__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Drawdowns</relationshipLabel>
        <relationshipName>Drawdowns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Admin Fee</fullName>
                </value>
                <value>
                    <fullName>Cheque</fullName>
                </value>
                <value>
                    <fullName>e-Transfer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reference_Notes__c</fullName>
        <label>Reference Notes</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Payment_Method__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Admin Fee</fullName>
                </value>
                <value>
                    <fullName>Admin Fee charged up front</fullName>
                </value>
                <value>
                    <fullName>Bad Debt</fullName>
                </value>
                <value>
                    <fullName>EFT Reject</fullName>
                </value>
                <value>
                    <fullName>EFT Reprocessed</fullName>
                </value>
                <value>
                    <fullName>EFT to Client</fullName>
                </value>
                <value>
                    <fullName>Fee</fullName>
                </value>
                <value>
                    <fullName>Loan Payout</fullName>
                </value>
                <value>
                    <fullName>Other Fee</fullName>
                </value>
                <value>
                    <fullName>Partial Payment</fullName>
                </value>
                <value>
                    <fullName>Payment Rejected</fullName>
                </value>
                <value>
                    <fullName>Payment Re-processed</fullName>
                </value>
                <value>
                    <fullName>Payment Shortfall</fullName>
                </value>
                <value>
                    <fullName>Payment Surplus</fullName>
                </value>
                <value>
                    <fullName>Payment to Client</fullName>
                </value>
                <value>
                    <fullName>Payment to Lawyer</fullName>
                </value>
                <value>
                    <fullName>Payment to other lender</fullName>
                </value>
                <value>
                    <fullName>Payment to Third-Party</fullName>
                </value>
                <value>
                    <fullName>Payment to Treatment - Service Provider</fullName>
                </value>
                <value>
                    <fullName>Referral Fee</fullName>
                </value>
                <value>
                    <fullName>Waived Fee</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Is_Rejected__c.field-meta.xml
<CustomField>
    <fullName>Is_Rejected__c</fullName>
    <formula>Rejections_Count__c &gt; 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Rejected</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Law_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Law Firm</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Referred Cases</relationshipLabel>
        <relationshipName>Referred_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lawyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lawyer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referred Cases</relationshipLabel>
        <relationshipName>Referred_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage_Status__c</fullName>
        <label>Stage Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>1st Week</fullName>
                </value>
                <value>
                    <fullName>2nd Week</fullName>
                </value>
                <value>
                    <fullName>File for Review</fullName>
                </value>
                <value>
                    <fullName>Add&apos;l Docs Required</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>F/U with PC/Facility</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Assessor Declined</fullName>
                </value>
                <value>
                    <fullName>Legal Representative Declined</fullName>
                </value>
                <value>
                    <fullName>Non-Responsive (Legal Representative/Plaintiff)</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Contact Sheet Completed; Part I of App Sent to Lead for Signature</fullName>
                </value>
                <value>
                    <fullName>Part II of App Sent to Firm w/ Request for Supporting Docs</fullName>
                </value>
                <value>
                    <fullName>Waiting for Additional Supporting Documents</fullName>
                </value>
                <value>
                    <fullName>Waiting for Payout From Other Lender</fullName>
                </value>
                <value>
                    <fullName>File Sent to Assessors Review</fullName>
                </value>
                <value>
                    <fullName>Awaiting Final Client Signature</fullName>
                </value>
                <value>
                    <fullName>Funds Advanced/Awaiting Signed Loan Documents</fullName>
                </value>
                <value>
                    <fullName>Awaiting Final Lawyer Signature</fullName>
                </value>
                <value>
                    <fullName>File Sent for EFT</fullName>
                </value>
                <value>
                    <fullName>See Notes</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Bad Debt</fullName>
                </value>
                <value>
                    <fullName>Paid Off</fullName>
                </value>
                <value>
                    <fullName>Payments Halted</fullName>
                </value>
                <value>
                    <fullName>Partial Payment</fullName>
                </value>
                <value>
                    <fullName>Shortfall</fullName>
                </value>
                <value>
                    <fullName>Surplus</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Loan__c</fullName>
        <label>Type of Loan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Facility Loan</fullName>
                </value>
                <value>
                    <fullName>Lump-Sum</fullName>
                    <default>true</default>
                    <label>Lump-Sum</label>
                </value>
                <value>
                    <fullName>Treatment Loan</fullName>
                </value>
                <value>
                    <fullName>Treatment Loan 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <formula>TEXT(Account.Business_Unit__c)</formula>
    <label>Business Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Closed_Date__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Closed_Date__c</fullName>
    <label>Opportunity Closed Date</label>
    <summarizedField>Drawdown__c.Date__c</summarizedField>
    <summaryFilterItems>
        <field>Drawdown__c.Payment_Method__c</field>
        <operation>equals</operation>
        <value>Payment</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Drawdown__c.Reference_Notes__c</field>
        <operation>equals</operation>
        <value>Loan Payout, Payment Shortfall, Payment Surplus</value>
    </summaryFilterItems>
    <summaryForeignKey>Drawdown__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ELFI</fullName>
    </customValue>
    <customValue>
        <fullName>Rhino</fullName>
    </customValue>
    <customValue>
        <fullName>Seahold</fullName>
    </customValue>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LawyerSalesSummaryViewAllCtlr.cls
/**
 * @File Name          : LawyerSalesSummaryViewAllCtlr.cls
 * @Description        : 
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 08-11-2020
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    07/04/2020   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/
public class LawyerSalesSummaryViewAllCtlr {
    
    public Date startDate{get;set;}
    public Date endDate{get;set;}
    public List<String> businessUnit{get;set;}
    public string businessUnitString{get;set;}
    public String searchByName{get;set;}
    public List<String> typeOfLoan{get;set;}
    public String contentType{get;set;}
    public String renderAs{get;set;}
    
    public LawyerSalesSummaryViewAllCtlr(){
        
        contentType = '';
        renderAs = '';
        Date dt = Date.today();
        
        Date startDt = Date.valueOf(startDate);
        Date endDt = Date.valueOf(endDate);
        
        List<String> paramBusinessUnit = ApexPages.currentPage().getParameters().get('BusinessUnit').split(',');
        String paramStartDate = ApexPages.currentPage().getParameters().get('StartDate');
        String paramEndDate = ApexPages.currentPage().getParameters().get('EndDate');
        String paramContentType = ApexPages.currentPage().getParameters().get('ContentType');
        
        String paramSearchByName = ApexPages.currentPage().getParameters().get('SearchByName');
        List<String> paramTypeOfLoan = ApexPages.currentPage().getParameters().get('TypeOfLoan').split(',');
        system.debug(paramTypeOfLoan);
        if(paramContentType == 'PDF'){
            renderAs = 'PDF';
        }else{
            contentType = 'application/x-excel#LawyerSalesSummaryViewAll.xls';
        }
        
        this.businessUnit = paramBusinessUnit;
        this.startDate = !String.isEmpty(paramStartDate)? Date.valueOf(paramStartDate) : dt.addDays(-30);
        this.endDate = !String.isEmpty(paramEndDate)? Date.valueOf(paramEndDate) : dt;
        this.searchByName = !String.isEmpty(paramSearchByName) ? paramSearchByName : '';
        this.typeOfLoan = paramTypeOfLoan;

        this.businessUnitString = (this.businessUnit.size() == GetPickListValueSize()) ? 'Consolidated' : string.join(this.businessUnit, ',');
    }
    
    public List<Drawdown__c> getAllDrawdowns(){
        List<Drawdown__c> drawdowns = new List<Drawdown__c>();
        
        string filterByBusinessUnit = '';
        string Rhino = 'Rhino';
        string Elfi = 'ELFI';
        
        // Business Unit Filter
        String strQuery = '';            
        
        String payment = 'Payment';
        String loanPayout = 'Loan Payout';
        String partialPayment = 'Partial Payment';
        String paymentShortfall = 'Payment Shortfall';
        String paymentSurplus = 'Payment Surplus';
        string eTransfer = 'e-Transfer';
        string Cheque = 'Cheque';
        string AdminFee = 'Admin Fee';
        String ClosedWithLoan = 'Closed With Loan';
        String closedPaid = 'Closed - Paid';
        String closedShortfall = 'Closed - Shortfall';
        String closedSurplus = 'Closed - Surplus';
        String badDebt = 'Bad Debt';
        String clientRebate = 'Client Rebate';
        
        Set<Id> lawyerIdsSet = new Set<Id>();
        
        strQuery = 'Select Id, Name, Date__c, Payment_Method__c, Reference_Notes__c, '; 
        strQuery += ' Opportunity__r.Type_of_Loan__c, Opportunity__r.Lawyer__c, Opportunity__r.Lawyer__r.Name,'; 
        strQuery += ' Opportunity__r.Law_firm__r.name, Opportunity__r.Law_firm__c, Opportunity__r.Account.Business_Unit__c,';
        strQuery += ' Opportunity__r.Account.Name, Opportunity__r.Account.AccountNumber, Opportunity__c, ';
        strQuery += ' Amount__c, Interest_Repaid__c';
        strQuery += ' FROM Drawdown__c WHERE Date__c >= :startDate'; 
        strQuery += ' AND Date__c <= :endDate'; 
        strQuery += ' AND Opportunity__r.StageName =:ClosedWithLoan AND ((Payment_Method__c =:eTransfer)';
        strQuery += ' OR (Payment_Method__c =:Cheque)';
        strQuery += ' OR (Payment_Method__c =:AdminFee))';
        strQuery += (typeOfLoan.isEmpty())? '' : ' AND Opportunity__r.Type_of_Loan__c IN :typeOfLoan';
        strQuery += ' AND Is_Rejected__c = false';
        strQuery += (businessUnit.isEmpty()) ? '' : ' AND Opportunity__r.Account.Business_Unit__c IN :businessUnit';
        strQuery += ' AND Opportunity__r.Lawyer__c != \'\'';
        strQuery += !String.isEmpty(searchByName) && searchByName != null ? ' AND (Opportunity__r.Law_firm__r.name LIKE \'%' + searchByName + '%\''  : '';
        strQuery += !String.isEmpty(searchByName) && searchByName != null ? ' OR Opportunity__r.Lawyer__r.Name_Formula__c LIKE \'%' + searchByName + '%\')'  : '';
        
        
        List<Drawdown__c> activeDrawdowns = Database.query(strQuery);
        
        for(Drawdown__c dd : activeDrawdowns){
            lawyerIdsSet.add(dd.Opportunity__r.Lawyer__c);
        }
        
        drawdowns.addAll(activeDrawdowns);
        
        /**
         * PAYOUT
         * */
        
        String closedOppQuery = 'Select Id, Name, Date__c, Payment_Method__c, Reference_Notes__c, '; 
        closedOppQuery += ' Opportunity__r.Type_of_Loan__c, Opportunity__r.Lawyer__c, Opportunity__r.Lawyer__r.Name,'; 
        closedOppQuery += ' Opportunity__r.Law_firm__r.name, Opportunity__r.Law_firm__c, Opportunity__r.Account.Business_Unit__c,';
        closedOppQuery += ' Opportunity__r.Account.Name, Opportunity__r.Account.AccountNumber, Opportunity__c, ';
        closedOppQuery += ' Amount__c, Interest_Repaid__c';        
        closedOppQuery += ' FROM Drawdown__c WHERE Opportunity__r.Opportunity_Closed_Date__c >= :startDate';
        closedOppQuery += ' AND Opportunity__r.Opportunity_Closed_Date__c <= :endDate';
        closedOppQuery += (typeOfLoan.isEmpty())? '' : ' AND Opportunity__r.Type_of_Loan__c IN :typeOfLoan';
        closedOppQuery += ' AND Opportunity__r.StageName =:ClosedWithLoan';
        closedOppQuery += ' AND Payment_Method__c =:payment';  
        closedOppQuery += ' AND (Reference_Notes__c =:loanPayout OR Reference_Notes__c =:partialPayment OR Reference_Notes__c =:clientRebate)'; 
        closedOppQuery += ' AND Opportunity__r.Stage_Status__c =:closedPaid';
        closedOppQuery += ' AND Opportunity__r.Lawyer__c in :lawyerIdsSet';
        closedOppQuery += ' AND Is_Rejected__c = false';
        closedOppQuery += (businessUnit.isEmpty()) ? '' : ' AND Opportunity__r.Account.Business_Unit__c IN :businessUnit';
        
        List<Drawdown__c> payouts = DataBase.query(closedOppQuery);        
        drawdowns.addAll(payouts);
        
        /**
         * Bad Debt
         * */
        
        String badDebtOppQuery = 'Select Id, Name, Date__c, Payment_Method__c, Reference_Notes__c, '; 
        badDebtOppQuery += ' Opportunity__r.Type_of_Loan__c, Opportunity__r.Lawyer__c, Opportunity__r.Lawyer__r.Name,'; 
        badDebtOppQuery += ' Opportunity__r.Law_firm__r.name, Opportunity__r.Law_firm__c, Opportunity__r.Account.Business_Unit__c,';
        badDebtOppQuery += ' Opportunity__r.Account.Name, Opportunity__r.Account.AccountNumber, Opportunity__c, ';
        badDebtOppQuery += ' Amount__c, Interest_Repaid__c';
        badDebtOppQuery += ' FROM Drawdown__c WHERE Date__c >= :startDate';
        badDebtOppQuery += ' AND Date__c <= :endDate';
        badDebtOppQuery += (typeOfLoan.isEmpty())? '' : ' AND Opportunity__r.Type_of_Loan__c IN :typeOfLoan';
        //badDebtOppQuery += ' AND Opportunity__r.StageName =:ClosedWithLoan';
        //badDebtOppQuery += ' AND Payment_Method__c =:payment';  
        badDebtOppQuery += ' AND Reference_Notes__c =:badDebt';                 
        badDebtOppQuery += ' AND Opportunity__r.Lawyer__c in :lawyerIdsSet';
        badDebtOppQuery += ' AND Is_Rejected__c = false';
        badDebtOppQuery += (businessUnit.isEmpty()) ? '' : ' AND Opportunity__r.Account.Business_Unit__c IN :businessUnit';
        
        List<Drawdown__c> badDebts = DataBase.query(badDebtOppQuery);        
        drawdowns.addAll(badDebts);
        
        /**
		* ShortFall
		* */
        String shortFallOppQuery = 'Select Id, Name, Date__c, Payment_Method__c, Reference_Notes__c, '; 
        shortFallOppQuery += ' Opportunity__r.Type_of_Loan__c, Opportunity__r.Lawyer__c, Opportunity__r.Lawyer__r.Name,'; 
        shortFallOppQuery += ' Opportunity__r.Law_firm__r.name, Opportunity__r.Law_firm__c, Opportunity__r.Account.Business_Unit__c,';
        shortFallOppQuery += ' Opportunity__r.Account.Name, Opportunity__r.Account.AccountNumber, Opportunity__c, ';
        shortFallOppQuery += ' Amount__c, Interest_Repaid__c';
        shortFallOppQuery += ' FROM Drawdown__c WHERE Opportunity__r.Opportunity_Closed_Date__c >= :startDate';
        shortFallOppQuery += ' AND Opportunity__r.Opportunity_Closed_Date__c <= :endDate';
        shortFallOppQuery += (typeOfLoan.isEmpty())? '' : ' AND Opportunity__r.Type_of_Loan__c IN :typeOfLoan';
        shortFallOppQuery += ' AND Opportunity__r.StageName =:ClosedWithLoan';
        shortFallOppQuery += ' AND Payment_Method__c =:payment';
        shortFallOppQuery += ' AND Reference_Notes__c =:paymentShortfall';                 
        shortFallOppQuery += ' AND Opportunity__r.Stage_Status__c =:closedShortfall';
        shortFallOppQuery += ' AND Opportunity__r.Lawyer__c in :lawyerIdsSet';
        shortFallOppQuery += ' AND Is_Rejected__c = false';
        shortFallOppQuery += (businessUnit.isEmpty()) ? '' : ' AND Opportunity__r.Account.Business_Unit__c IN :businessUnit';
        
        List<Drawdown__c> shortFalls = DataBase.query(shortFallOppQuery);        
        drawdowns.addAll(shortFalls);
        
        /**
		* Overage
		* */
        
        String overageOppQuery = 'Select Id, Name, Date__c, Payment_Method__c, Reference_Notes__c, '; 
        overageOppQuery += ' Opportunity__r.Type_of_Loan__c, Opportunity__r.Lawyer__c, Opportunity__r.Lawyer__r.Name,'; 
        overageOppQuery += ' Opportunity__r.Law_firm__r.name, Opportunity__r.Law_firm__c, Opportunity__r.Account.Business_Unit__c,';
        overageOppQuery += ' Opportunity__r.Account.Name, Opportunity__r.Account.AccountNumber, Opportunity__c, ';
        overageOppQuery += ' Amount__c, Interest_Repaid__c';
        overageOppQuery += ' FROM Drawdown__c WHERE Opportunity__r.Opportunity_Closed_Date__c >= :startDate';
        overageOppQuery += ' AND Opportunity__r.Opportunity_Closed_Date__c <= :endDate';
        overageOppQuery += (typeOfLoan.isEmpty())? '' : ' AND Opportunity__r.Type_of_Loan__c IN :typeOfLoan';
        overageOppQuery += ' AND Opportunity__r.StageName =:ClosedWithLoan';
        overageOppQuery += ' AND Payment_Method__c =:payment';  
        overageOppQuery += ' AND Reference_Notes__c =:paymentSurplus'; 
        overageOppQuery += ' AND Opportunity__r.Stage_Status__c =:closedSurplus';
        overageOppQuery += ' AND Opportunity__r.Lawyer__c in :lawyerIdsSet';
        overageOppQuery += ' AND Is_Rejected__c = false';
        overageOppQuery += (businessUnit.isEmpty()) ? '' : ' AND Opportunity__r.Account.Business_Unit__c IN :businessUnit';
        
        List<Drawdown__c> overages = DataBase.query(overageOppQuery);        
        drawdowns.addAll(overages);
        
        
        drawdowns.sort();
        return drawdowns;
    }
    
    public list<LawyerSalesSummaryComponentCtrl.Wrapper> getGroupbyLawyer(){
        return LawyerSalesSummaryComponentCtrl.getAmountGroupByLawyer(''+this.startDate, ''+this.endDate, 'Opportunity__r.Lawyer__r.name', 'DESC', this.businessUnit, this.searchByName, this.typeOfLoan);
    }
    public Integer GetPickListValueSize(){
        return LawyerSalesSummaryComponentCtrl.getPickListValues('Account','Business_Unit__c').size();
    }
}