src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>Mapped from the Lead</description>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Unit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Conga_Batch_Law_Firm_Summary_Send_Email__c</fullName>
        <formula>SUBSTITUTE(  Conga_Batch_Law_Firm_Summary__c , &quot;&amp;qmode=Attachments&quot;, &quot;&amp;qmode=SendEmail&quot;)  &amp;
&quot;&amp;CongaEmailTemplateId=a0o0L00000L4wrN&quot;&amp;
&quot;&amp;EmailToId=&quot;&amp; BLANKVALUE( $Setup.Conga_batch_setting__c.Test_Recipient_of_Lawyer_Summary__c ,   $Setup.Conga_batch_setting__c.Email_To_Id_Law_Firm_Summary__c)</formula>
        <label>Conga Batch Law Firm Summary Send Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Conga_Batch_Law_Firm_Summary__c</fullName>
        <formula>&quot;&amp;solmgr=1&quot; + 
&quot;&amp;id=&quot; + Id +
&quot;&amp;queryid=&quot; + IF( $Setup.Conga_batch_setting__c.Query_Selector_Law_Firm_Report__c = &quot;Active&quot;, &quot;[LawFirmActiveClients]a0p0L00000JSOke&quot;, &quot;[LawFirmAllClients]a0p0L00000JSOkj&quot;)  + &quot;?pv0=&quot; + Id +
&quot;&amp;templateid=a0x0L00000PVUBi&quot; + 
&quot;&amp;defaultpdf=1&quot; + 
&quot;&amp;attachmentparentid=&quot; + Id +
&quot;&amp;ac0=1&quot; + 
&quot;&amp;sc0=1&quot; + 
&quot;&amp;sc1=SalesforceFile&quot; + 
&quot;&amp;DS7=5&quot; + 
&quot;&amp;qmode=Attachments&quot;</formula>
        <label>Conga Batch Law Firm Summary</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Additional_Notes_Law_Firm_Report__c</fullName>
        <formula>$Setup.Conga_batch_setting__c.Email_Additional_Notes_Law_Firm_Report__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email Additional Notes Law Firm Report</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payout_Date_Law_Firm_Report__c</fullName>
        <formula>$Setup.Conga_batch_setting__c.Payout_Date_Law_Firm_Report__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payout Date Law Firm Report</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Report_Date_Law_Firm_Report__c</fullName>
        <formula>$Setup.Conga_batch_setting__c.Report_Date_Law_Firm_Report__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Report Date Law Firm Report</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Exclude_from_Payout__c.field-meta.xml
<CustomField>
    <fullName>Exclude_from_Payout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exclude from Payout</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Conga_batch_setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom conga batch setting to store Report Date, Payout Date, Email body and conga template query selector</description>
    <fields>
        <fullName>Conductor_Id_Law_Firm_Summary_Report__c</fullName>
        <label>Conductor Id Law Firm Summary Report</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Additional_Notes_Law_Firm_Report__c</fullName>
        <label>Email Additional Notes Law Firm Report</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Email_To_Id_Law_Firm_Summary__c</fullName>
        <label>Email To Id Law Firm Summary</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payout_Date_Law_Firm_Report__c</fullName>
        <label>Payout Date Law Firm Report</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Query_Selector_Law_Firm_Report__c</fullName>
        <description>Will be used to select Query Id for conga template to send law firm report summary.</description>
        <label>Query Selector Law Firm Report</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Date_Law_Firm_Report__c</fullName>
        <label>Report Date Law Firm Report</label>
        <type>Date</type>
    </fields>
    <label>Conga batch setting</label>
</CustomObject>

force-app/main/default/objects/Conga_batch_setting__c/fields/Type_of_Loan_Law_Firm__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Loan_Law_Firm__c</fullName>
    <label>Type of Loan Law Firm</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Drawdown_Total__c</fullName>
        <label>Drawdown Total</label>
        <summarizedField>Drawdown__c.Amount__c</summarizedField>
        <summaryForeignKey>Drawdown__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Law_Firm_Lawyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Law Firm Lawyer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Onboarding Opportunity</relationshipLabel>
        <relationshipName>Onboarding_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Law_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Law Firm</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Referred Cases</relationshipLabel>
        <relationshipName>Referred_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lawyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lawyer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referred Cases</relationshipLabel>
        <relationshipName>Referred_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan_Available_to_Drawdown__c</fullName>
        <formula>CASE(
TEXT(Type_of_Loan__c), 
&quot;Facility Loan&quot;, Amount - Drawdown_Total__c,
&quot;Lum-Sum&quot;, 0,
&quot;Treatment Loan&quot;, Amount - Total_Paid_Service_Provider__c,
&quot;Treatment Loan 2&quot;, Amount - Total_Paid_Service_Provider__c,
0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Loan Available to Drawdown</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Stage_Status__c</fullName>
        <label>Stage Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>1st Week</fullName>
                </value>
                <value>
                    <fullName>2nd Week</fullName>
                </value>
                <value>
                    <fullName>File for Review</fullName>
                </value>
                <value>
                    <fullName>Add&apos;l Docs Required</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>F/U with PC/Facility</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Assessor Declined</fullName>
                </value>
                <value>
                    <fullName>Legal Representative Declined</fullName>
                </value>
                <value>
                    <fullName>Non-Responsive (Legal Representative/Plaintiff)</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Contact Sheet Completed; Part I of App Sent to Lead for Signature</fullName>
                </value>
                <value>
                    <fullName>Part II of App Sent to Firm w/ Request for Supporting Docs</fullName>
                </value>
                <value>
                    <fullName>Waiting for Additional Supporting Documents</fullName>
                </value>
                <value>
                    <fullName>Waiting for Payout From Other Lender</fullName>
                </value>
                <value>
                    <fullName>File Sent to Assessors Review</fullName>
                </value>
                <value>
                    <fullName>Awaiting Final Client Signature</fullName>
                </value>
                <value>
                    <fullName>Funds Advanced/Awaiting Signed Loan Documents</fullName>
                </value>
                <value>
                    <fullName>Awaiting Final Lawyer Signature</fullName>
                </value>
                <value>
                    <fullName>File Sent for EFT</fullName>
                </value>
                <value>
                    <fullName>See Notes</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Bad Debt</fullName>
                </value>
                <value>
                    <fullName>Paid Off</fullName>
                </value>
                <value>
                    <fullName>Payments Halted</fullName>
                </value>
                <value>
                    <fullName>Partial Payment</fullName>
                </value>
                <value>
                    <fullName>Shortfall</fullName>
                </value>
                <value>
                    <fullName>Surplus</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Loan__c</fullName>
        <label>Type of Loan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Facility Loan</fullName>
                </value>
                <value>
                    <fullName>Lump-Sum</fullName>
                    <default>true</default>
                    <label>Lump-Sum</label>
                </value>
                <value>
                    <fullName>Treatment Loan</fullName>
                </value>
                <value>
                    <fullName>Treatment Loan 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <formula>TEXT(Account.Business_Unit__c)</formula>
    <label>Business Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payout_Bath_Job__mdt/Payout_Bath_Job__mdt.object-meta.xml
<CustomObject>
    <label>Payout Bath Job</label>
    <pluralLabel>Payout Bath Jobs</pluralLabel>
</CustomObject>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ELFI</fullName>
    </customValue>
    <customValue>
        <fullName>Rhino</fullName>
    </customValue>
    <customValue>
        <fullName>Seahold</fullName>
    </customValue>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LawfirmSummaryCtlr.cls
/**
 * @File Name          : LawfirmSummaryCtlr.cls
 * @Description        : 
 * @Author             : fahad.khan@toptal.com
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 02/07/2020, 7:11:49 pm
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    5/7/2020   fahad.khan@toptal.com     Initial Version
**/
public with sharing class LawfirmSummaryCtlr {
    
    /******************* Method to get all picklists values for Account *********************/  
    @AuraEnabled
    public static List < String > getPickListValues(String objectType, String field)
    {
        return OpportunityViewComponentCtlr.getPickListValues(objectType, field);
    }
    
    /******************* Method to return all lawyers *********************/
    @AuraEnabled
    public static List<AccountInfo> getLawfirmAccounts(String strQuery, String LoanFilter, String businessUnitFilter, List<String> typeOfLoan) {
        try{
            system.debug('Query ' + strQuery);
            Boolean ExcludeFromPayout = false;
            LoanFilter = String.isEmpty(LoanFilter) ? 'All' : LoanFilter;
            businessUnitFilter = String.isEmpty(businessUnitFilter) ? 'ELFI' :businessUnitFilter;
            system.debug('LoanFilter ' + LoanFilter);
            
            // Initializing the Account variable
            List<AccountInfo> accountInfo = new List<AccountInfo>();
            List<Account> accounts = new List<Account>();
            
                        
            // *** Still need to handle exceptions ***
            // Executing the query to retrieve the account information
            accounts = Database.query(strQuery);        
            system.debug('Size = ' + accounts.size());
            
            Set<Id> accountIds = new Map<Id,Account>(accounts).keySet();
            for(account acc : accounts)
            {
                System.debug('## getLawfirmAccounts - RESULT: ' + acc.Id);
            }
            
            strQuery = 'Select Law_firm__c, Law_Firm_Lawyer__c, Lawyer__c, AccountId, Loan_Available_to_Drawdown__c from Opportunity where Law_firm__c in :accountIds AND StageName = \'Closed With Loan\' AND Drawdown_Total__c > 0';
            strQuery += ' AND Account.Exclude_from_Payout__c =: ExcludeFromPayout';
            strQuery += LoanFilter == 'Active'? ' AND Stage_Status__c LIKE \'%Active%\'' : '';
            strQuery += (businessUnitFilter == '' || businessUnitFilter == null)? ' AND Account.Business_Unit__c = \'ELFI\'' : ' AND Account.Business_Unit__c =: businessUnitFilter';
            strQuery += typeOfLoan.isEmpty() ? '' : ' AND Type_of_Loan__c IN :typeOfLoan';
            
            List<Opportunity> oppties = new List<Opportunity>();
            oppties = Database.query(strQuery);
            Map<Id,Set<Id>> lawfirmToClients = new Map<Id,Set<Id>>();
            
            for(Opportunity opp : oppties)
            {
                if(!lawfirmToClients.containsKey(opp.Law_firm__c))
                {
                    lawfirmToClients.put(opp.Law_firm__c, new Set<Id>());
                }
                lawfirmToClients.get(opp.Law_firm__c).add(opp.AccountId);
            }
            system.debug('====>>>>MEE');
            system.debug(lawfirmToClients);
            system.debug('====>>>>MEE');
            for(account a : accounts)
            {
                AccountInfo info = new AccountInfo();
                info.account = a;
                info.noOfFiles = lawfirmToClients.containsKey(a.Id) ? lawfirmToClients.get(a.Id).size() : 0;
                if(info.noOfFiles > 0)
                {
                    accountInfo.add(info);
                }
            }
            return accountInfo;
        }
        catch(Exception e){
            throw new AuraHandledException('Error Message' + e.getMessage());
        }
    }    
    @AuraEnabled
    public static Id send(String query, List<String> selectedIds, String payoutDate, String reportDate, String emailRecipientId, String emailBody, String LoanFilter, String businessUnitFilter, List<String> typeOfLoan){       
        try{
            APXT_BPM__Conductor__c conductor;
            APXTConga4__Conga_Merge_Query__c congaQuery;        
            String ids = '';
            
            if(String.isEmpty(query) || query == null) {
                ids = String.Join(selectedIds,',');
                query = 'SELECT Id FROM Account WHERE Id in ('+ ids +')';
            }        
            
            Conga_batch_setting__c customSettings = Conga_batch_setting__c.getInstance(UserInfo.getUserId());        
            customSettings.Payout_Date_Law_Firm_Report__c = (!String.isEmpty(payoutDate) && payoutDate != null) ? Date.valueOf(payoutDate) : customSettings.Payout_Date_Law_Firm_Report__c;
            customSettings.Report_Date_Law_Firm_Report__c = (!String.isEmpty(reportDate) && reportDate != null) ? Date.valueOf(reportDate) : customSettings.Report_Date_Law_Firm_Report__c;
            customSettings.Email_Additional_Notes_Law_Firm_Report__c = emailBody;
            customSettings.Email_To_Id_Law_Firm_Summary__c = (!String.isEmpty(emailRecipientId) && emailRecipientId != null) ? emailRecipientId : '';
            customSettings.Query_Selector_Law_Firm_Report__c = LoanFilter;
            customSettings.Business_Unit_Lawfirm_Summary__c = (!String.isEmpty(businessUnitFilter) && businessUnitFilter != null) ? businessUnitFilter : 'ELFI';
            customSettings.Type_of_Loan_Law_Firm__c = String.join(typeOfLoan, '|');
            
            if(String.isEmpty(customSettings.Conductor_Id_Law_Firm_Summary_Report__c)){
                congaQuery = new APXTConga4__Conga_Merge_Query__c(APXTConga4__Name__c = 'Law firm summary conductor query - ' + UserInfo.getName(),
                                                                  APXTConga4__Description__c = 'Query of law firm summary custom report for conga conductor.',
                                                                  APXTConga4__Query__c = query);
                insert congaQuery;
                conductor = new APXT_BPM__Conductor__c(APXT_BPM__Title__c = 'Mass Law Firm Summary - ' + UserInfo.getName(), APXT_BPM__Query_Id__c = congaQuery.Id,
                                                       APXT_BPM__URL_Field_Name__c = 'Conga_Batch_Law_Firm_Summary_Send_Email__c');
                insert conductor;            
                customSettings.Conductor_Id_Law_Firm_Summary_Report__c = conductor.Id;
            }else{
                conductor = [SELECT Id, APXT_BPM__Query_Id__c, APXT_BPM__URL_Field_Name__c FROM APXT_BPM__Conductor__c WHERE Id =:customSettings.Conductor_Id_Law_Firm_Summary_Report__c];
                congaQuery = [SELECT Id, APXTConga4__Query__c FROM APXTConga4__Conga_Merge_Query__c WHERE Id =:conductor.APXT_BPM__Query_Id__c];
                conductor.APXT_BPM__URL_Field_Name__c = 'Conga_Batch_Law_Firm_Summary_Send_Email__c';
                update conductor;
                congaQuery.APXTConga4__Query__c = query;
                update congaQuery;
            }
            upsert customSettings;
            return conductor.id;
        }
        catch(exception e){
            throw new AuraHandledException('Error Message' + e.getMessage()+e.getStackTraceString());
        }
    }
    
    @AuraEnabled
    public static Id generate(String query, List<String> selectedIds, String payoutDate, String reportDate, String LoanFilter, String businessUnitFilter, List<String> typeOfLoan){
		
        try{
            APXT_BPM__Conductor__c conductor;
            APXTConga4__Conga_Merge_Query__c congaQuery;
            String ids = '';
            
            if(String.isEmpty(query) || query == null) {
                ids = String.Join(selectedIds,',');
                query = 'SELECT Id FROM Account WHERE Id in ('+ ids +')';
            }
            Conga_batch_setting__c customSettings = Conga_batch_setting__c.getInstance(UserInfo.getUserId());        
            customSettings.Payout_Date_Law_Firm_Report__c = (!String.isEmpty(payoutDate) && payoutDate != null) ? Date.valueOf(payoutDate) : customSettings.Payout_Date_Law_Firm_Report__c;
            customSettings.Report_Date_Law_Firm_Report__c = (!String.isEmpty(reportDate) && reportDate != null) ? Date.valueOf(reportDate) : customSettings.Report_Date_Law_Firm_Report__c;
            //customSettings.Email_To_Id_Law_Firm_Summary__c = (!String.isEmpty(emailRecipientId) && emailRecipientId != null) ? emailRecipientId : '';
            customSettings.Query_Selector_Law_Firm_Report__c = LoanFilter;
            customSettings.Business_Unit_Lawfirm_Summary__c = (!String.isEmpty(businessUnitFilter) && businessUnitFilter != null) ? businessUnitFilter : 'ELFI';
            customSettings.Type_of_Loan_Law_Firm__c = String.join(typeOfLoan, '|');
            
            if(String.isEmpty(customSettings.Conductor_Id_Law_Firm_Summary_Report__c)){
                congaQuery = new APXTConga4__Conga_Merge_Query__c(APXTConga4__Name__c = 'Law firm summary conductor query - ' + UserInfo.getName(),
                                                                  APXTConga4__Description__c = 'Query of law firm summary custom report for conga conductor.',
                                                                  APXTConga4__Query__c = query);
                insert congaQuery;
                conductor = new APXT_BPM__Conductor__c(APXT_BPM__Title__c = 'Mass Law Firm Summary - ' + UserInfo.getName(), APXT_BPM__Query_Id__c = congaQuery.Id,
                                                       APXT_BPM__URL_Field_Name__c = 'Conga_Batch_Law_Firm_Summary__c');
                insert conductor;            
                customSettings.Conductor_Id_Law_Firm_Summary_Report__c = conductor.Id;
            }else{
                conductor = [SELECT Id, APXT_BPM__Query_Id__c, APXT_BPM__URL_Field_Name__c FROM APXT_BPM__Conductor__c WHERE Id =:customSettings.Conductor_Id_Law_Firm_Summary_Report__c];
                congaQuery = [SELECT Id, APXTConga4__Query__c FROM APXTConga4__Conga_Merge_Query__c WHERE Id =:conductor.APXT_BPM__Query_Id__c];
                conductor.APXT_BPM__URL_Field_Name__c = 'Conga_Batch_Law_Firm_Summary__c';
                update conductor;
                congaQuery.APXTConga4__Query__c = query;
                update congaQuery;
            }
            upsert customSettings;
            return conductor.id;
        }
        catch(exception e){
            throw new AuraHandledException('Error Message' + e.getMessage()+e.getStackTraceString());
        }
    }
    
    @AuraEnabled
    public static void generatePayoutBalance(Id lawfirmId, String payoutDate, String LoanFilter, String businessUnitFilter, List<String> typeOfLoan){
        try{
            List <Payout_Bath_Job__mdt> payoutJobs = [SELECT MasterLabel, DeveloperName FROM Payout_Bath_Job__mdt];
            Map<String, Payout_Bath_Job__mdt> devNameToPayoutJobsMap = new Map<String, Payout_Bath_Job__mdt>();
            for(Payout_Bath_Job__mdt pJob : payoutJobs){
                devNameToPayoutJobsMap.put(pJob.DeveloperName, pJob);
            }
            
            
            List<AsyncApexJob> currentJobs = [SELECT Id ,Status, ApexClass.Name, CreatedBy.Name, CreatedDate
                                              FROM AsyncApexJob
                                              WHERE Status!='Aborted'
                                              AND ApexClass.Name IN :devNameToPayoutJobsMap.keySet()
                                              AND Status!='Completed'
                                              ORDER BY CreatedDate DESC];
            if(!currentJobs.isEmpty()){
                String m = 'Cannot execute this job because ' + currentJobs[0].CreatedBy.Name + ' ran a similar job at ' + currentJobs[0].CreatedDate + '.';
                m += '\nPlease try again later.';
                
                AuraHandledException e = new AuraHandledException(m);
                e.setMessage(m);
                throw e;
            }
            LoanFilter = String.isEmpty(LoanFilter) ? 'All' : LoanFilter;
            businessUnitFilter = String.isEmpty(businessUnitFilter) ? 'ELFI' :businessUnitFilter;
            Date pDate = Date.valueOf(payoutDate);
            
            LawfirmSummaryGeneratePayoutBalance lfSummaryJob = new LawfirmSummaryGeneratePayoutBalance(new Set<Id>{lawfirmId}, pDate, loanFilter, businessUnitFilter, typeOfLoan);
            Database.executeBatch(lfSummaryJob, 50);
            
        }catch(exception e){
            system.debug('Error Message' + e.getMessage()+e.getStackTraceString());
            throw new AuraHandledException('' + e.getMessage());
        }
    }
    
    @AuraEnabled
    public static AsyncApexJob getBatchJobStatus(){
        List<AsyncApexJob> aaj = null;
        try{
            aaj = [SELECT Id, ApexClassId, Status, NumberOfErrors, TotalJobItems, JobItemsProcessed, createdBy.Name, createdDate, CompletedDate FROM AsyncApexJob
                   WHERE ApexClass.Name = 'LawfirmSummaryGeneratePayoutBalance' AND Status != 'Aborted' order by CreatedDate DESC LIMIT 1];
        }catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }        
        return (aaj.size() > 0 )? aaj[0] : null;
    }
    
    @AuraEnabled 
    public static void abortBatchJobs(){
        for(AsyncApexJob aJob : [SELECT id FROM AsyncApexJob WHERE Status!='Aborted' AND Status!='Completed'
                                 AND ApexClass.Name = 'LawfirmSummaryGeneratePayoutBalance'] ){                                     
                                     System.AbortJob(aJob.Id);                                     
                                 }
    }
    
    public class AccountInfo{
        @AuraEnabled
        public Account account{get;set;}
        
        @AuraEnabled
        public Integer noOfFiles{get;set;} 
        
        @AuraEnabled
        public Boolean checked{get;set;} 
    }

}