src/objects/Drawdown__c.object
<CustomObject>
    <fields>
        <fullName>Admin_Fee__c</fullName>
        <label>Admin Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EFT__c</fullName>
        <label>EFT #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interest_Deferral_Period__c</fullName>
        <description>The Interest Deferral Period from the Opportunity, replicated here to avoid cross object formula size limitations.  Also converted to an number from a picklist value so it&apos;s readily usable in formulas.</description>
        <inlineHelpText>The months to defer interest on this Drawdown.</inlineHelpText>
        <label>Interest Deferral Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <description>The interest rate pulled down from the Opportunity.  Duplicated here to allow formulas to access without exceeding limits.</description>
        <inlineHelpText>Loan Interest Rate</inlineHelpText>
        <label>Interest Rate</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Minimum_Interest_Period__c</fullName>
        <description>The minimum Interest period from the Opportunity.   Replicated here to avoid exceeding cross object formula limitations.</description>
        <inlineHelpText>The number of months of interest which must be charged at a minimum.</inlineHelpText>
        <label>Minimum Interest Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Drawdowns</relationshipLabel>
        <relationshipName>Drawdowns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Admin_Fee__c</fullName>
        <label>Admin Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Interest_Compounding_Period__c</fullName>
        <label>Interest Compounding Period</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Simple Interest</fullName>
                </value>
                <value>
                    <fullName>Compounding Interest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interest_Deferral_Period__c</fullName>
        <label>Interest Deferral Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>48</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <label>Annual Interest Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Minimum_Interest_Period__c</fullName>
        <label>Minimum Interest Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0 months</fullName>
                </value>
                <value>
                    <fullName>1 month</fullName>
                </value>
                <value>
                    <fullName>2 months</fullName>
                </value>
                <value>
                    <fullName>3 months</fullName>
                </value>
                <value>
                    <fullName>4 months</fullName>
                </value>
                <value>
                    <fullName>5 months</fullName>
                </value>
                <value>
                    <fullName>6 months</fullName>
                    <default>true</default>
                    <label>6 months</label>
                </value>
                <value>
                    <fullName>7 months</fullName>
                </value>
                <value>
                    <fullName>8 months</fullName>
                </value>
                <value>
                    <fullName>9 months</fullName>
                </value>
                <value>
                    <fullName>10 months</fullName>
                </value>
                <value>
                    <fullName>11 months</fullName>
                </value>
                <value>
                    <fullName>12 months</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage_Status__c</fullName>
        <label>Stage Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>1st Week</fullName>
                </value>
                <value>
                    <fullName>2nd Week</fullName>
                </value>
                <value>
                    <fullName>File for Review</fullName>
                </value>
                <value>
                    <fullName>Add&apos;l Docs Required</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>F/U with PC/Facility</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Assessor Declined</fullName>
                </value>
                <value>
                    <fullName>Legal Representative Declined</fullName>
                </value>
                <value>
                    <fullName>Non-Responsive (Legal Representative/Plaintiff)</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Contact Sheet Completed; Part I of App Sent to Lead for Signature</fullName>
                </value>
                <value>
                    <fullName>Part II of App Sent to Firm w/ Request for Supporting Docs</fullName>
                </value>
                <value>
                    <fullName>Waiting for Additional Supporting Documents</fullName>
                </value>
                <value>
                    <fullName>Waiting for Payout From Other Lender</fullName>
                </value>
                <value>
                    <fullName>File Sent to Assessors Review</fullName>
                </value>
                <value>
                    <fullName>Awaiting Final Client Signature</fullName>
                </value>
                <value>
                    <fullName>Funds Advanced/Awaiting Signed Loan Documents</fullName>
                </value>
                <value>
                    <fullName>Awaiting Final Lawyer Signature</fullName>
                </value>
                <value>
                    <fullName>File Sent for EFT</fullName>
                </value>
                <value>
                    <fullName>See Notes</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Bad Debt</fullName>
                </value>
                <value>
                    <fullName>Paid Off</fullName>
                </value>
                <value>
                    <fullName>Payments Halted</fullName>
                </value>
                <value>
                    <fullName>Partial Payment</fullName>
                </value>
                <value>
                    <fullName>Shortfall</fullName>
                </value>
                <value>
                    <fullName>Surplus</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduled_Payment__c/Scheduled_Payment__c.object-meta.xml
<CustomObject>
    <label>Scheduled Payment</label>
    <nameField>
        <displayFormat>PS-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduled_Payment__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Bank account that we send the funds to</description>
    <label>Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Bank_Account__c.Client__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Drawdown__c.field-meta.xml
<CustomField>
    <fullName>Drawdown__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drawdown</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Drawdown__c.Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Opportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Drawdown__c</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/EFT_Number__c.field-meta.xml
<CustomField>
    <fullName>EFT_Number__c</fullName>
    <label>EFT Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/First_Sent_to_Bank_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Sent_to_Bank_Date__c</fullName>
    <label>First Sent to Bank Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lump-Sum</fullName>
            </value>
            <value>
                <fullName>Ad-Hoc</fullName>
            </value>
            <value>
                <fullName>Scheduled Facility</fullName>
            </value>
            <value>
                <fullName>Treatment</fullName>
            </value>
            <value>
                <fullName>Payment to Other Lender</fullName>
            </value>
            <value>
                <fullName>Loan Payout</fullName>
                <isActive>false</isActive>
                <label>Loan Payout</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Sent_to_Bank_Date__c.field-meta.xml
<CustomField>
    <fullName>Sent_to_Bank_Date__c</fullName>
    <description>Date and Time this payment was included in a banking sheet</description>
    <label>Sent to Bank Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Pre Send Validation</fullName>
            </value>
            <value>
                <fullName>Approved to Send</fullName>
            </value>
            <value>
                <fullName>Sent to Bank</fullName>
            </value>
            <value>
                <fullName>Processed by Bank</fullName>
            </value>
            <value>
                <fullName>Drawdown Created</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Won&apos;t Send</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ScheduledPaymentHelperTest.cls
/**
 * @File Name          : ScheduledPaymentHelperTest.cls
 * @Description        : 
 * @Author             : Seth Boyd
 * @Group              : 
 * @Last Modified By   : Seth Boyd
 * @Last Modified On   : 5/1/2019, 3:19:14 PM
 * @Modification Log   : 
 *==============================================================================
 * Ver         Date                     Author      		      Modification
 *==============================================================================
 * 1.0    4/25/2019, 10:39:39 AM   Seth Boyd     Initial Version
**/
@isTest(seeAllData=false)
public class ScheduledPaymentHelperTest {

    @isTest
    static void test_one_sp() {
        // Test with no account set on SP
        Bank_Account__c bankRec = TestDataFactory.getBankAccountObjects(1)[0];

        FObject opp = new FObject('Opportunity', 1);
        opp.setDefinition('Amount', 'static value(5000)');
        opp.setDefinition('Admin_Fee__c', 'static value(475)');
        opp.setDefinition('StageName', 'static value(Loan Approved)');
        opp.setDefinition('Stage_Status__c', 'static value(File Sent for EFT)');
        opp.setDefinition('AccountId', 'random lookup(Account) source(forceea)');
        opp.setDefinition('Minimum_Interest_Period__c', 'random type(picklist)');
        opp.setDefinition('Interest_Deferral_Period__c', 'random type(picklist)');
        opp.setDefinition('Interest_Rate__c', 'static value(0.245)');
        opp.setDefinition('Interest_Compounding_Period__c', 'static value(Simple Interest)');
        opp.insertRecords(true);
        Opportunity oppRec = ((List<Opportunity>)opp.getRecords())[0];

        FObject sp = new Fobject('Scheduled_Payment__c', 1);
        sp.setDefinition('Amount__c', 'static value(1000)');
        sp.setDefinition('Status__c', 'static value(Sent to Bank)');
        sp.setDefinition('Payment_Type__c', 'static value(Lump-Sum)');
        //sp.setDefinition('Sent_to_Bank_Date__c', 'random type(datetime) from(2010-1-1) to(2015-12-31 15:13:00)');
        sp.setDefinition('EFT_Number__c', 'static value(123)');
        sp.insertRecords(true);
        Scheduled_Payment__c spRec = ((List<Scheduled_Payment__c>)sp.getRecords())[0];

        String eftNum = '123';
        test.startTest();
        Id[] spIds = new Id[]{spRec.Id};
        ScheduledPaymentHelper.generateDrawdowns(spIds);
        test.stopTest();

        spRec = [
            Select
                Id,
                Amount__c,
                Opportunity__c,
                First_Sent_to_Bank_Date__c
            From Scheduled_Payment__c
            Where Id = :spRec.Id
        ];

        Drawdown__c[] dd = [
            Select
                Id,
                Scheduled_Payment__c,
                Amount__c,
                Opportunity__c,
                EFT__c,
                Payment_Method__c,
                Reference_Notes__c,
                Date__c
            FROM Drawdown__c
            Where Scheduled_Payment__c = :spRec.Id
        ];
        // ensure drawdown was created correctly
        system.assert(!dd.isEmpty(), 'Drawdown should have been created');
        system.assertEquals(spRec.Id, dd[0].Scheduled_Payment__c, 'Drawdown should be associated with Scheduled Payment');
        system.assertEquals(spRec.Amount__c, dd[0].Amount__c, 'Drawdown Amount should be set');
        system.assertEquals(spRec.Opportunity__c, dd[0].Opportunity__c, 'Drawdown Opporunity should be set');
        system.assertEquals(eftNum, dd[0].EFT__c, 'Drawdown EFT # should be set');
        system.assertEquals('e-Transfer', dd[0].Payment_Method__c, 'Drawdown payment method should be set');
        system.assertEquals('Payment to Client', dd[0].Reference_Notes__c, 'Drawdown Reference Notes should be set');
        system.assertEquals(spRec.First_Sent_to_Bank_Date__c.date(), dd[0].Date__c, 'Drawdown date should be set');

        // ensure admin fee drawdown was created
        Drawdown__c[] adminDD = [
            Select
                Id,
                Amount__c,
                Opportunity__c,
                Payment_Method__c,
                Reference_Notes__c,
                Date__c
            From Drawdown__c
            Where
                Payment_Method__c = 'Admin Fee'];
        System.debug(adminDD);
        system.assert(!adminDD.isEmpty(), 'Admin Fee drawdown should have been created');
        system.assertEquals(oppRec.Admin_Fee__c, adminDD[0].Amount__c, 'Amount should have been set');
        system.assertEquals(oppRec.Id, adminDD[0].Opportunity__c, 'Opporunity should have been set');
        system.assertEquals('Admin Fee', adminDD[0].Reference_Notes__c, 'Reference notes should have been set');
        system.assertEquals(Date.today(), adminDD[0].Date__c, 'Date should have been set');

        //oppRec = [Select Id, Funding_Details_Status__c from Opportunity Where Id = :oppRec.Id][0];
        //System.assertEquals('Loan Setup Check', oppRec.Funding_Details_Status__c, 'Opportunity Funding Details Status should have been set');
    }

    @isTest
    static void test_multiple_sp_per_opp() {
        // Test with multiple scheduled payments per opp
        Bank_Account__c bankRec = TestDataFactory.getBankAccountObjects(1)[0];

        FObject opp = new FObject('Opportunity', 1);
        opp.setDefinition('Amount', 'static value(5000)');
        opp.setDefinition('Admin_Fee__c', 'static value(475)');
        opp.setDefinition('StageName', 'static value(Loan Approved)');
        opp.setDefinition('Stage_Status__c', 'static value(File Sent for EFT)');
        opp.setDefinition('AccountId', 'random lookup(Account) source(forceea)');
        opp.setDefinition('Minimum_Interest_Period__c', 'random type(picklist)');
        opp.setDefinition('Interest_Deferral_Period__c', 'random type(picklist)');
        opp.setDefinition('Interest_Rate__c', 'static value(0.245)');
        opp.setDefinition('Interest_Compounding_Period__c', 'static value(Simple Interest)');
        opp.insertRecords(true);
        Opportunity oppRec = ((List<Opportunity>)opp.getRecords())[0];

        FObject sp = new Fobject('Scheduled_Payment__c', 2);
        sp.setDefinition('Amount__c', 'static value(1000)');
        sp.setDefinition('Status__c', 'static value(Sent to Bank)');
        sp.setDefinition('Payment_Type__c', 'static value(Ad-Hoc)');
        //sp.setDefinition('Sent_to_Bank_Date__c', 'random type(datetime) from(2010-1-1) to(2015-12-31 15:13:00)');
        sp.setDefinition('Send_Cheque__c', 'static value(true)');
        sp.setDefinition('Cheque_Number__c', 'static value(123)');
        sp.insertRecords(true);
        Scheduled_Payment__c[] spRecs = ((List<Scheduled_Payment__c>)sp.getRecords());

        String chqNum = '123';
        test.startTest();
        ScheduledPaymentHelper.invocableGenerateDrawdowns(new Id[]{oppRec.Id});
        test.stopTest();

        // Test first sp
        Id[] spIds = new Id[]{spRecs[0].Id, spRecs[1].Id};

        spRecs = [
            Select
                Id,
                Amount__c,
                Opportunity__c,
                First_Sent_to_Bank_Date__c
            From Scheduled_Payment__c
            Where Id in :spIds
            Order By First_Sent_to_Bank_Date__c ASC
        ];

        Scheduled_Payment__c spRec = spRecs[0];

        Drawdown__c[] dd = [
            Select
                Id,
                Scheduled_Payment__c,
                Amount__c,
                Opportunity__c,
                CHQ__c,
                Payment_Method__c,
                Reference_Notes__c,
                Date__c
            FROM Drawdown__c
            Where Scheduled_Payment__c = :spRec.Id
        ];

        // ensure drawdown was created correctly
        system.assert(!dd.isEmpty(), 'Drawdown should have been created');
        system.assertEquals(spRec.Id, dd[0].Scheduled_Payment__c, 'Drawdown should be associated with Scheduled Payment');
        system.assertEquals(spRec.Amount__c, dd[0].Amount__c, 'Drawdown Amount should be set');
        system.assertEquals(spRec.Opportunity__c, dd[0].Opportunity__c, 'Drawdown Opporunity should be set');
        system.assertEquals(chqNum, dd[0].CHQ__c, 'Drawdown CHQ # should be set');
        system.assertEquals('Cheque', dd[0].Payment_Method__c, 'Drawdown payment method should be set');
        system.assertEquals('Payment to Client', dd[0].Reference_Notes__c, 'Drawdown Reference Notes should be set');
        system.assertEquals(spRec.First_Sent_to_Bank_Date__c.date(), dd[0].Date__c, 'Drawdown date should be set');

        spRec = spRecs[1];
        dd = [
            Select
                Id,
                Scheduled_Payment__c,
                Amount__c,
                Opportunity__c,
                CHQ__c,
                Payment_Method__c,
                Reference_Notes__c,
                Date__c
            FROM Drawdown__c
            Where Scheduled_Payment__c = :spRec.Id
        ];
        // ensure drawdown was created correctly
        system.assert(!dd.isEmpty(), 'Drawdown should have been created');
        system.assertEquals(spRec.Id, dd[0].Scheduled_Payment__c, 'Drawdown should be associated with Scheduled Payment');
        system.assertEquals(spRec.Amount__c, dd[0].Amount__c, 'Drawdown Amount should be set');
        system.assertEquals(spRec.Opportunity__c, dd[0].Opportunity__c, 'Drawdown Opporunity should be set');
        system.assertEquals(chqNum, dd[0].CHQ__c, 'Drawdown CHQ # should be set');
        system.assertEquals('Cheque', dd[0].Payment_Method__c, 'Drawdown payment method should be set');
        system.assertEquals('Payment to Client', dd[0].Reference_Notes__c, 'Drawdown Reference Notes should be set');
        system.assertEquals(spRec.First_Sent_to_Bank_Date__c.date(), dd[0].Date__c, 'Drawdown date should be set');

        // ensure admin fee drawdown was created
        Drawdown__c[] adminDD = [
            Select
                Id,
                Amount__c,
                Opportunity__c,
                Payment_Method__c,
                Reference_Notes__c,
                Date__c
            From Drawdown__c
            Where
                Payment_Method__c = 'Admin Fee'];
        System.debug(adminDD);
        system.assert(!adminDD.isEmpty(), 'Admin Fee drawdown should have been created');
        system.assertEquals(1, adminDD.size(), 'Only one admin fee Drawdown should have been created');
        system.assertEquals(oppRec.Admin_Fee__c, adminDD[0].Amount__c, 'Amount should have been set');
        system.assertEquals(oppRec.Id, adminDD[0].Opportunity__c, 'Opporunity should have been set');
        system.assertEquals('Admin Fee', adminDD[0].Reference_Notes__c, 'Reference notes should have been set');
        system.assertEquals(Date.today(), adminDD[0].Date__c, 'Date should have been set');

        //oppRec = [Select Id, Funding_Details_Status__c from Opportunity Where Id = :oppRec.Id][0];
        //System.assertEquals('Loan Setup Check', oppRec.Funding_Details_Status__c, 'Opportunity Funding Details Status should have been set');
    }
}