src/objects/Drawdown__c.object
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Is_NSF_Rejection__c.field-meta.xml
<CustomField>
    <fullName>Is_NSF_Rejection__c</fullName>
    <formula>AND(NOT(ISBLANK(TEXT(Reason_to_Reverse_Payment_NSF__c))), Rejections_Count__c &gt; 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is NSF Rejection</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Reason_to_Reverse_Payment_NSF__c.field-meta.xml
<CustomField>
    <fullName>Reason_to_Reverse_Payment_NSF__c</fullName>
    <label>Reason for reversing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NSF Cheque</fullName>
            </value>
            <value>
                <fullName>Client Error</fullName>
            </value>
            <value>
                <fullName>ELFI Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Batch_ClearNSF.cls
global class Batch_ClearNSF implements Database.Batchable<sObject>{
	global Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator('select Reason_to_Reverse_Payment_NSF__c, Rejections_Count__c, Is_NSF_Rejection__c from Drawdown__c where Reason_to_Reverse_Payment_NSF__c=\'NSF Cheque\' and  Is_NSF_Rejection__c=false');
   }

   global void execute(Database.BatchableContext BC, List<sObject> scope){
       List<Drawdown__c> drs = (List<Drawdown__c>) scope;
       doJob(drs);
   }
   
   global static void doJob(List<Drawdown__c> drs){
       for (Drawdown__c d : drs){
           d.Reason_to_Reverse_Payment_NSF__c = null;
       }
       
       update drs;
   }

   global void finish(Database.BatchableContext BC){
   }
}