src/objects/Drawdown__c.object
<CustomObject>
    <fields>
        <fullName>Accrued_Interest_as_of_Payout_Date__c</fullName>
        <formula>IF (OR( ISPICKVAL(Reference_Notes__c,&quot;Referral Fee&quot;),
		ISPICKVAL(Reference_Notes__c,&quot;Payment Rejected&quot;),
		ISPICKVAL(Reference_Notes__c,&quot;Payment Re-processed&quot;)),0,
IF(  ISPICKVAL(Payment_Method__c , &quot;Payment&quot;),0,(Outstanding_Balance_as_of_Payout_Date__c-Amount_Adjusted_for_Repayments__c)+Interest_up_to_Last_Repayment__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Interest Accrued up to Payout Date</inlineHelpText>
        <label>Accrued Interest</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interest_End_Date__c</fullName>
        <formula>IF(Payout_Date__c&gt;ADDMONTHS(Date__c,Minimum_Interest_Period__c),Payout_Date__c,ADDMONTHS(Date__c,Minimum_Interest_Period__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Date Interest will be calculated TO.   Date is adjusted for minimum interest period.</inlineHelpText>
        <label>Interest End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Drawdowns</relationshipLabel>
        <relationshipName>Drawdowns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Outstanding_Balance_as_of_Payout_Date__c</fullName>
        <description>NOTE: Used EXP and LN as the normal exponent function does not handle fractional numbers:  See: https://developer.salesforce.com/forums/?id=906F00000008vDHIAY</description>
        <formula>IF (OR( ISPICKVAL(Reference_Notes__c,&quot;Referral Fee&quot;),
		ISPICKVAL(Reference_Notes__c,&quot;Payment Rejected&quot;),
		ISPICKVAL(Reference_Notes__c,&quot;Payment Re-processed&quot;)),0,
IF(  ISPICKVAL(Payment_Method__c , &quot;Payment&quot;),Sum_of_Payment_Allocations__c - Amount__c,
IF(Compounding_Interest__c,(Amount_Adjusted_for_Repayments__c*(EXP(LN(1 + (Interest_Rate__c/Compounding_Frequency__c))*   
(Compounding_Frequency__c*Interest_Accrual_Years__c)))),Amount_Adjusted_for_Repayments__c*(1+((Interest_Rate__c/365)* Interest_Accrual_Days__c)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Outstanding Balance as it will be at the Payout Date.  This Accounts for compounding interest or Simple Interest depending on the Loan.  This is set to zero when Drawdown is Payment.   For Payments, negative amounts represent unallocated payment amounts.</inlineHelpText>
        <label>Outstanding Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Admin Fee</fullName>
                </value>
                <value>
                    <fullName>Cheque</fullName>
                </value>
                <value>
                    <fullName>e-Transfer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payout_Date__c</fullName>
        <description>The Payout Date pulled down from the Opportunity to work around calculated field length limitations.  Do not update directly here, update on Opportunity instead and let it replicate down.</description>
        <inlineHelpText>Expected or Actual Payout Date of the Drawdown.  Do not update directly here, update on Opportunity instead and let it replicate down to here.</inlineHelpText>
        <label>Payout Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Temp_Payout_Date__c</fullName>
        <inlineHelpText>Used to calculate outstanding balance and date as of a scratch date.  This field should not be updated directly on the Drawdown, instead update from Opportunity and let it replicate down.  Used for Payment Allocation and Reporting From/To amount calc.</inlineHelpText>
        <label>Temp Payout Date</label>
        <type>Date</type>
    </fields>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Drawdown_Payment_Allocation__c.object
<CustomObject>
    <description>All Payment allocations to Drawdowns.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>Amount of Transaction (negative for payments)</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Drawdown__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Drawdown that this applies to</inlineHelpText>
        <label>Drawdown</label>
        <referenceTo>Drawdown__c</referenceTo>
        <relationshipLabel>Payments Allocated to this Drawdown</relationshipLabel>
        <relationshipName>Payments_Allocated_to_this_Drawdown</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interest_Accrued_to_Transaction_Date__c</fullName>
        <inlineHelpText>Interest Accrued to the date of the Payment</inlineHelpText>
        <label>Interest Accrued to Transaction Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Interest_End_Date__c</fullName>
        <inlineHelpText>The date interest was accrued to when this Payment Allocation was created.</inlineHelpText>
        <label>Interest End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Opportunity the parent Drawdown is linked to.   This is required to allow efficient replication down from Opportunity.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Drawdown Payment Allocations</relationshipLabel>
        <relationshipName>Drawdown_Payment_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <inlineHelpText>Payment associated with this Drawdown</inlineHelpText>
        <label>Payment</label>
        <referenceTo>Drawdown__c</referenceTo>
        <relationshipLabel>Drawdowns Allocated to this Payment</relationshipLabel>
        <relationshipName>Drawdowns_Allocated_to_this_Payment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payout_Date__c</fullName>
        <inlineHelpText>The Payout Date replicated down from the Opportunity.  It&apos;s required hear for the DLRS to trigger aggregation.</inlineHelpText>
        <label>Payout Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Temp_Payout_Date__c</fullName>
        <inlineHelpText>The Temp Payout Date replicated down from the Opportunity.  It&apos;s required here to allow the DLRS to aggregate up to Drawdown.</inlineHelpText>
        <label>Temp Payout Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <inlineHelpText>Date of Transaction</inlineHelpText>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <label>Drawdown Payment Allocation</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdown Payment Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Drawdown_Total_wo_Payment__c</fullName>
        <label>Drawdown Total w/o Payment</label>
        <summarizedField>Drawdown__c.Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Drawdown__c.Payment_Method__c</field>
            <operation>notEqual</operation>
            <value>Payment</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Drawdown__c.Reference_Notes__c</field>
            <operation>notEqual</operation>
            <value>Payment Rejected, Payment Re-processed, Referral Fee</value>
        </summaryFilterItems>
        <summaryForeignKey>Drawdown__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Payout_Date__c</fullName>
        <label>Payout Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Principal_Repaid__c.field-meta.xml
<CustomField>
    <fullName>Principal_Repaid__c</fullName>
    <label>Principal Repaid</label>
    <summarizedField>Drawdown__c.Principal_Repaid__c</summarizedField>
    <summaryFilterItems>
        <field>Drawdown__c.Payment_Method__c</field>
        <operation>equals</operation>
        <value>Payment</value>
    </summaryFilterItems>
    <summaryForeignKey>Drawdown__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/QueueablePaymentAllocator.cls
public with sharing class QueueablePaymentAllocator implements queueable {
   
    private Set<Id> paymentIds;

    public QueueablePaymentAllocator(Set<Id> paymentIds) {
        this.paymentIds = paymentIds;
    }

    public class PayoutDateInconsistentException extends Exception {}

    public void execute(System.QueueableContext QC){
        
        // Get the Payments
        list<Drawdown__c> payments = [select name, CreatedDate, Outstanding_Balance_as_of_Payout_Date__c,Date__c,Id,Opportunity__c,Opportunity__r.Payout_Date__c 
                                      from Drawdown__c where Id IN :this.paymentIds ORDER BY CreatedDate];

        // Get all Opportunities
        Set<ID> opportunityIds = new Set<ID>();
        for (Drawdown__c p:payments){
            opportunityIds.add(p.Opportunity__c);
        }

        // Get all drawdowns which are not payments but are under the same Opportunity - calling them customer "advances"
        list<Drawdown__c> advances = [select Name,date__c,Outstanding_Balance_as_of_Payout_Date__c,Id, Opportunity__c, Payout_Date__c, Temp_Payout_Date__c, 
                                      Interest_End_Date__c, Accrued_Interest_as_of_Payout_Date__c,Amount__c, Interest_repaid__c, Principal_repaid__c,
                                      Opportunity__r.Interest_Accrued_as_of_Payout_Date__c, Opportunity__r.Drawdown_Total_wo_Payment__c, 
                                      Opportunity__r.Sum_of_Principal_Repayments__c
                                      from Drawdown__c
                                      where Opportunity__c in :opportunityIds AND Outstanding_Balance_as_of_Payout_Date__c > 0 and Payment_Method__c <> 'Payment' order by Opportunity__c,Date__c ASC];


        list<Drawdown_Payment_Allocation__c> allocations = new list<Drawdown_Payment_Allocation__c> ();  // list of allocations to be inserted

        // saving the balance of each advance so I can decrement as I allocate it
        map<id,Decimal> advanceBalance = new map<id,Decimal>();  
        for (drawdown__c a : advances){
            advanceBalance.put(a.id,a.Outstanding_Balance_as_of_Payout_Date__c);
        }

        // go through each payment and allocate it - there is unlikely to be more than 1 but trying to bulkify ...
        Decimal SumPrincipalRepaymentsAux = 0;
        for (Drawdown__c p:payments){            
            Decimal paymentBalance = 0.00 - p.Outstanding_Balance_as_of_Payout_Date__c;  //change sign            
                 
            for (drawdown__c a : advances){
                
                if (a.Payout_Date__c <> p.date__c && a.opportunity__c == p.opportunity__c){
                    throw new PayoutDateInconsistentException('Drawdown ' + a.name + ', with a Payout Date of:' + a.Payout_Date__c + ' is not consistent with Payment date on ' + p.name+ ' of '+ p.date__c +'. Payments cannot be allocated.');
                }
                
                if (a.opportunity__c == p.opportunity__c && paymentBalance > 0 && advanceBalance.get(a.id)> 0  ){
                    
                    Decimal AllocationAmount = 0.00;                    
                    if (advanceBalance.get(a.id)>= paymentBalance){
                        AllocationAmount += paymentBalance;
                        advanceBalance.put(a.id,advanceBalance.get(a.id)-paymentBalance);
                        paymentBalance = 0;
                        
                    } else {
                        AllocationAmount += advanceBalance.get(a.id);
                        paymentBalance -= advanceBalance.get(a.id);
                        advanceBalance.put(a.id,0);
                        
                    }
                    Drawdown_Payment_Allocation__c newAllocation = 
                        new Drawdown_Payment_Allocation__c (Amount__c=AllocationAmount, drawdown__c=a.id,payment__c=p.id, 
                                                            payout_date__c=a.payout_date__c, temp_payout_date__c=a.temp_payout_date__c, 
                                                            Transaction_Date__c=p.date__c, opportunity__c=p.opportunity__c,
                                                            Interest_Accrued_to_Transaction_Date__c = a.Accrued_Interest_as_of_Payout_Date__c,
                                                            Interest_End_Date__c = a.Interest_End_Date__c);
                    
                    if(SumPrincipalRepaymentsAux == 0 && a.Opportunity__r.Sum_of_Principal_Repayments__c != null){
                        SumPrincipalRepaymentsAux = a.Opportunity__r.Sum_of_Principal_Repayments__c;
                    } else if (SumPrincipalRepaymentsAux == 0 && a.Opportunity__r.Sum_of_Principal_Repayments__c == null){
                        SumPrincipalRepaymentsAux = 0;
                    }
                    
                    
                    // calculate principal repaid                    
                    If (SumPrincipalRepaymentsAux >= a.Opportunity__r.Drawdown_Total_wo_Payment__c){
                        //set to zero as principal is already fully paid
                        newAllocation.Principal_repaid__c = 0.00;
                    } else{
                        If((AllocationAmount + SumPrincipalRepaymentsAux)<= a.Opportunity__r.Drawdown_Total_wo_Payment__c){
                            //set to full repayment as principal outstanding is less than repayment
                            newAllocation.Principal_repaid__c = AllocationAmount;
                            SumPrincipalRepaymentsAux = SumPrincipalRepaymentsAux + newAllocation.Principal_repaid__c;
                        } else {
                            //set to the difference between the principal outstanding and the amount paid so far
                            newAllocation.Principal_repaid__c = a.Opportunity__r.Drawdown_Total_wo_Payment__c - SumPrincipalRepaymentsAux;
                            SumPrincipalRepaymentsAux = SumPrincipalRepaymentsAux + newAllocation.Principal_repaid__c;
                        }
                    }
                    
                    system.debug(' newAllocation.Principal_repaid__c >> ' + newAllocation.Principal_repaid__c);
                    
                    // calculate interest repaid                    
                    If (newAllocation.Principal_repaid__c >= AllocationAmount){
                        // all of the repayment went to principal to set interest repaid to zero
                        newAllocation.Interest_repaid__c = 0.00;
                    } else {
                        // Interest repaid is set to the leftover amount after the principal is repaid
                        newAllocation.Interest_repaid__c = AllocationAmount - newAllocation.Principal_repaid__c;
                    }
                    
                    system.debug(' newAllocation.Interest_repaid__c >> ' + newAllocation.Interest_repaid__c );
                    
                    //insert newAllocation;
                    allocations.add(newAllocation);                 
                }
            }
        }
        insert allocations;
    }
}