src/objects/Drawdown__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Drawdowns</relationshipLabel>
        <relationshipName>Drawdowns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/BOM_Fee_Advance__c.field-meta.xml
<CustomField>
    <fullName>BOM_Fee_Advance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BOM Fee Advance</label>
    <referenceTo>Drawdown__c</referenceTo>
    <relationshipLabel>Drawdowns (BOM Fee Advance)</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Batch_ReNumberDrawdown.cls
public class Batch_ReNumberDrawdown implements Database.Batchable<sObject> {
    
    public Set<Id> oppIds;
    
    public Batch_ReNumberDrawdown(){
        oppIds = new Set<Id>();
    }
    public Batch_ReNumberDrawdown(Set<Id> Ids){
        oppIds = Ids;
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        String strQuery = 'SELECT Id, (SELECT Id, Drawdown_Number__c FROM Drawdowns__r Order by Date__c asc) FROM Opportunity';
        strQuery += !oppIds.isEmpty()? ' WHERE Id in :oppIds' : '';
        return DataBase.getQueryLocator(strQuery);
    }
    
    public void execute(Database.BatchableContext BC, List<Opportunity> Opportunities){
        List<Drawdown__c> drawdownsToUpdate = new List<Drawdown__c>();
        
        for(Opportunity opp :Opportunities){
            Integer num = 1;
            for(Drawdown__c dd : opp.Drawdowns__r){
                if(dd.Drawdown_Number__c != num){
                    dd.Drawdown_Number__c = num;
                    drawdownsToUpdate.add(dd);
                }
                num++;
            }
        }
        
        if(!drawdownsToUpdate.isEmpty()) update drawdownsToUpdate;
    }
    
    public void finish(Database.BatchableContext BC){

    }
}