src/objects/Drawdown__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Drawdowns</relationshipLabel>
        <relationshipName>Drawdowns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/BOM_Fees_Generated__c.field-meta.xml
<CustomField>
    <fullName>BOM_Fees_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BOM Fees Generated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Has_Interest__c.field-meta.xml
<CustomField>
    <fullName>Has_Interest__c</fullName>
    <formula>NOT(OR( ISPICKVAL(Reference_Notes__c,&quot;Referral Fee&quot;),
ISPICKVAL(Reference_Notes__c,&quot;Refund&quot;),
ISPICKVAL(Reference_Notes__c,&quot;Payment Re-processed&quot;),
ISPICKVAL(Payment_Method__c, &apos;Payment&apos;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Has Interest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Variable_Fees_Generated__c.field-meta.xml
<CustomField>
    <fullName>Variable_Fees_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Variable Fees Generated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CreateVariableFeesQueueable.cls
public class CreateVariableFeesQueueable implements Queueable{
    List<Id> oppIds;
    public CreateVariableFeesQueueable (List<Id> oppIds){
        this.oppIds = oppIds;
    }
    
   	public void execute(QueueableContext context) {        
        if (!oppIds.isEmpty()){                        
            try{
                Id oppId = oppIds[0];
                VariableFeeHelper.createFeesForOpp(oppIds[0]);
                VariableFeeHelper.createBOMFeesForOpp(oppId);
                List<Drawdown__c> drawdowns = [select Id, Variable_Fees_Generated__c, BOM_Fees_Generated__c from Drawdown__c where Opportunity__c=:oppId and Has_Interest__c=true];
                for (Drawdown__c d : drawdowns){
                    d.Variable_Fees_Generated__c = true;
                    d.BOM_Fees_Generated__c = true;
                }
                update drawdowns;
                oppIds.remove(0);
                System.enqueueJob(new CreateVariableFeesQueueable(oppIds));
            }
            catch(Exception ex){
                onFinish();
            }
        }       
        else
            onFinish();
    }
    
    private void onFinish(){
    }
}