src/objects/Drawdown__c.object
<CustomObject>
    <fields>
        <fullName>Accrued_Interest_In_Reporting_Period__c</fullName>
        <formula>Accrued_Interest_as_of_To_Date__c -  Accrued_Interest_as_of_From_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Accrued Interest In Reporting Period</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Accrued_Interest_as_of_From_Date__c</fullName>
        <inlineHelpText>Accrued interest on the From Date</inlineHelpText>
        <label>Accrued Interest as of From Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Accrued_Interest_as_of_Temp_Date__c</fullName>
        <formula>IF (OR( ISPICKVAL(Reference_Notes__c,&quot;Referral Fee&quot;),
		ISPICKVAL(Reference_Notes__c,&quot;Payment Rejected&quot;),
		ISPICKVAL(Reference_Notes__c,&quot;Payment Re-processed&quot;)),0,
IF( ISPICKVAL(Payment_Method__c , &quot;Payment&quot;),0,(Outstanding_Balance_as_of_Temp_Date__c-Amount_Adjusted_for_Payments_b4_Temp_Dt__c)+Interest_up_to_Last_Repayment_b4_Temp_Dt__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Interest Accrued up to Temp Payout Date</inlineHelpText>
        <label>Accrued Interest as of Temp Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Accrued_Interest_as_of_To_Date__c</fullName>
        <label>Accrued Interest as of To Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Balance_Change_In_Reporting_Period__c</fullName>
        <formula>Outstanding_Balance_as_of_To_Date__c -  Outstanding_Balance_as_of_From_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Balance Change In Reporting Period</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <description>The interest rate pulled down from the Opportunity.  Duplicated here to allow formulas to access without exceeding limits.</description>
        <inlineHelpText>Loan Interest Rate</inlineHelpText>
        <label>Interest Rate</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Drawdowns</relationshipLabel>
        <relationshipName>Drawdowns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Outstanding_Balance_as_of_From_Date__c</fullName>
        <inlineHelpText>Outstanding balance on the From date</inlineHelpText>
        <label>Outstanding Balance as of From Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Outstanding_Balance_as_of_Temp_Date__c</fullName>
        <description>NOTE: Used EXP and LN as the normal exponent function does not handle fractional numbers: See: https://developer.salesforce.com/forums/?id=906F00000008vDHIAY</description>
        <formula>IF (OR( ISPICKVAL(Reference_Notes__c,&quot;Referral Fee&quot;),
		ISPICKVAL(Reference_Notes__c,&quot;Payment Rejected&quot;),
		ISPICKVAL(Reference_Notes__c,&quot;Payment Re-processed&quot;)),0,
IF( ISPICKVAL(Payment_Method__c , &quot;Payment&quot;),Sum_of_Payment_Allocations__c - Amount__c, 
IF(Compounding_Interest__c,(Amount_Adjusted_for_Payments_b4_Temp_Dt__c*(EXP(LN(1 + (Interest_Rate__c/Compounding_Frequency__c))* 
(Compounding_Frequency__c*Interest_Accrual_Years_Pymt_to_Temp_Dt__c)))),Amount_Adjusted_for_Payments_b4_Temp_Dt__c*(1+((Interest_Rate__c/365)* Interest_Accrual_Days_Pymt_to_Temp_Dt__c)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Outstanding Balance as it will be at the Temp Payout Date. This Accounts for compounding interest or Simple Interest depending on the Loan. This is set to zero when Drawdown is Payment.  For Payments this contains the unallocated payment amount.</inlineHelpText>
        <label>Outstanding Balance as of Temp Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Outstanding_Balance_as_of_To_Date__c</fullName>
        <inlineHelpText>Balance on To Date</inlineHelpText>
        <label>Outstanding Balance as of To Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Admin Fee</fullName>
                </value>
                <value>
                    <fullName>Cheque</fullName>
                </value>
                <value>
                    <fullName>e-Transfer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reporting_From_Date__c</fullName>
        <inlineHelpText>Start date of reporting information</inlineHelpText>
        <label>Reporting From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reporting_To_Date__c</fullName>
        <inlineHelpText>End date of reporting information</inlineHelpText>
        <label>Reporting To Date</label>
        <type>Date</type>
    </fields>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <label>Annual Interest Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Outstanding_Balance_as_of_To_Date__c</fullName>
        <inlineHelpText>Outstanding Balance on the Reporting To date.  Used for ELFI 1 report.  Note that this field is just labeled &quot;Outstanding Balance&quot; on the report (label changed via report type).</inlineHelpText>
        <label>Outstanding Balance as of To Date</label>
        <summarizedField>Drawdown__c.Outstanding_Balance_as_of_To_Date__c</summarizedField>
        <summaryFilterItems>
            <field>Drawdown__c.Payment_Method__c</field>
            <operation>notEqual</operation>
            <value>Payment</value>
        </summaryFilterItems>
        <summaryForeignKey>Drawdown__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Reporting_From_Date__c</fullName>
        <inlineHelpText>The minimum Reporting From Date on all of the Drawdowns which are eligible for inclusion in the Portfolio reports.</inlineHelpText>
        <label>Reporting From Date</label>
        <summarizedField>Drawdown__c.Reporting_From_Date__c</summarizedField>
        <summaryFilterItems>
            <field>Drawdown__c.Payment_Method__c</field>
            <operation>notEqual</operation>
            <value>Payment</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Drawdown__c.Include_in_Portfolio_Reports__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Drawdown__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Reporting_To_Date__c</fullName>
        <inlineHelpText>The maximum Reporting TO Date on all of the Drawdowns which are eligible for inclusion in the Portfolio reports.</inlineHelpText>
        <label>Reporting To Date</label>
        <summarizedField>Drawdown__c.Reporting_To_Date__c</summarizedField>
        <summaryFilterItems>
            <field>Drawdown__c.Payment_Method__c</field>
            <operation>notEqual</operation>
            <value>Payment</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Drawdown__c.Include_in_Portfolio_Reports__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Drawdown__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Stage_Status__c</fullName>
        <label>Stage Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>1st Week</fullName>
                </value>
                <value>
                    <fullName>2nd Week</fullName>
                </value>
                <value>
                    <fullName>File for Review</fullName>
                </value>
                <value>
                    <fullName>Add&apos;l Docs Required</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>F/U with PC/Facility</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Assessor Declined</fullName>
                </value>
                <value>
                    <fullName>Legal Representative Declined</fullName>
                </value>
                <value>
                    <fullName>Non-Responsive (Legal Representative/Plaintiff)</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Contact Sheet Completed; Part I of App Sent to Lead for Signature</fullName>
                </value>
                <value>
                    <fullName>Part II of App Sent to Firm w/ Request for Supporting Docs</fullName>
                </value>
                <value>
                    <fullName>Waiting for Additional Supporting Documents</fullName>
                </value>
                <value>
                    <fullName>Waiting for Payout From Other Lender</fullName>
                </value>
                <value>
                    <fullName>File Sent to Assessors Review</fullName>
                </value>
                <value>
                    <fullName>Awaiting Final Client Signature</fullName>
                </value>
                <value>
                    <fullName>Funds Advanced/Awaiting Signed Loan Documents</fullName>
                </value>
                <value>
                    <fullName>Awaiting Final Lawyer Signature</fullName>
                </value>
                <value>
                    <fullName>File Sent for EFT</fullName>
                </value>
                <value>
                    <fullName>See Notes</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Bad Debt</fullName>
                </value>
                <value>
                    <fullName>Paid Off</fullName>
                </value>
                <value>
                    <fullName>Payments Halted</fullName>
                </value>
                <value>
                    <fullName>Partial Payment</fullName>
                </value>
                <value>
                    <fullName>Shortfall</fullName>
                </value>
                <value>
                    <fullName>Surplus</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Loan__c</fullName>
        <label>Type of Loan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Facility Loan</fullName>
                </value>
                <value>
                    <fullName>Lump-Sum</fullName>
                    <default>true</default>
                    <label>Lump-Sum</label>
                </value>
                <value>
                    <fullName>Treatment Loan</fullName>
                </value>
                <value>
                    <fullName>Treatment Loan 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/FinancialReportCalculateData.cls
global class FinancialReportCalculateData implements Database.Batchable<sObject> {
    
    String query;
	public Date fromDate;  // date we are calcuating from
	public Date toDate;    // date we are calculating to
    public Date adhocAsOfDate;    
	public Boolean sinceInception;  // use this to indicate calculation since the drawdown date
    public String typeOfLoan;  // opportunity type of loan
    public Set<Id> oppIds;
    
    global FinancialReportCalculateData(Date fromDt, Date toDt, Boolean inception, String loanType, Date adhocDate){
        
        system.debug('loanType ' + loanType);
        oppIds = new Set<Id>();
        fromDate = (fromDt != null) ? fromDt.addDays(-1) : null;
		toDate = (toDt != null) ? toDt : null;    
		sinceInception = (inception == null) ? false : inception;
        typeOfLoan = !String.isEmpty(loanType) && loanType != null? loanType : '';
        //typeOfLoan = 'Testing';
        
        adhocAsOfDate = (adhocDate != null) ? adhocDate : null;
        
        String strQuery = 'SELECT Id, Opportunity__c FROM Drawdown__c WHERE Date__c >= :fromDate';
        strQuery += ' AND Date__c <= :toDate AND Opportunity__r.StageName = \'Closed With Loan\'';
        strQuery += (String.isEmpty(typeOfLoan) || typeOfLoan == null || typeOfLoan == 'Consolidated')? '' : ' AND Opportunity__r.Type_of_Loan__c =:typeOfLoan';
        strQuery += ' AND (Opportunity__r.Stage_Status__c =\'Active\' OR Opportunity__r.Stage_Status__c =\'Active - Collections\' OR Opportunity__r.Stage_Status__c = \'Active - Partial Payment\'';
        strQuery += ' OR Opportunity__r.Stage_Status__c =\'Closed - Paid\' OR Opportunity__r.Stage_Status__c = \'Closed - Shortfall\'';
        strQuery += ' OR Opportunity__r.Stage_Status__c =\'Closed - Surplus\' OR Opportunity__r.Stage_Status__c =\'Closed - Bad Debt\')';
        strQuery += ' AND (Payment_Method__c =\'Cheque\' or Payment_Method__c = \'e-Transfer\')';
        
        
        List<Drawdown__c> drawdowns = Database.query(strQuery);
        
        system.debug('drawdowns ' + drawdowns.size());
        
        for(Drawdown__c dd : drawdowns){
            oppIds.add(dd.Opportunity__c);
        }
        
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        String closedWithLoan = 'Closed With Loan';
        String none = '';
        String partialPayment = 'Active - Partial Payment';
        String active = 'Active';
        String activeCollections = 'Active - Collections';
        String closedSurplus = 'Closed - Surplus';
        String closedShortfall = 'Closed - Shortfall';
        String closedPaid = 'Closed - Paid';
        String closedBadDebt = 'Closed - Bad Debt';
                
        query='SELECT id,date__c,Reporting_From_Date__c,Outstanding_Balance_as_of_From_Date__c,Accrued_Interest_as_of_From_Date__c,' +
            'Reporting_To_Date__c,Outstanding_Balance_as_of_To_Date__c,Accrued_Interest_as_of_To_Date__c,'+
            'Balance_Change_In_Reporting_Period__c,Accrued_Interest_In_Reporting_Period__c,Outstanding_Balance_as_of_Temp_Date__c, '+
            'Accrued_Interest_as_of_Temp_Date__c from drawdown__c where Opportunity__r.StageName =:closedWithLoan';
        query += !oppIds.isEmpty()? ' AND Opportunity__c in :oppIds' : ''; 
        query += (String.isEmpty(typeOfLoan) || typeOfLoan == null || typeOfLoan == 'Consolidated')? '' : ' AND Opportunity__r.Type_of_Loan__c =:typeOfLoan';
        query += ' AND (Opportunity__r.Stage_Status__c =:none OR Opportunity__r.Stage_Status__c =:active OR Opportunity__r.Stage_Status__c =:activeCollections OR Opportunity__r.Stage_Status__c =:partialPayment';
        query += ' OR Opportunity__r.Stage_Status__c =:closedPaid OR Opportunity__r.Stage_Status__c =:closedShortfall';
        query += ' OR Opportunity__r.Stage_Status__c =:closedSurplus OR Opportunity__r.Stage_Status__c =:closedBadDebt)';
        query += ' AND Interest_Rate__c > 0 AND Payment_Method__c != \'Payment\' ';
        
        /**
         * Updated the the above query. Added some more filters.
         * Date range filter is added.
         * Opportunity Type of loan filter is added
         * Added Opportunity stage status = Active
         * Modified Opportunity stage status filter from 'Partial Payment' to 'Active - Partial Payment'
         * 
         * Modified Date = March, 20, 2020.
         * */
        
        system.debug(query);
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        try{
			PortfolioReportCalculateData.calculateDataInStatic(scope, sinceInception,  adhocAsOfDate != null? adhocAsOfDate :fromDate, toDate);
		}
		catch (Exception e){
			
		}
    }
    global void finish(Database.BatchableContext BC){
        
    }
}