src/objects/Drawdown__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Drawdowns</relationshipLabel>
        <relationshipName>Drawdowns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Admin Fee</fullName>
                </value>
                <value>
                    <fullName>Cheque</fullName>
                </value>
                <value>
                    <fullName>e-Transfer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reference_Notes__c</fullName>
        <label>Reference Notes</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Payment_Method__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Admin Fee</fullName>
                </value>
                <value>
                    <fullName>Admin Fee charged up front</fullName>
                </value>
                <value>
                    <fullName>Bad Debt</fullName>
                </value>
                <value>
                    <fullName>EFT Reject</fullName>
                </value>
                <value>
                    <fullName>EFT Reprocessed</fullName>
                </value>
                <value>
                    <fullName>EFT to Client</fullName>
                </value>
                <value>
                    <fullName>Fee</fullName>
                </value>
                <value>
                    <fullName>Loan Payout</fullName>
                </value>
                <value>
                    <fullName>Other Fee</fullName>
                </value>
                <value>
                    <fullName>Partial Payment</fullName>
                </value>
                <value>
                    <fullName>Payment Rejected</fullName>
                </value>
                <value>
                    <fullName>Payment Re-processed</fullName>
                </value>
                <value>
                    <fullName>Payment Shortfall</fullName>
                </value>
                <value>
                    <fullName>Payment Surplus</fullName>
                </value>
                <value>
                    <fullName>Payment to Client</fullName>
                </value>
                <value>
                    <fullName>Payment to Lawyer</fullName>
                </value>
                <value>
                    <fullName>Payment to other lender</fullName>
                </value>
                <value>
                    <fullName>Payment to Third-Party</fullName>
                </value>
                <value>
                    <fullName>Payment to Treatment - Service Provider</fullName>
                </value>
                <value>
                    <fullName>Referral Fee</fullName>
                </value>
                <value>
                    <fullName>Waived Fee</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Variable_Fee_Effected_At__c.field-meta.xml
<CustomField>
    <fullName>Variable_Fee_Effected_At__c</fullName>
    <label>Variable Fee Effected At</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Loan Setup</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>BOM</fullName>
            </value>
            <value>
                <fullName>One Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Date_of_advance__c</fullName>
        <label>Date of advance</label>
        <summarizedField>Drawdown__c.Date__c</summarizedField>
        <summaryForeignKey>Drawdown__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type__c</fullName>
    <label>Fee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>No Fee</fullName>
            </value>
            <value>
                <fullName>Waived Fee</fullName>
            </value>
            <value>
                <fullName>Variable Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Variable_Fee__c/Variable_Fee__c.object-meta.xml
<CustomObject>
    <label>Variable Fee</label>
    <nameField>
        <label>Variable Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variable Fees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Variable_Fee__c/fields/Effective_At__c.field-meta.xml
<CustomField>
    <fullName>Effective_At__c</fullName>
    <label>Effective At</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Loan Setup</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>One Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Variable_Fee__c/fields/Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type__c</fullName>
    <label>Fee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>%</fullName>
            </value>
            <value>
                <fullName>$</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Variable_Fee__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Variable_Fee__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Variable Fees</relationshipLabel>
    <relationshipName>Variable_Fees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VariableFeeScheduler.cls
global class VariableFeeScheduler implements Schedulable{
	global void execute(SchedulableContext sc)    
    {
        createFees(Date.today());
    }
    public static void createFees(Date dt){        
        Map<Id, List<Drawdown__c>> oppIdToDrawdowns = getExistingDrawdowns(dt);        
        List<Variable_Fee__c> variableFeesToProcess = getVariableFeesToProcess(dt);
        List<Drawdown__c> drawdownsToInsert = new List<Drawdown__c>();
        for (Variable_Fee__c vf : variableFeesToProcess){ 
            if (!drawdownExists(vf, oppIdToDrawdowns)){                
                Decimal amount = vf.Fee_Type__c=='%' ? vf.Opportunity__r.Amount * vf.Rate__c / 100.0 : vf.Rate__c;
                Drawdown__c d = new Drawdown__c(Date__c=dt, Amount__c=amount, Payment_Method__c='Admin Fee', Opportunity__c = vf.Opportunity__c,
                                                Reference_Notes__c='Admin Fee', Variable_Fee_Effected_At__c=vf.Effective_At__c);
                drawdownsToInsert.add(d);
            }
        }
        if (!drawdownsToInsert.isEmpty())
            insert drawdownsToInsert;
    }
    public static Map<Id, List<Drawdown__c>> getExistingDrawdowns(Date dt){
        List<Drawdown__c> existingDrawdowns = [select Id, Opportunity__c, Variable_Fee_Effected_At__c from Drawdown__c where Variable_Fee_Effected_At__c != null and Payment_Method__c='Admin Fee' and Date__c=:dt order by Opportunity__c];
        Map<Id, List<Drawdown__c>> oppIdToDrawdowns = new Map<Id, List<Drawdown__c>>();
        for (Drawdown__c d : existingDrawdowns){
            if (oppIdToDrawdowns.containsKey(d.Opportunity__c))
                oppIdToDrawdowns.get(d.Opportunity__c).add(d);
            else
                oppIdToDrawdowns.put(d.Opportunity__c, new List<Drawdown__c>{d});
        }
        return oppIdToDrawdowns;
    }
    public static List<Variable_Fee__c> getVariableFeesToProcess(Date dt){
        List<Variable_Fee__c> variableFees = [select Fee_Type__c, Month__c, Effective_At__c, Rate__c, Opportunity__c, 
                                              Opportunity__r.Date_of_advance__c, Opportunity__r.Amount from Variable_Fee__c 
                                              where Opportunity__r.Amount != null and Opportunity__r.Date_of_advance__c != null order by Order__c];
        List<Variable_Fee__c> variableFeesToProcess = new List<Variable_Fee__c>();        
        for (Variable_Fee__c variableFee : variableFees){
            if (variableFee.Opportunity__r.Date_of_advance__c != null){
                if (variableFee.Effective_At__c == 'Loan Setup' && variableFee.Opportunity__r.Date_of_advance__c == dt){
                    variableFeesToProcess.add(variableFee);
                }
                if (variableFee.Effective_At__c == 'Annual' && variableFee.Opportunity__r.Date_of_advance__c.year() < dt.year()
                   && variableFee.Opportunity__r.Date_of_advance__c.month() == dt.month() && variableFee.Opportunity__r.Date_of_advance__c.day() == dt.day()){
                       variableFeesToProcess.add(variableFee);
                }
                if (variableFee.Effective_At__c == 'BOM' && variableFee.Month__c != null){
                    Date nextDate = variableFee.Opportunity__r.Date_of_advance__c.addMonths((Integer)variableFee.Month__c);
                    System.debug('Next date ' + nextDate);
                    if (nextDate == dt){
                        variableFeesToProcess.add(variableFee);
                    }
                }
                if (variableFee.Effective_At__c == 'One Time' && variableFee.Month__c != null){
                    Date nextDate = variableFee.Opportunity__r.Date_of_advance__c.addMonths((Integer)variableFee.Month__c);
                    if (nextDate == dt){
                        variableFeesToProcess.add(variableFee);
                    }
                }
            }
        }
        return variableFeesToProcess;
    }
    public static Boolean drawdownExists(Variable_Fee__c vf, Map<Id, List<Drawdown__c>> oppIdToDrawdowns){
        if (!oppIdToDrawdowns.containsKey(vf.Opportunity__c))
            return false;        
        for (Drawdown__c d : oppIdToDrawdowns.get(vf.Opportunity__c)){
            if (vf.Effective_At__c == d.Variable_Fee_Effected_At__c)
                return true;
        }
        return false;
    }
}