src/objects/Drawdown__c.object
<CustomObject>
    <fields>
        <fullName>Admin_Fee__c</fullName>
        <label>Admin Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Compounding_Interest__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The opportunity__r.compounding_Interest__c field has been replicated here to avoid exceeding cross object formula lmits.   Field was transformed to a checkbox to simplify usage in formulas as well.</description>
        <inlineHelpText>Indicates if loan interest is compounding or simple.</inlineHelpText>
        <label>Compounding Interest</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <description>The interest rate pulled down from the Opportunity.  Duplicated here to allow formulas to access without exceeding limits.</description>
        <inlineHelpText>Loan Interest Rate</inlineHelpText>
        <label>Interest Rate</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Minimum_Interest_Period__c</fullName>
        <description>The minimum Interest period from the Opportunity.   Replicated here to avoid exceeding cross object formula limitations.</description>
        <inlineHelpText>The number of months of interest which must be charged at a minimum.</inlineHelpText>
        <label>Minimum Interest Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payout_Date__c</fullName>
        <description>The Payout Date pulled down from the Opportunity to work around calculated field length limitations.  Do not update directly here, update on Opportunity instead and let it replicate down.</description>
        <inlineHelpText>Expected or Actual Payout Date of the Drawdown.  Do not update directly here, update on Opportunity instead and let it replicate down to here.</inlineHelpText>
        <label>Payout Date</label>
        <type>Date</type>
    </fields>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Drawdown_Amount__c.field-meta.xml
<CustomField>
    <fullName>Drawdown_Amount__c</fullName>
    <formula>IF(OR(ISPICKVAL(Payment_Method__c,&apos;e-Transfer&apos;),ISPICKVAL(Payment_Method__c,&apos;Cheque&apos;)), Total_Amount__c,IF(ISPICKVAL(Payment_Method__c,&apos;Admin Fee&apos;),0,(0-Principal_Repaid__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Drawdown Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Admin_Fee__c</fullName>
        <label>Admin Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Compounding_Interest__c</fullName>
        <label>Interest Compounding Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Interest_Compounding_Period__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-Annual</fullName>
                </value>
                <value>
                    <fullName>Annual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Drawdown_Amount__c</fullName>
        <label>Drawdown Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Interest_Compounding_Period__c</fullName>
        <label>Interest Compounding Period</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Simple Interest</fullName>
                </value>
                <value>
                    <fullName>Compounding Interest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <label>Annual Interest Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Minimum_Interest_Period__c</fullName>
        <label>Minimum Interest Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0 months</fullName>
                </value>
                <value>
                    <fullName>1 month</fullName>
                </value>
                <value>
                    <fullName>2 months</fullName>
                </value>
                <value>
                    <fullName>3 months</fullName>
                </value>
                <value>
                    <fullName>4 months</fullName>
                </value>
                <value>
                    <fullName>5 months</fullName>
                </value>
                <value>
                    <fullName>6 months</fullName>
                    <default>true</default>
                    <label>6 months</label>
                </value>
                <value>
                    <fullName>7 months</fullName>
                </value>
                <value>
                    <fullName>8 months</fullName>
                </value>
                <value>
                    <fullName>9 months</fullName>
                </value>
                <value>
                    <fullName>10 months</fullName>
                </value>
                <value>
                    <fullName>11 months</fullName>
                </value>
                <value>
                    <fullName>12 months</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Schedule__c</fullName>
        <label>Payment Schedule</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payout_Date__c</fullName>
        <label>Payout Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Stage_Status__c</fullName>
        <label>Stage Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>1st Week</fullName>
                </value>
                <value>
                    <fullName>2nd Week</fullName>
                </value>
                <value>
                    <fullName>File for Review</fullName>
                </value>
                <value>
                    <fullName>Add&apos;l Docs Required</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>F/U with PC/Facility</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Assessor Declined</fullName>
                </value>
                <value>
                    <fullName>Legal Representative Declined</fullName>
                </value>
                <value>
                    <fullName>Non-Responsive (Legal Representative/Plaintiff)</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Contact Sheet Completed; Part I of App Sent to Lead for Signature</fullName>
                </value>
                <value>
                    <fullName>Part II of App Sent to Firm w/ Request for Supporting Docs</fullName>
                </value>
                <value>
                    <fullName>Waiting for Additional Supporting Documents</fullName>
                </value>
                <value>
                    <fullName>Waiting for Payout From Other Lender</fullName>
                </value>
                <value>
                    <fullName>File Sent to Assessors Review</fullName>
                </value>
                <value>
                    <fullName>Awaiting Final Client Signature</fullName>
                </value>
                <value>
                    <fullName>Funds Advanced/Awaiting Signed Loan Documents</fullName>
                </value>
                <value>
                    <fullName>Awaiting Final Lawyer Signature</fullName>
                </value>
                <value>
                    <fullName>File Sent for EFT</fullName>
                </value>
                <value>
                    <fullName>See Notes</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Bad Debt</fullName>
                </value>
                <value>
                    <fullName>Paid Off</fullName>
                </value>
                <value>
                    <fullName>Payments Halted</fullName>
                </value>
                <value>
                    <fullName>Partial Payment</fullName>
                </value>
                <value>
                    <fullName>Shortfall</fullName>
                </value>
                <value>
                    <fullName>Surplus</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type_of_Loan__c</fullName>
        <label>Type of Loan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Facility Loan</fullName>
                </value>
                <value>
                    <fullName>Lump-Sum</fullName>
                    <default>true</default>
                    <label>Lump-Sum</label>
                </value>
                <value>
                    <fullName>Treatment Loan</fullName>
                </value>
                <value>
                    <fullName>Treatment Loan 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Payment_Schedule_Send_First_Immediately__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule_Send_First_Immediately__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Send First Payment Immediately</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/Scheduled_Payment__c.object-meta.xml
<CustomObject>
    <label>Scheduled Payment</label>
    <nameField>
        <displayFormat>PS-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduled_Payment__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Bank account that we send the funds to</description>
    <label>Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Bank_Account__c.Client__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Pre Send Validation</fullName>
            </value>
            <value>
                <fullName>Approved to Send</fullName>
            </value>
            <value>
                <fullName>Sent to Bank</fullName>
            </value>
            <value>
                <fullName>Processed by Bank</fullName>
            </value>
            <value>
                <fullName>Drawdown Created</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Won&apos;t Send</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FacilityLoanSchedulingTest.cls
@isTest(seeAllData=false)
public class FacilityLoanSchedulingTest {

    @isTest
    static void test_full_process_amount() {
        // Test with no account set on SP
        DateUtil.today = Date.newInstance(2019, 1, 1);
        DateUtil.now = Datetime.newInstance(2019, 1, 1);

        Bank_Account__c bankRec = TestDataFactory.getBankAccountObjects(TestDataFactory.getBankAccountConfig(1), false)[0];
        bankRec.Mark_as_Primary__c = true;
        insert bankRec;

        Opportunity opp = TestDataFactory.getOpportunityObjects(1)[0];
        opp.StageName = 'Closed With Loan';
        opp.Stage_Status__c = 'Approved';
        opp.Amount = 5475.00;
        opp.Admin_Fee__c = 475.00;
        opp.Payout_Date__c = DateUtil.today();
        opp.Type_of_Loan__c = 'Facility Loan';
        opp.Minimum_Interest_Period__c = '0 months';
        opp.Compounding_Interest__c = 'Monthly';
        opp.Interest_Compounding_Period__c = 'Compounding Interest';
        opp.Interest_Rate__c = 24.5;

        opp.Payment_Schedule__c = 'Yes';
        opp.Payment_Schedule_Mode__c = Constants.PAYMENT_MODE_AMOUNT;
        opp.Payment_Use_Primary_Bank_Account__c = true;
        opp.Payment_Default_Bank_Account__c = bankRec.Id;
        opp.Start_Date__c = DateUtil.today();
        opp.Day_of_Month__c = 'Last';
        opp.Payment_Schedule_Allotted_Amount__c = 5000.00;
        opp.Drawdown_Amount__c = 1000.00;
        opp.Payment_Schedule_Send_First_Immediately__c = false;
        opp.CloseDate = DateUtil.today();
        update opp;

        Scheduled_Payment__c[] spList = [
            Select
                Id, Status__c, Scheduled_Date__c, Amount__c, Current_Opportunity_Schedule_Version__c
            From Scheduled_Payment__c
            Where Opportunity__c = :opp.Id
            Order By Scheduled_Date__c ASC
        ];

        System.assertEquals(5, spList.size(), 'Should be 5 payments');
        Date dt = Dateutil.today();
        System.debug(System.LoggingLevel.ERROR, spList);
        for (Scheduled_Payment__c sp : spList) {
            System.debug(System.LoggingLevel.ERROR, sp);
            System.assertEquals(opp.Drawdown_Amount__c, sp.Amount__c, 'Should be same amount');
            System.assertEquals(dt.month(), sp.Scheduled_Date__c.month(), 'Date should increment through months: ' + sp.Scheduled_Date__c.format());
            System.assert(sp.Current_Opportunity_Schedule_Version__c, 'Should be current schedule');
            dt = dt.addMonths(1);
        }

        Scheduled_Payment__c sp1 = spList[0];
        sp1.Status__c = 'Approved to Send';
        sp1.Banking_Verified__c = true;
        sp1.BIA_PPSA_LL_Verified__c = true;
        sp1.Credit_Verified__c = true;
        sp1.Documents_Verified__c = true;
        sp1.EFT_Number__c = '123';
        update sp1;

        test.startTest();
        ScheduledPaymentHelper.generateDrawdowns(new Id[]{sp1.Id});

        spList = [
            Select
                Id, Status__c, Scheduled_Date__c, Amount__c, Current_Opportunity_Schedule_Version__c, EFT_Number__c,
                Drawdown__r.Amount__c,
                Drawdown__r.Opportunity__c,
                Drawdown__r.EFT__c,
                Drawdown__r.Payment_Method__c,
                Drawdown__r.Reference_Notes__c,
                Drawdown__r.Date__c
            From Scheduled_Payment__c
            Where Opportunity__c = :opp.Id
            Order By Scheduled_Date__c ASC
        ];
        System.debug(System.LoggingLevel.ERROR, spList);
        for (Scheduled_Payment__c sp : spList) {
            System.debug(System.LoggingLevel.ERROR, sp);
        }

        sp1 = spList[0];
        System.assertEquals(opp.Id, sp1.Drawdown__r.Opportunity__c, 'Opp Should be set on Drawdown');
        System.assertEquals(sp1.Amount__c, sp1.Drawdown__r.Amount__c, 'Amounts should be the same');
        System.assertEquals('e-Transfer', sp1.Drawdown__r.Payment_Method__c, 'Payment Method');
        System.assertEquals('Payment to Client', sp1.Drawdown__r.Reference_Notes__c, 'Reference Notes');

        System.assertEquals(5, spList.size(), 'Should be 5 payments');
        dt = DateUtil.today();
        for (Scheduled_Payment__c sp : spList) {
            System.debug(System.LoggingLevel.ERROR, sp);
            System.assertEquals(opp.Drawdown_Amount__c, sp.Amount__c, 'Should be same amount');
            System.assertEquals(dt.month(), sp.Scheduled_Date__c.month(), 'Date should increment through months: ' + sp.Scheduled_Date__c.format());
            System.assert(sp.Current_Opportunity_Schedule_Version__c, 'Should be current schedule');
            dt = dt.addMonths(1);
        }
        test.stopTest();
        /*

        Scheduled_Payment__c sp2 = spList[1];
        sp2.Status__c = 'Approved to Send';
        sp2.Banking_Verified__c = true;
        sp2.BIA_PPSA_LL_Verified__c = true;
        sp2.Credit_Verified__c = true;
        sp2.Documents_Verified__c = true;
        update sp2;

        ScheduledPaymentHelper.generateDrawdowns(new Id[]{sp2.Id});

        spList = [
            Select
                Id, Status__c, Scheduled_Date__c, Amount__c, Current_Opportunity_Schedule_Version__c, EFT_Number__c,
                Drawdown__r.Amount__c,
                Drawdown__r.Opportunity__c,
                Drawdown__r.EFT__c,
                Drawdown__r.Payment_Method__c,
                Drawdown__r.Reference_Notes__c,
                Drawdown__r.Date__c
            From Scheduled_Payment__c
            Where Opportunity__c = :opp.Id
            Order By Scheduled_Date__c ASC
        ];
        System.debug(System.LoggingLevel.ERROR, spList);
        for (Scheduled_Payment__c sp : spList) {
            System.debug(System.LoggingLevel.ERROR, sp);
        }

        sp2 = spList[1];
        System.assertEquals(opp.Id, sp2.Drawdown__r.Opportunity__c, 'Opp Should be set on Drawdown');
        System.assertEquals(sp2.Amount__c, sp2.Drawdown__r.Amount__c, 'Amounts should be the same');
        System.assertEquals('e-Transfer', sp2.Drawdown__r.Payment_Method__c, 'Payment Method');
        System.assertEquals('Payment to Client', sp2.Drawdown__r.Reference_Notes__c, 'Reference Notes');

        System.assertEquals(5, spList.size(), 'Should be 5 payments');
        dt = DateUtil.today();
        for (Scheduled_Payment__c sp : spList) {
            System.debug(System.LoggingLevel.ERROR, sp);
            System.assertEquals(opp.Drawdown_Amount__c, sp.Amount__c, 'Should be same amount');
            System.assertEquals(dt.month(), sp.Scheduled_Date__c.month(), 'Date should increment through months: ' + sp.Scheduled_Date__c.format());
            System.assert(sp.Current_Opportunity_Schedule_Version__c, 'Should be current schedule');
            dt = dt.addMonths(1);
        }
        */

    }

    @isTest
    static void test_full_process_date() {
        // Test with no account set on SP
        DateUtil.today = Date.newInstance(2019, 1, 1);
        DateUtil.now = Datetime.newInstance(2019, 1, 1);

        Bank_Account__c bankRec = TestDataFactory.getBankAccountObjects(TestDataFactory.getBankAccountConfig(1), false)[0];
        bankRec.Mark_as_Primary__c = true;
        insert bankRec;

        Opportunity opp = TestDataFactory.getOpportunityObjects(1)[0];
        opp.StageName = 'Closed With Loan';
        opp.Stage_Status__c = 'Approved';
        opp.Amount = 5475.00;
        opp.Admin_Fee__c = 475.00;
        opp.Payout_Date__c = DateUtil.today();
        opp.Type_of_Loan__c = 'Facility Loan';
        opp.Minimum_Interest_Period__c = '0 months';
        opp.Compounding_Interest__c = 'Monthly';
        opp.Interest_Compounding_Period__c = 'Compounding Interest';
        opp.Interest_Rate__c = 24.5;

        opp.Payment_Schedule__c = 'Yes';
        opp.Payment_Schedule_Mode__c = Constants.PAYMENT_MODE_AMOUNT;
        opp.Payment_Use_Primary_Bank_Account__c = true;
        opp.Payment_Default_Bank_Account__c = bankRec.Id;
        opp.Start_Date__c = DateUtil.today();
        opp.End_Date__c = opp.Start_Date__c.addMonths(5);
        opp.Day_of_Month__c = '1st';
        opp.Payment_Schedule_Allotted_Amount__c = 5000.00;
        opp.Drawdown_Amount__c = 1000.00;
        opp.Payment_Schedule_Send_First_Immediately__c = false;
        opp.CloseDate = DateUtil.today();
        update opp;

        Scheduled_Payment__c[] spList = [
            Select
                Id, Status__c, Scheduled_Date__c, Amount__c, Current_Opportunity_Schedule_Version__c
            From Scheduled_Payment__c
            Where Opportunity__c = :opp.Id
            Order By Scheduled_Date__c ASC
        ];

        System.assertEquals(5, spList.size(), 'Should be 5 payments');
        Date dt = Dateutil.today();
        System.debug(System.LoggingLevel.ERROR, spList);
        for (Scheduled_Payment__c sp : spList) {
            System.debug(System.LoggingLevel.ERROR, sp);
            System.assertEquals(opp.Drawdown_Amount__c, sp.Amount__c, 'Should be same amount');
            System.assertEquals(dt.month(), sp.Scheduled_Date__c.month(), 'Date should increment through months: ' + sp.Scheduled_Date__c.format());
            System.assert(sp.Current_Opportunity_Schedule_Version__c, 'Should be current schedule');
            dt = dt.addMonths(1);
        }

        Scheduled_Payment__c sp1 = spList[0];
        sp1.Status__c = 'Approved to Send';
        sp1.Banking_Verified__c = true;
        sp1.BIA_PPSA_LL_Verified__c = true;
        sp1.Credit_Verified__c = true;
        sp1.Documents_Verified__c = true;
        sp1.EFT_Number__c = '123';
        update sp1;

        test.startTest();
        ScheduledPaymentHelper.generateDrawdowns(new Id[]{sp1.Id});

        spList = [
            Select
                Id, Status__c, Scheduled_Date__c, Amount__c, Current_Opportunity_Schedule_Version__c, EFT_Number__c,
                Drawdown__r.Amount__c,
                Drawdown__r.Opportunity__c,
                Drawdown__r.EFT__c,
                Drawdown__r.Payment_Method__c,
                Drawdown__r.Reference_Notes__c,
                Drawdown__r.Date__c
            From Scheduled_Payment__c
            Where Opportunity__c = :opp.Id
            Order By Scheduled_Date__c ASC
        ];
        System.debug(System.LoggingLevel.ERROR, spList);
        for (Scheduled_Payment__c sp : spList) {
            System.debug(System.LoggingLevel.ERROR, sp);
        }

        sp1 = spList[0];
        System.assertEquals(opp.Id, sp1.Drawdown__r.Opportunity__c, 'Opp Should be set on Drawdown');
        System.assertEquals(sp1.Amount__c, sp1.Drawdown__r.Amount__c, 'Amounts should be the same');
        System.assertEquals('e-Transfer', sp1.Drawdown__r.Payment_Method__c, 'Payment Method');
        System.assertEquals('Payment to Client', sp1.Drawdown__r.Reference_Notes__c, 'Reference Notes');

        System.assertEquals(5, spList.size(), 'Should be 5 payments');
        dt = DateUtil.today();
        for (Scheduled_Payment__c sp : spList) {
            System.debug(System.LoggingLevel.ERROR, sp);
            System.assertEquals(opp.Drawdown_Amount__c, sp.Amount__c, 'Should be same amount');
            System.assertEquals(dt.month(), sp.Scheduled_Date__c.month(), 'Date should increment through months: ' + sp.Scheduled_Date__c.format());
            System.assert(sp.Current_Opportunity_Schedule_Version__c, 'Should be current schedule');
            dt = dt.addMonths(1);
        }
        test.stopTest();
    }
}