src/objects/Drawdown__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Drawdowns</relationshipLabel>
        <relationshipName>Drawdowns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/BOM_Fee_Advance__c.field-meta.xml
<CustomField>
    <fullName>BOM_Fee_Advance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BOM Fee Advance</label>
    <referenceTo>Drawdown__c</referenceTo>
    <relationshipLabel>Drawdowns (BOM Fee Advance)</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Drawdown_Amount__c.field-meta.xml
<CustomField>
    <fullName>Drawdown_Amount__c</fullName>
    <formula>IF(OR(ISPICKVAL(Payment_Method__c,&apos;e-Transfer&apos;),ISPICKVAL(Payment_Method__c,&apos;Cheque&apos;)), Total_Amount__c,IF(ISPICKVAL(Payment_Method__c,&apos;Admin Fee&apos;),0,(0-Principal_Repaid__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Drawdown Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Drawdown_Amount__c</fullName>
        <label>Drawdown Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type_of_Loan__c</fullName>
        <label>Type of Loan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Facility Loan</fullName>
                </value>
                <value>
                    <fullName>Lump-Sum</fullName>
                    <default>true</default>
                    <label>Lump-Sum</label>
                </value>
                <value>
                    <fullName>Treatment Loan</fullName>
                </value>
                <value>
                    <fullName>Treatment Loan 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Amount_Available_for_Scheduled_Payments__c.field-meta.xml
<CustomField>
    <fullName>Amount_Available_for_Scheduled_Payments__c</fullName>
    <description>Calculates how much of the approved loan amount is available for new scheduled payments (does not consider &quot;Scheduled Facility)</description>
    <formula>Amount
    - IF(Admin_Fee_Roll_up__c &gt; 0, 0, Admin_Fee__c)
    - Drawdown_Total_w_o_payments_and_provider__c 
    - Total_Outstanding_Previous_Loans__c
				- Scheduled_Non_Facility_Treatment_Total__c
				- Total_Service_Providers_Allowance__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Available for Scheduled Payments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/Scheduled_Payment__c.object-meta.xml
<CustomObject>
    <label>Scheduled Payment</label>
    <nameField>
        <displayFormat>PS-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduled_Payment__c/fields/Drawdown__c.field-meta.xml
<CustomField>
    <fullName>Drawdown__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drawdown</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Drawdown__c.Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Opportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Drawdown__c</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Pre Send Validation</fullName>
            </value>
            <value>
                <fullName>Approved to Send</fullName>
            </value>
            <value>
                <fullName>Sent to Bank</fullName>
            </value>
            <value>
                <fullName>Processed by Bank</fullName>
            </value>
            <value>
                <fullName>Drawdown Created</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Won&apos;t Send</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DrawdownHelper.cls
/**
*    @description : Helper class for drawdowns
**/
public with sharing class DrawdownHelper {

    @AuraEnabled
    public static Drawdown__c[] getDrawdowns(String fields, String conditions, String extra) {
        if (String.isBlank(fields) || fields == 'all') {
            Map<String, Schema.SObjectField> allFields = Schema.SObjectType.Drawdown__c.fields.getMap();
            List<String> lstFields = new List<String>();
            for (Schema.SObjectField field : allFields.values()) {
                lstFields.add(field.getDescribe().getName());
            }
            
            // Building the query
            fields = String.join(lstFields, ',');
        }
        String strQuery = 'SELECT ' + fields + ' FROM Drawdown__c';

        if (!String.isBlank(conditions)) {
            strQuery += ' WHERE ' + conditions;
        }

        if (!String.isBlank(extra)) {
            strQuery += ' ' + extra;
        }

        //strQuery = String.escapeSingleQuotes(strQuery); // Sanitize Single Quotes

        return Database.query(strQuery);
    }

    //public static List<Scheduled_Payment__c> paymentsToUpdate = new List<Scheduled_Payment__c>();
    //public static List<Scheduled_Payment__c> paymentsToDelete = new List<Scheduled_Payment__c>();
    
    /**
    * @description Method to re-calculate payment schedules
    * @param List<Drawdown__c> drawdownsList
    * @return void
	// Replaced with process and InvocableMethod callout to consolidate work
    public static void updatePaymentScheduleForFacilityLoan(List<Drawdown__c> drawdownsList){
        Set<Id> opportunityIds = new Set<Id>();

        // loop through drawdown list 
        for(Drawdown__c drawdown : drawdownsList){
            if(drawdown.Amount__c != null){
                opportunityIds.add(drawdown.Opportunity__c);
            }
        }
    
        if(!opportunityIds.isEmpty()) adjustPaymentSchedulesForFacilityLoan(opportunityIds);
    }

    /**
    * @description Method to adjust payment schedules
    * @param List<Drawdown__c> drawdownsList
    * @return void
	// Replaced with process and InvocableMethod callout to consolidate work
    public static void adjustPaymentSchedulesForFacilityLoan(Set<Id> opportunityIds){
        Map<Id, Opportunity> opportunitiesMap = new Map<Id, Opportunity>([SELECT Id, Amount_Available_for_Scheduled_Payments__c, Drawdown_Amount__c, 
                                                                            (SELECT Id, Amount__c, Scheduled_Date__c FROM Scheduled_Payments__r WHERE Status__c =: Constants.PAYMENT_SCHEDULED_STATUS ORDER BY Scheduled_Date__c),
                                                                              (SELECT Amount__c FROM Drawdowns__r)
                                                                                FROM Opportunity WHERE Id IN: opportunityIds AND Type_of_Loan__c =: Constants.FACILITY_LOAN LIMIT 45000]);

        if(!opportunitiesMap.isEmpty()){
            for(Opportunity opportunity : opportunitiesMap.values()){
                PaymentHelper.recalculatePayments(opportunity,opportunity.Scheduled_Payments__r);
            }
        }

        if(!paymentsToUpdate.isEmpty()) update paymentsToUpdate;
        if(!paymentsToDelete.isEmpty()) delete paymentsToDelete;
    }
    **/
}