src/objects/Drawdown__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Adjusted_for_Repayments__c</fullName>
        <formula>(Amount__c -  Sum_of_Repayments__c )+ Interest_up_to_Last_Repayment__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Calculated Balance after last repayment.  This field will be used for calculating outstanding balance.</inlineHelpText>
        <label>Amount Adjusted for Repayments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Compounding_Frequency__c</fullName>
        <description>The Opportunity__r.Interest_Compounding_Period__c replicated down to the Drawdown to avoid hitting limits in formula calculations.</description>
        <inlineHelpText>The number of times per year that interest compounds.   Expressed as an integer.   For Daily interest this value will be adjusted to either 365 or 366 depending on the interest start date.</inlineHelpText>
        <label>Compounding Frequency</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Compounding_Interest__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The opportunity__r.compounding_Interest__c field has been replicated here to avoid exceeding cross object formula lmits.   Field was transformed to a checkbox to simplify usage in formulas as well.</description>
        <inlineHelpText>Indicates if loan interest is compounding or simple.</inlineHelpText>
        <label>Compounding Interest</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_Last_Repayment__c</fullName>
        <inlineHelpText>Date of last repayment applied to this Drawdown.   This field is a roll up summary (DLRS) of the Payment Allocations and should not be updated directly.</inlineHelpText>
        <label>Date of Last Repayment</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interest_Deferral_Period__c</fullName>
        <description>The Interest Deferral Period from the Opportunity, replicated here to avoid cross object formula size limitations.  Also converted to an number from a picklist value so it&apos;s readily usable in formulas.</description>
        <inlineHelpText>The months to defer interest on this Drawdown.</inlineHelpText>
        <label>Interest Deferral Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interest_End_Date__c</fullName>
        <formula>IF(Payout_Date__c&gt;ADDMONTHS(Date__c,Minimum_Interest_Period__c),Payout_Date__c,ADDMONTHS(Date__c,Minimum_Interest_Period__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Date Interest will be calculated TO.   Date is adjusted for minimum interest period.</inlineHelpText>
        <label>Interest End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interest_End_Date_at_Last_Repayment__c</fullName>
        <inlineHelpText>The date the interest had accrued to when last payment was recorded.    As this is a DLRS roll up summary, do no update directly.  Instead, update Payments.</inlineHelpText>
        <label>Interest End Date at Last Repayment</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interest_Start_Date__c</fullName>
        <description>NOTE: Adding one to the repayment date so we don&apos;t double count interest on the date of repayment.</description>
        <formula>IF(not(isblank(Date_of_Last_Repayment__c)), Interest_End_Date_at_Last_Repayment__c + 1,
 IF(Interest_Deferral_Period__c&gt;0, ADDMONTHS(Date__c,Interest_Deferral_Period__c),
    Date__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Start date of interest accrual adjusted for the minimum interest period and for interest already accounted for in prior periods.</inlineHelpText>
        <label>Interest Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interest_up_to_Last_Repayment__c</fullName>
        <inlineHelpText>Sum of all Interest Accrued up to the point of last repayment.   Used to calculate Outstanding Balance as Interest Accrued before Payment cannot be re-calculated dynamically.   This is a roll-up summary field (DLRS) and should not be updated directly.</inlineHelpText>
        <label>Interest up to Last Repayment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Drawdowns</relationshipLabel>
        <relationshipName>Drawdowns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payout_Date__c</fullName>
        <description>The Payout Date pulled down from the Opportunity to work around calculated field length limitations.  Do not update directly here, update on Opportunity instead and let it replicate down.</description>
        <inlineHelpText>Expected or Actual Payout Date of the Drawdown.  Do not update directly here, update on Opportunity instead and let it replicate down to here.</inlineHelpText>
        <label>Payout Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reference_Notes__c</fullName>
        <label>Reference Notes</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Payment_Method__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Admin Fee</fullName>
                </value>
                <value>
                    <fullName>Admin Fee charged up front</fullName>
                </value>
                <value>
                    <fullName>Bad Debt</fullName>
                </value>
                <value>
                    <fullName>EFT Reject</fullName>
                </value>
                <value>
                    <fullName>EFT Reprocessed</fullName>
                </value>
                <value>
                    <fullName>EFT to Client</fullName>
                </value>
                <value>
                    <fullName>Fee</fullName>
                </value>
                <value>
                    <fullName>Loan Payout</fullName>
                </value>
                <value>
                    <fullName>Other Fee</fullName>
                </value>
                <value>
                    <fullName>Partial Payment</fullName>
                </value>
                <value>
                    <fullName>Payment Rejected</fullName>
                </value>
                <value>
                    <fullName>Payment Re-processed</fullName>
                </value>
                <value>
                    <fullName>Payment Shortfall</fullName>
                </value>
                <value>
                    <fullName>Payment Surplus</fullName>
                </value>
                <value>
                    <fullName>Payment to Client</fullName>
                </value>
                <value>
                    <fullName>Payment to Lawyer</fullName>
                </value>
                <value>
                    <fullName>Payment to other lender</fullName>
                </value>
                <value>
                    <fullName>Payment to Third-Party</fullName>
                </value>
                <value>
                    <fullName>Payment to Treatment - Service Provider</fullName>
                </value>
                <value>
                    <fullName>Referral Fee</fullName>
                </value>
                <value>
                    <fullName>Waived Fee</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Has_Interest__c.field-meta.xml
<CustomField>
    <fullName>Has_Interest__c</fullName>
    <formula>NOT(OR( ISPICKVAL(Reference_Notes__c,&quot;Referral Fee&quot;),
ISPICKVAL(Reference_Notes__c,&quot;Refund&quot;),
ISPICKVAL(Reference_Notes__c,&quot;Payment Re-processed&quot;),
ISPICKVAL(Payment_Method__c, &apos;Payment&apos;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Has Interest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/No_Interest__c.field-meta.xml
<CustomField>
    <fullName>No_Interest__c</fullName>
    <formula>ISPICKVAL(Reference_Notes__c,&quot;Admin Fee - No Interest&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>No Interest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Outstanding_Balance_VR__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Balance_VR__c</fullName>
    <label>Outstanding Balance VR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Compounding_Interest__c</fullName>
        <label>Interest Compounding Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Interest_Compounding_Period__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-Annual</fullName>
                </value>
                <value>
                    <fullName>Annual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_of_advance__c</fullName>
        <label>Date of advance</label>
        <summarizedField>Drawdown__c.Date__c</summarizedField>
        <summaryForeignKey>Drawdown__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Interest_Deferral_Period__c</fullName>
        <label>Interest Deferral Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>48</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payout_Date__c</fullName>
        <label>Payout Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Compounding_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Compounding_Frequency__c</fullName>
    <formula>CASE(Text(Compounding_Interest__c), 
&quot;Annual&quot;,1,
&quot;Semi-Annual&quot;,2,
&quot;Quarterly&quot;,4,
&quot;Monthly&quot;,12,
&quot;Daily&quot;, 365,
0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Compounding Frequency</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Minimum_Interest_Period_Number__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Interest_Period_Number__c</fullName>
    <formula>Case(Text(Minimum_Interest_Period__c ),
&quot;1 month&quot;,1,
&quot;2 months&quot;,2,
&quot;3 months&quot;,3,
&quot;4 months&quot;,4,
&quot;5 months&quot;,5,
&quot;6 months&quot;,6,
&quot;7 months&quot;,7,
&quot;8 months&quot;,8,
&quot;9 months&quot;,9,
&quot;10 months&quot;,10,
&quot;11 months&quot;,11,
&quot;12 months&quot;,12,
0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Minimum Interest Period Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Variable_Rate__c/Variable_Rate__c.object-meta.xml
<CustomObject>
    <label>Variable Rate</label>
    <nameField>
        <label>Variable Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variable Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Variable_Rate__c/fields/Month_End__c.field-meta.xml
<CustomField>
    <fullName>Month_End__c</fullName>
    <label>Month End</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Variable_Rate__c/fields/Month_Start__c.field-meta.xml
<CustomField>
    <fullName>Month_Start__c</fullName>
    <label>Month Start</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Variable_Rate__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Variable Rates</relationshipLabel>
    <relationshipName>Variable_Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/InterestCalculator.cls
public class InterestCalculator {
    public static Decimal getCompoundInterestMultiplier(Decimal annualRate, Decimal compoundingFrequency, Date interestStartDate, Date interestEndDate){
        Integer accrualDays = interestStartDate.daysBetween(interestEndDate) + 1;
        System.debug('Accrual Days ' + accrualDays);
        Decimal accrualYears = accrualDays / 366.0;
        //accrualYears = accrualYears.setScale(5);
        System.debug('Accrual Years ' + accrualYears);
        System.debug('Annual rate ' + annualRate);
        System.debug('Compounding freq ' + compoundingFrequency);
        Decimal value = 1.0 + annualRate /( 100.0 * compoundingFrequency);
        Decimal exp = compoundingFrequency * accrualYears;
        System.debug(value);
        System.debug(exp);
        Decimal result = Math.exp(Math.log(value) * exp);
        System.debug('Result ' + result);
        return result;
    }
    public static Decimal getCompoundInterest(Decimal principal, Decimal annualRate, Decimal compoundingFrequency, Date interestStartDate, Date interestEndDate){
        Decimal multiplier = getCompoundInterestMultiplier(annualRate, compoundingFrequency, interestStartDate, interestEndDate);        
        Decimal result = multiplier * principal;
        //result = result.setScale(2);
        System.debug('Result ' + result);
        return result;
    }    
    public static void calculateVariableRates(Id oppId){
        List<Opportunity> opps = [select Id, Date_Of_Advance__c, Payout_Date__c, Minimum_Interest_Period_Number__c, 
                                  Interest_Deferral_Period__c, Compounding_Frequency__c from Opportunity where Id = :oppId];
        if (!opps.isEmpty()){
            Date payoutDate = opps[0].Payout_Date__c;
            if (payoutDate != null){
                opps[0].Payout_Date__c = null;
                update opps;
                opps[0].Payout_Date__c = payoutDate;
            }
            else 
                opps[0].Payout_Date__c = Date.today();
            update opps;
        }
        calculateVariableRates(opps);
    }
    public static Date getInterestStartDate(Drawdown__c d, Opportunity opp, Boolean isBOM){
        if (d.Interest_Start_Date__c != null)
            return d.Interest_Start_Date__c;
        Date interestStartDate = d.Date__c;
        if (opp.Interest_Deferral_Period__c != null && Integer.valueOf(opp.Interest_Deferral_Period__c) > 0)
            return interestStartDate.addMonths(Integer.valueOf(opp.Interest_Deferral_Period__c));
        if (d.Date_of_Last_Repayment__c != null)
            return d.Interest_End_Date_at_Last_Repayment__c.addDays(1);
        return d.Date__c;        
    }    
    public static Date getInterestEndDate(Date payoutDate, Drawdown__c d, Opportunity opp, Boolean isBOM){
        if (isBOM)
            return payoutDate;
        if (payoutDate == d.Date__c)
            return payoutDate;
        Date minimumInterestPeriodDate = d.Date__c.addDays((Integer)(30 * Integer.valueOf(opp.Minimum_Interest_Period_Number__c) - 1));
        return payoutDate > minimumInterestPeriodDate ? payoutDate : minimumInterestPeriodDate;
    }
    public static void calculateVariableRates(List<Drawdown__c> drds, List<Variable_Rate__c> vrs, Date payoutDate, Opportunity opp){
        for (Drawdown__c d : drds){
            Decimal amountAdjustedForRepayment = d.Amount_Adjusted_for_Repayments__c;
            if (amountAdjustedForRepayment == null)
                amountAdjustedForRepayment = d.Amount__c;

            if (d.No_Interest__c){
                d.Outstanding_Balance_VR__c = amountAdjustedForRepayment;
            }
            else{
                Date effectiveDate = opp.Date_Of_Advance__c;
                Decimal totalMultiplier = 1.0;
                Boolean isBOM = d.Reference_Notes__c == 'Admin Fee - BOM';
                Date drawdownInterestStartDate = getInterestStartDate(d, opp, isBOM);                
                Date drawdownInterestEndDate = getInterestEndDate(payoutDate, d, opp, isBOM);
                System.debug(drawdownInterestEndDate);
                for (Variable_Rate__c vr : vrs){
                    Date vrStartDate = effectiveDate.addMonths((Integer)vr.Month_Start__c - 1);                    
                    //vrStartDate = vrStartDate.addDays(1);
                    Date vrEndDate = vr.Month_End__c == null ? null : effectiveDate.addMonths((Integer)vr.Month_End__c).addDays(-1); 
                    System.debug('Dates ' + amountAdjustedForRepayment + ' ' + drawdownInterestStartDate + ' ' + drawdownInterestEndDate +' ' +vrStartDate + ' ' + vrEndDate);
                    if (drawdownInterestEndDate >= vrStartDate && (vrEndDate == null || drawdownInterestStartDate <= vrEndDate)){
                        Date interestStartDate = (drawdownInterestStartDate < vrStartDate) ? vrStartDate : drawdownInterestStartDate;
                        Date interestEndDate = (vrEndDate != null && drawdownInterestEndDate >= vrEndDate) ? vrEndDate : drawdownInterestEndDate;
                        System.debug(interestStartDate);
                        System.debug(interestEndDate);
                        System.debug(vr.Rate__c);
                        Decimal multiplier = InterestCalculator.getCompoundInterestMultiplier(vr.Rate__c, Integer.valueOf(opp.Compounding_Frequency__c), interestStartDate, interestEndDate);                       
                        totalMultiplier *= multiplier;                        
                    }
                }
                d.Outstanding_Balance_VR__c = amountAdjustedForRepayment * totalMultiplier;
            }            
        }

    }
    public static void calculateVariableRates(List<Opportunity> vrOpps){
        System.debug('calculateVariableRates');
        List<Id> vrOppIds = new List<Id>();
        Map<Id, Opportunity> oppsMap = new Map<Id, Opportunity>();
        for (Opportunity opp : vrOpps){
            vrOppIds.add(opp.Id);
            oppsMap.put(opp.Id, opp);
        }
        List<Variable_Rate__c> variableRates = [Select Month_Start__c, Month_End__c, Rate__c, Opportunity__c  from Variable_Rate__c where Opportunity__c in :vrOppIds order by Opportunity__c, Month_Start__c asc];
        List<Drawdown__c> drawdowns = [select Id, No_Interest__c, Amount__c, Opportunity__c, Date__c, Interest_up_to_Last_Repayment__c, Amount_Adjusted_for_Repayments__c,
                                       Compounding_Interest__c, Compounding_Frequency__c, Interest_Start_Date__c, Interest_End_Date__c, Reference_Notes__c, Outstanding_Balance_VR__c 
                                       from Drawdown__c where Opportunity__c in :vrOppIds and Has_Interest__c = true];
        Map<Id, List<Variable_Rate__c>> oppIdToVRs = new Map<Id, List<Variable_Rate__c>>();
        for (Variable_Rate__c vr : variableRates){            
            if (oppIdToVRs.containsKey(vr.Opportunity__c)){
                oppIdToVRs.get(vr.Opportunity__c).add(vr);
            }
            else
                oppIdToVRs.put(vr.Opportunity__c, new List<Variable_Rate__c>{vr});
        }
        List<Drawdown__c> drawdownsToUpdate = new List<Drawdown__c>();
        for (Opportunity opp : vrOpps){
            List<Drawdown__c> drawdownsForOpp = new List<Drawdown__c>();
            for (Drawdown__c d : drawdowns){   
                if (d.Opportunity__c == opp.Id)
                    drawdownsForOpp.add(d);
            }
            if (!drawdownsForOpp.isEmpty()){
                List<Variable_Rate__c> vrs = oppIdToVRs.get(opp.Id);
                calculateVariableRates(drawdownsForOpp, vrs, opp.Payout_Date__c, opp);
                drawdownsToUpdate.addAll(drawdownsForOpp);
            }
        }
		if (!drawdownsToUpdate.isEmpty())
            update drawdownsToUpdate;
    }

    /*public static Double getCompoundInterestMultiplier(Double annualRate, Integer compoundingFrequency, Date interestStartDate, Date interestEndDate){
        Integer accrualDays = interestStartDate.daysBetween(interestEndDate) + 1;
        System.debug('Accrual Days ' + accrualDays);
        Double accrualYears = accrualDays / 365.0;
        System.debug('Accrual Years ' + accrualYears);
        Double doubleValue = (Double)1.0 + annualRate /( 100.0 * compoundingFrequency);
        Double exp = (Double)compoundingFrequency * accrualYears;
        System.debug(doubleValue);
        System.debug(exp);
        Double result = Math.pow(doubleValue, exp);
        System.debug('Result ' + result);
        return result;
    }
    public static Double getCompoundInterest(Double principal, Double annualRate, Integer compoundingFrequency, Date interestStartDate, Date interestEndDate){
        Double multiplier = getCompoundInterestMultiplier(annualRate, compoundingFrequency, interestStartDate, interestEndDate);        
        Double result = multiplier * principal;
        System.debug('Result ' + result);
        return result;
    }*/
}