src/objects/Firm__c.object
<CustomObject>
    <fields>
        <fullName>Date_of_Update__c</fullName>
        <label>Date of Update</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Law_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Law Firm</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Firms</relationshipLabel>
        <relationshipName>Firms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lawyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lawyer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Firms</relationshipLabel>
        <relationshipName>Firms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Firms</relationshipLabel>
        <relationshipName>Firms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Firm</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Firm Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Firms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Law_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Law Firm</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Referred Cases</relationshipLabel>
        <relationshipName>Referred_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lawyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lawyer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referred Cases</relationshipLabel>
        <relationshipName>Referred_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/FirmHandler.cls
public with sharing class FirmHandler {
	
	public static void createActivityHistory(Map<Id,Opportunity> newMap){
        
        List<Firm__c> lstFirm = new List<Firm__c>();
        
        for(Opportunity opp : newMap.values()){
            Opportunity oppr = (Opportunity)Trigger.oldMap.get(opp.Id);
            
            if(opp.Law_Firm__c != oppr.Law_Firm__c ||
               opp.Lawyer__c != oppr.Lawyer__c 
               ){
                Firm__c firm = new Firm__c();
                firm.Law_Firm__c = opp.Law_Firm__c;
                firm.Lawyer__c = opp.Lawyer__c;
                firm.Date_of_Update__c = Date.today();
                firm.Opportunity__c = opp.Id;

                lstFirm.add(firm);
            }
        }

        if(lstFirm.size() > 0){
            insert lstFirm; 
        }
    }
}