src/objects/Opportunity.object
<CustomObject>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/VR_Fees_Generating_In_Progress__c.field-meta.xml
<CustomField>
    <fullName>VR_Fees_Generating_In_Progress__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VR Fees Generating In Progress</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/VR_Fees_Generating_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>VR_Fees_Generating_Start_Time__c</fullName>
    <label>VR Fees Generating Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/CreateFeesForOppQueueable.cls
public class CreateFeesForOppQueueable implements Queueable{
    Id oppId;
    Boolean onlyBOM;
    public CreateFeesForOppQueueable (Id oppId){
        this.oppId = oppId;        
    }
    
   	public void execute(QueueableContext context) {        
        try{
        	VariableFeeHelper.createFeesForOpp(oppId);                
            VariableFeeHelper.createBOMFeesForOpp(oppId);        
        	InterestCalculator.calculateVariableRates(oppId);
        }
        catch(Exception ex){
		}
        Opportunity opp = [select Id, VR_Fees_Generating_In_Progress__c from Opportunity where Id=:oppId];        
        opp.VR_Fees_Generating_In_Progress__c = false;
        opp.VR_Fees_Generating_Start_Time__c = null;
        update opp;
    }
}