src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Payout_Date__c</fullName>
        <label>Payout Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Payout__c</fullName>
        <formula>(Drawdown_Total_wo_Payment__c + Payout_Interest__c) - Payment_Roll_up__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Payout</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Accrued_Interest_as_of_Reserve_Date__c.field-meta.xml
<CustomField>
    <fullName>Accrued_Interest_as_of_Reserve_Date__c</fullName>
    <label>Accrued Interest as of Reserve Date</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_Reserve_Applied__c.field-meta.xml
<CustomField>
    <fullName>Is_Reserve_Applied__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Reserve Applied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Non_Repaid_Drawdown_Principal_Total__c.field-meta.xml
<CustomField>
    <fullName>Non_Repaid_Drawdown_Principal_Total__c</fullName>
    <formula>Drawdown_Principal_Total__c - Principal_Repaid_Roll_up__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Non Repaid Drawdown Principal Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Principal_Non_Repaid_as_of_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Principal_Non_Repaid_as_of_To_Date__c</fullName>
    <formula>Principal_Borrowed_as_of_To_Date__c - Principal_Repaid_as_of_To_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Principal Non Repaid as of To Date</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reserve_Amount__c.field-meta.xml
<CustomField>
    <fullName>Reserve_Amount__c</fullName>
    <label>Reserve Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reserve_Date__c.field-meta.xml
<CustomField>
    <fullName>Reserve_Date__c</fullName>
    <label>Reserve Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reserve_Exposure__c.field-meta.xml
<CustomField>
    <fullName>Reserve_Exposure__c</fullName>
    <formula>Reserve_Principal_Advanced__c + Accrued_Interest_as_of_Reserve_Date__c - Reserve_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reserve Exposure</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reserve_Principal_Advanced__c.field-meta.xml
<CustomField>
    <fullName>Reserve_Principal_Advanced__c</fullName>
    <label>Reserve Principal Advanced</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stop_Interest__c.field-meta.xml
<CustomField>
    <fullName>Stop_Interest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Stop Interest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ReserveHelper.cls
public class ReserveHelper {
	public static List<Opportunity> applyReserveOpps(List<Map<String, Object>> reserveInfos){        
        List<Id> oppIds = new List<Id>();
        List<Id> oppWithReserveIds = new List<Id>();
        for (Map<String, Object> reserveInfoMap : reserveInfos){    
            prepareReserveMap(reserveInfoMap);
            oppIds.add((Id)reserveInfoMap.get('Id'));
            Boolean isReserveApplied = Boolean.valueOf(reserveInfoMap.get('Is_Reserve_Applied__c'));
            if (isReserveApplied)
                oppWithReserveIds.add((Id)reserveInfoMap.get('Id'));
        }
        if (!oppIds.isEmpty()){
            List<Opportunity> opps = [select Payout_Date__c, Reserve_Date__c, Reserve_Amount__c, Is_Reserve_Applied__c, Accrued_Interest_as_of_Reserve_Date__c,
                                      Reserve_Principal_Advanced__c, Stop_Interest__c from Opportunity where Id in :oppIds];
            Map<Id, Opportunity> idToOppMap = new Map<Id, Opportunity>();
            for (Opportunity opp : opps){
                idToOppMap.put(opp.Id, opp);
            }
            for (Map<String, Object> reserveInfoMap : reserveInfos){
                Id oppId = (Id)reserveInfoMap.get('Id');                    
                Opportunity opp = idToOppMap.get(oppId);
                updateOppReserveFields(opp, reserveInfoMap);
            }
            update opps;
            updateOppsWithReserveApplied(oppWithReserveIds);
            opps = [select Is_Reserve_Applied__c, Payout_Date__c, Reserve_Date__c,Interest_Accrued_as_of_Payout_Date__c, Drawdown_Principal_Total__c,
                    Reserve_Principal_Advanced__c, Accrued_Interest_as_of_Reserve_Date__c, Reserve_Exposure__c, Reserve_Amount__c, Stop_Interest__c from Opportunity where Id=:oppIds];
            return opps;
        }

        return new List<Opportunity>();
    }
    @TestVisible
    private static void prepareReserveMap(Map<String, Object> reserveInfoMap){
        if (reserveInfoMap.get('Is_Reserve_Applied__c') == null)
            reserveInfoMap.put('Is_Reserve_Applied__c', false);
        if (reserveInfoMap.get('Stop_Interest__c') == null)
            reserveInfoMap.put('Stop_Interest__c', false);        
        if (Boolean.valueOf(reserveInfoMap.get('Is_Reserve_Applied__c')) == true){
            if (reserveInfoMap.get('Reserve_Amount__c') == null)
                reserveInfoMap.put('Reserve_Amount__c', 0.0);
            if (reserveInfoMap.get('Reserve_Date__c') == null)
                reserveInfoMap.put('Reserve_Date__c', Date.today());
        }
    }
    @TestVisible
    private static void updateOppReserveFields(Opportunity opp, Map<String, Object> reserveInfoMap){
        Boolean isReserveApplied = Boolean.valueOf(reserveInfoMap.get('Is_Reserve_Applied__c'));         
        opp.Is_Reserve_Applied__c = isReserveApplied;
        opp.Stop_Interest__c = Boolean.valueOf(reserveInfoMap.get('Stop_Interest__c')); 
        if (!isReserveApplied){
            opp.Reserve_Date__c = null;            
            opp.Reserve_Amount__c = null;
            opp.Accrued_Interest_as_of_Reserve_Date__c = null;
            opp.Reserve_Principal_Advanced__c = null;
        }            
        else{
            Date reserveDate = reserveInfoMap.get('Reserve_Date__c') instanceOf Date ? Date.valueOf(reserveInfoMap.get('Reserve_Date__c')) : Date.valueOf((String)reserveInfoMap.get('Reserve_Date__c'));
            opp.Reserve_Date__c = reserveDate;
            opp.Payout_Date__c = reserveDate;                
            opp.Reserve_Amount__c = Double.valueOf(reserveInfoMap.get('Reserve_Amount__c'));
        }                                        
    }
    
    private static void updateOppsWithReserveApplied(List<Id> oppWithReserveIds){
        if (!oppWithReserveIds.isEmpty()){
            List<Opportunity> opps = [select Is_Reserve_Applied__c, Non_Repaid_Drawdown_Principal_Total__c, Payout_Date__c, Reserve_Date__c, Interest_Accrued_as_of_Payout_Date__c, Drawdown_Principal_Total__c,Principal_Non_Repaid_as_of_To_Date__c,
                    Reserve_Principal_Advanced__c, Accrued_Interest_as_of_Reserve_Date__c, Reserve_Exposure__c, Total_Payout__c, Principal_Repaid_Roll_up__c from Opportunity where Id  in :oppWithReserveIds];
            for (Opportunity opp : opps){
                Decimal principal = opp.Non_Repaid_Drawdown_Principal_Total__c;
                opp.Accrued_Interest_as_of_Reserve_Date__c = opp.Total_Payout__c - principal;
                opp.Reserve_Principal_Advanced__c = principal;
            }
            update opps;
        }
    }
}