force-app/main/default/objects/AFT_File__c/AFT_File__c.object-meta.xml
<CustomObject>
    <label>AFT File</label>
    <nameField>
        <displayFormat>AFT-{0000}</displayFormat>
        <label>AFT File Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AFT Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AFT_File__c/fields/Credit_Transaction_Count__c.field-meta.xml
<CustomField>
    <fullName>Credit_Transaction_Count__c</fullName>
    <label>Credit Transaction Count</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AFT_File__c/fields/Total_Credit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Credit_Amount__c</fullName>
    <label>Total Credit Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AFT_File__c/fields/Total_Debit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Debit_Amount__c</fullName>
    <label>Total Debit Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AFT_File_Setting__mdt/AFT_File_Setting__mdt.object-meta.xml
<CustomObject>
    <label>AFT File Setting</label>
    <pluralLabel>AFT File Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/AFT_File_Setting__mdt/fields/Account_Number_for_Returns__c.field-meta.xml
<CustomField>
    <fullName>Account_Number_for_Returns__c</fullName>
    <label>Account Number for Returns</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AFT_File_Setting__mdt/fields/Destination_Data_Centre__c.field-meta.xml
<CustomField>
    <fullName>Destination_Data_Centre__c</fullName>
    <label>Destination Data Centre</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AFT_File_Setting__mdt/fields/File_Number__c.field-meta.xml
<CustomField>
    <fullName>File_Number__c</fullName>
    <label>File Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AFT_File_Setting__mdt/fields/Institutional_ID_for_Returns__c.field-meta.xml
<CustomField>
    <fullName>Institutional_ID_for_Returns__c</fullName>
    <label>Institutional ID for Returns</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AFT_File_Setting__mdt/fields/Originator_Id__c.field-meta.xml
<CustomField>
    <fullName>Originator_Id__c</fullName>
    <label>Originator Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AFT_File_Setting__mdt/fields/Originator_Long_Name__c.field-meta.xml
<CustomField>
    <fullName>Originator_Long_Name__c</fullName>
    <label>Originator Long Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AFT_File_Setting__mdt/fields/Originator_Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Originator_Short_Name__c</fullName>
    <label>Originator Short Name</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CWB_File_Setting__c/CWB_File_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CWB File Setting</label>
</CustomObject>

force-app/main/default/objects/CWB_File_Setting__c/fields/ELFI_File_Number__c.field-meta.xml
<CustomField>
    <fullName>ELFI_File_Number__c</fullName>
    <label>ELFI File Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CWB_File_Setting__c/fields/Rhino_File_Number__c.field-meta.xml
<CustomField>
    <fullName>Rhino_File_Number__c</fullName>
    <label>Rhino File Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CWB_File_Setting__c/fields/Seahold_File_Number__c.field-meta.xml
<CustomField>
    <fullName>Seahold_File_Number__c</fullName>
    <label>Seahold File Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/Scheduled_Payment__c.object-meta.xml
<CustomObject>
    <label>Scheduled Payment</label>
    <nameField>
        <displayFormat>PS-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduled_Payment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account that payment should be sent to (will default to Opportunity Account if not set)</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/AFT_File__c.field-meta.xml
<CustomField>
    <fullName>AFT_File__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AFT File</label>
    <referenceTo>AFT_File__c</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/AFT_File_Number__c.field-meta.xml
<CustomField>
    <fullName>AFT_File_Number__c</fullName>
    <label>AFT File Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Bank account that we send the funds to</description>
    <label>Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Bank_Account__c.Client__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Can_Send_to_Bank__c.field-meta.xml
<CustomField>
    <fullName>Can_Send_to_Bank__c</fullName>
    <description>Does the current user have the permission to send this to the bank?</description>
    <formula>AND(
				$Permission.Can_Process_Scheduled_Payments,
    OR(
				    $User.Id &lt;&gt; Verified_By__c,
			    	$Permission.EFT_Permission
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Can Send to Bank</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Current_Bank_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Current_Bank_Account_Id__c</fullName>
    <description>The Id of the bank account that would be used if the payment was processed</description>
    <formula>IF(
    ISBLANK(Sent_to_Bank_Account__c),
    IF(
        Use_Primary_Bank_Account__c,
        IF(
            OR(ISBLANK(Account__c), ISBLANK(Account__r.Primary_Bank_Account__c)),
            IF(
                ISBLANK(Opportunity__r.Account.Primary_Bank_Account__c),
                NULL,
                Opportunity__r.Account.Primary_Bank_Account__c
            ),
            Account__r.Primary_Bank_Account__c
        ),
        IF(
            ISBLANK(Bank_Account__c),
            NULL,
            Bank_Account__c
        )
    ),
    Sent_to_Bank_Account__c
)</formula>
    <label>Current Bank Account Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Current_Bank_Account_URL__c.field-meta.xml
<CustomField>
    <fullName>Current_Bank_Account_URL__c</fullName>
    <formula>&apos;/&apos; +
IF(
				ISBLANK(Current_Bank_Account_Id__c),
				IF(
								ISBLANK(Account__c),
								Opportunity__r.AccountId,
								Account__c
				),
				Current_Bank_Account_Id__c
)</formula>
    <label>Current Bank Account URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/CWB_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>CWB_Business_Unit__c</fullName>
    <label>CWB Business Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/CWB_Sheet_Number__c.field-meta.xml
<CustomField>
    <fullName>CWB_Sheet_Number__c</fullName>
    <formula>IF(AFT_File_Number__c &gt; 0,  CWB_Business_Unit__c + &quot; - &quot; + LPAD(TEXT(AFT_File_Number__c), 4, &apos;0&apos;), &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CWB Sheet Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/EFT_File__c.field-meta.xml
<CustomField>
    <fullName>EFT_File__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>EFT File</label>
    <referenceTo>EFT_File__c</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/File_Number__c.field-meta.xml
<CustomField>
    <fullName>File_Number__c</fullName>
    <formula>EFT_File__r.File_Number__c</formula>
    <label>File Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Send_Cheque__c.field-meta.xml
<CustomField>
    <fullName>Send_Cheque__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Send a Cheque instead of an EFT</description>
    <label>Send Cheque</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Sent_to_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Sent_to_Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Bank account EFT was actually sent to</description>
    <label>Sent to Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Scheduled Payments (Sent to Bank Account)</relationshipLabel>
    <relationshipName>Sent_Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Sent_to_Bank_By__c.field-meta.xml
<CustomField>
    <fullName>Sent_to_Bank_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User that generated the Banking Sheet this Payment was included in.</description>
    <label>Sent to Bank By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Sent_to_Bank_Date__c.field-meta.xml
<CustomField>
    <fullName>Sent_to_Bank_Date__c</fullName>
    <description>Date and Time this payment was included in a banking sheet</description>
    <label>Sent to Bank Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Pre Send Validation</fullName>
            </value>
            <value>
                <fullName>Approved to Send</fullName>
            </value>
            <value>
                <fullName>Sent to Bank</fullName>
            </value>
            <value>
                <fullName>Processed by Bank</fullName>
            </value>
            <value>
                <fullName>Drawdown Created</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Won&apos;t Send</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Transaction_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Reference_Number__c</fullName>
    <description>Reference number to match EFT to Scheduled Payments (Date Sent + Random Digits)</description>
    <label>Transaction Reference Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AFTFile.cls
/**
 * @File Name          : AFTFile.cls
 * @Description        : 
 * @Author             : fahad.khan@toptal.com
 * @Group              : 
 * @Last Modified By   : fahad.khan@toptal.com
 * @Last Modified On   : 6/18/2020, 3:02:20 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    6/18/2020   fahad.khan@toptal.com     Initial Version
**/
public with sharing class AFTFile {
    
    private Id[] spIds;
    private Scheduled_Payment__c[] spList;
    private Map<Id, Bank_Account__c> bankAccountList;
    private Decimal amountCreditTotal = 0;
    private Integer creditTransactionCount = 0;
    private Decimal amountDebitTotal = 0;
    private Integer debitTransactionCount = 0;
    private Date dueDate;
    private String businessUnitFilter = 'ELFI';
    
    public AFTFile(Id[] spIds, String businessUnitFilter) {
        this.dueDate = DateUtil.today();
        this.spIds = spIds;
        this.businessUnitFilter = businessUnitFilter;
    }

    public AFTFile(Id[] spIds, Date dueDate) {
        this.dueDate = dueDate;
        this.spIds = spIds;
    }
    
    public class GroupedPayments {
        public Decimal total {public get; private set;}
        public Scheduled_Payment__c[] spList;
        public String referenceNumber;
        public Bank_Account__c bankAccount;
        
        public GroupedPayments(Bank_Account__c bankAccount) {
            this.total = 0;
            this.spList = new Scheduled_Payment__c[]{};
                this.bankAccount = bankAccount;
            Blob blobKey = crypto.generateAesKey(128);
            String key = EncodingUtil.base64encode(blobKey).remove('/');
            this.referenceNumber = DateUtil.now().format('ddMMyy') + '-' + key.substring(0, 11);
        }
        
        public void addPayment(Scheduled_Payment__c sp) {
            spList.add(sp);
            total += sp.Amount__c;
            sp.Transaction_Reference_Number__c = referenceNumber;
        }
    }
    
    private void fetchData() {
       this.spList = [
            Select
                Id, Name, Amount__c, Status__c, Current_Bank_Account_Id__c, Can_Send_to_Bank__c, AFT_File_Number__c, CWB_Sheet_Number__c, // Scheduled Payment Fields
                Opportunity__r.AccountId // Opportunity Fields
            FROM Scheduled_Payment__c
            WHERE Id in :this.spIds
            ORDER BY Current_Bank_Account_Id__c
        ];

        // Collect Account Ids
        Set<Id> bankAccountIds = new Set<id>();
        for (Scheduled_Payment__c sp : this.spList) {
            bankAccountIds.add(sp.Current_Bank_Account_Id__c);
        }

        // Fetch Accounts with Bank Account and Contact information mapped by Id for ease of use
        this.bankAccountList = new Map<Id, Bank_Account__c>([
            SELECT Id, Name, Bank__c, Transit__c, Account__c, Client__r.Name, Client__r.AccountNumber
            FROM Bank_Account__c
            WHERE Id in :bankAccountIds
            ORDER BY Id
        ]);
    }
    
    private AFT_File__c getAFTFileObj() {
        AFT_File__c aftFileObj = new AFT_File__c();
        insert aftFileObj;
        aftFileObj = [Select Id, Name, File_Number__c From AFT_File__c Where Id = :aftFileObj.Id];
        if (aftFileObj.File_Number__c == '0000') {
            // If File Number is 0000 it is invalid, so we must delete that object and create another so the Auto-number increments
            delete aftFileObj;
            return getAFTFileObj();
        }
        return aftFileObj;
    }
    
    private void UpdateCWBFileSettings(String businessUnit, CWB_File_Setting__c cwbFileCustomSetting, Integer fileNumber){
        
        if(businessUnit == 'ELFI'){
            cwbFileCustomSetting.ELFI_File_Number__c = fileNumber;            
        }else if(businessUnit == 'Rhino'){
            cwbFileCustomSetting.Rhino_File_Number__c = fileNumber;
        }else if(businessUnit == 'Seahold'){
            cwbFileCustomSetting.Seahold_File_Number__c = fileNumber;
        }
        upsert cwbFileCustomSetting;
    }
        
    public String generateFileText() {
        
        // initilize Exception Collection
        EFTFileException[] errorList = new EFTFileException[]{};
            
        String aftFileData = '';
        this.fetchData();
        Integer logicalRecordCount = 1;
        String businessUnit = this.businessUnitFilter != null && !String.isEmpty(this.businessUnitFilter) && this.businessUnitFilter != 'All'? this.businessUnitFilter : 'ELFI';
        
        /****************************************************************
         * 						Validation
         * **************************************************************/
        Set<String> oldFileNumbers = new Set<String>();
        integer oldSpCount = 0;
        Boolean hasNewPayments = false;
        try{
            for(Scheduled_Payment__c sp : this.spList){
                if(sp.CWB_Sheet_Number__c != null && sp.CWB_Sheet_Number__c != ''){
                    oldFileNumbers.add(sp.CWB_Sheet_Number__c);
                    oldSpCount++;
                }else{
                    hasNewPayments = true;
                }
            }
            if(oldFileNumbers.size() > 1){
                throw new EFTFileException(null, '', 'Banking sheet can not include failed payments of two different files.' );
            }
        }catch(EFTFileException e){
            errorList.add(e);
            throw new EFTFileErrorListException(errorList);
        }
        system.debug('oldFileNumbers ' + oldFileNumbers.size());
        system.debug(oldFileNumbers);
        try{
            if(oldFileNumbers.size() == 1){
                List<Scheduled_Payment__c> schedulePayments = [
                    Select Id, AFT_File_Number__c, CWB_Sheet_Number__c
                    FROM Scheduled_Payment__c
                    WHERE (Status__c = 'Pre Send Validation' OR Status__c = 'Approved to Send')
                    AND Send_Cheque__c = false
                    AND CWB_Sheet_Number__c IN : oldFileNumbers
                    AND AFT_File_Number__c != null
                ];
                
                system.debug('schedulePayments ' + schedulePayments.size());
                system.debug(schedulePayments);
                
                system.debug('oldSpCount ' + oldSpCount);
                
                if(schedulePayments.size() != oldSpCount){
                    throw new EFTFileException(null, '', 'Please include all failed Scheduled payments for Banking Sheet # ' + new List<String>(oldFileNumbers)[0] + '.' );
                }
            }
        }
        catch(EFTFileException e){
            errorList.add(e);
            throw new EFTFileErrorListException(errorList);
        }
        /***********************************************************************/
        
        AFT_File__c aftFileObj = getAFTFileObj();        
        CWBFileSetting cwbFileSetting = new CWBFileSetting();
        CWB_File_Setting__c cwbFileCustomSetting = CWB_File_Setting__c.getOrgDefaults();
        
        cwbFileSetting.fileNumber = Integer.valueOf(cwbFileCustomSetting.get(businessUnit + '_File_Number__c'));
        cwbFileSetting.AccountNumberforReturns = String.valueOf(cwbFileCustomSetting.get(businessUnit + '_Account_Number_for_Returns__c'));
        cwbFileSetting.DestinationDataCentre = String.valueOf(cwbFileCustomSetting.get(businessUnit + '_Destination_Data_Centre__c'));
        cwbFileSetting.InstitutionalIDforReturns = String.valueOf(cwbFileCustomSetting.get(businessUnit + '_Institutional_ID_for_Returns__c'));
        cwbFileSetting.OriginatorId = String.valueOf(cwbFileCustomSetting.get(businessUnit + '_Originator_Id__c'));
        cwbFileSetting.OriginatorLongName = String.valueOf(cwbFileCustomSetting.get(businessUnit + '_Originator_Long_Name__c'));
        cwbFileSetting.OriginatorShortName = String.valueOf(cwbFileCustomSetting.get(businessUnit + '_Originator_Short_Name__c'));
        
        /*AFT_File__c aftFileObj = getAFTFileObj();
        AFT_File_Setting__mdt aftFileSetting = [SELECT Account_Number_for_Returns__c, Destination_Data_Centre__c, Institutional_ID_for_Returns__c,
                                                Originator_Id__c, Originator_Long_Name__c, Originator_Short_Name__c, MasterLabel, DeveloperName, File_Number__c
                                                FROM AFT_File_Setting__mdt WHERE DeveloperName = :businessUnit];*/
        if(cwbFileSetting.fileNumber == null || cwbFileSetting.fileNumber == 0){
            cwbFileSetting.fileNumber = 1;
        }else{
            cwbFileSetting.fileNumber++;
        }
        
        if(oldFileNumbers.size() == 1){
            string filenumStr = new List<String>(oldFileNumbers)[0];
        	
            cwbFileSetting.fileNumber = integer.valueof(filenumStr.split('-')[1].trim());
        }/*else{
        	MetaDataUtility.upsertMetadata(System.JSON.serialize(aftFileSetting));
        }*/
        
        String aftFileHeaderStr = '';
        
               
        // Generate file header
        AFTFileHeader aftFileHeader = new AFTFileHeader(String.valueOf(logicalRecordCount), cwbFileSetting);
        try {
            aftFileHeaderStr = aftFileHeader.getFileHeaderAsString() + '\r\n'; // Prepend header             
        } catch (EFTFileException e) {
            errorList.add(e);
            throw new EFTFileErrorListException(errorList);
        }
        
        
            
        Map<Id, GroupedPayments> groupedPayments = new Map<Id, GroupedPayments>();
        
        // Loop over Scheduled Payments and create detail lines        
        Datetime now = DateUtil.now();
        
        for (Scheduled_Payment__c sp : this.spList) {
            // Validate User is able to send current payment (has EFT_Permission or was not the validator)
            if (!sp.Can_Send_to_Bank__c) {
                errorList.add(new EFTFileException(sp.Id, 'Can_Send_to_Bank__c', 'You are not able to send payments that you verified.'));
            }
            
            try {
                if (sp.Current_Bank_Account_Id__c == null || String.isBlank(sp.Current_Bank_Account_Id__c)) {
                    throw new EFTFileException(sp.Id, 'Current_Bank_Account_URL__c', 'Scheduled Payment does not have a Bank Account set');
                }
                if (sp.Amount__c <= 0) {
                    throw new EFTFileException(sp.Id, 'Amount__c', 'Scheduled Payment amount must be greater than $0');
                }
                GroupedPayments gp;
                if (groupedPayments.containsKey(sp.Current_Bank_Account_Id__c)) {
                    gp = groupedPayments.get(sp.Current_Bank_Account_Id__c);
                } else {
                    Id baId = sp.Current_Bank_Account_Id__c;
                    Bank_Account__c ba = this.bankAccountList.get(baId);
                    gp = new GroupedPayments(ba);
                    groupedPayments.put(sp.Current_Bank_Account_Id__c, gp);
                }
                sp.Bank_Account__c = sp.Current_Bank_Account_Id__c;
                gp.addPayment(sp);
            } catch (EFTFileException e) {
                system.debug('exception: ' + e.message);
                // Catch exception and set Scheduled Payment Id
                e.id = sp.Id;
                errorList.add(e);
                //throw e;
            }
            
            sp.Status__c = 'Sent to Bank';
            sp.Sent_to_Bank_Account__c = sp.Current_Bank_Account_Id__c;
            sp.Sent_to_Bank_Date__c = now;
            sp.Sent_to_Bank_By__c = UserInfo.getUserId();
            sp.AFT_File_Number__c = cwbFileSetting.fileNumber;
            sp.CWB_Business_Unit__c = businessUnit;
        }
        
        logicalRecordCount++;
        String aftFileDetailStr = '';
        // Generate Debit Transaction Lines from Grouped Payments
        List<List<GroupedPayments>> listOfGroupedPayments = new List<List<GroupedPayments>>();
        listOfGroupedPayments.add(new List<GroupedPayments>());// 0 index
        Integer transCount = 0, index = 0, count = 0;
        for (GroupedPayments gp : groupedPayments.values()) {
            if(math.mod(count, 6)  == 0 && count != 0){
                index++;
                if(count < groupedPayments.size() + 1)
                	listOfGroupedPayments.add(new List<GroupedPayments>());
            }
            listOfGroupedPayments[index].add(gp); 
            count++;
        }
        
        system.debug('listOfGroupedPayments ' + listOfGroupedPayments.size());
        system.debug(listOfGroupedPayments);
        String detailRow = '';
        AFTFileDetail aftFileD;
        for(List<GroupedPayments> groupedPaymentsList : listOfGroupedPayments){
            transCount = 0;
            detailRow = '';
            for(GroupedPayments gp : groupedPaymentsList){
                try {
                    aftFileD = new AFTFileDetail('C', gp, this.dueDate, String.valueOf(logicalRecordCount), cwbFileSetting);
                    
                    if(transCount == 0){
                        detailRow += aftFileD.getSegmentZero();
                    }
                    detailRow += aftFileD.getSegmentOne();
                    
                    this.amountCreditTotal += gp.total;
                    this.creditTransactionCount += 1;
                    
                }catch (EFTFileException e) {
                    system.debug('exception: ' + e.message);
                    errorList.add(e);
                    //throw e;
                }
                transCount++;
            }
            aftFileDetailStr += AFTFileDetail.setRowFiller(detailRow);
            aftFileDetailStr += '\r\n';
            logicalRecordCount++;
            
        }
        
        String aftFileTrailerStr = '';
        // Generate file footer
        AFTFileTrailer aftFileTrailer = new AFTFileTrailer(String.valueOf(logicalRecordCount), this.amountCreditTotal, this.creditTransactionCount, this.amountDebitTotal, this.debitTransactionCount, cwbFileSetting);
        try {
            aftFileTrailerStr += aftFileTrailer.getFileTrailerAsString() + '\r\n';
        } catch (EFTFileException e) {
            errorList.add(e);
        }
        
        if (errorList.isEmpty() == false) {
            System.debug(errorList);
            throw new EFTFileErrorListException(errorList);
        } else {            
            try {                
                for (Scheduled_Payment__c sp : spList) {
                    sp.AFT_File__c = aftFileObj.Id;
                    sp.EFT_File__c = null;
                }
            } catch (EFTFileException e) {
                errorList.add(e);
                throw new EFTFileErrorListException(errorList);
            }
        }

        // update Scheduled Payments' status
        update spList;
        UpdateCWBFileSettings(businessUnit, cwbFileCustomSetting, cwbFileSetting.fileNumber);
        
        aftFileObj.Total_Credit_Amount__c = this.amountCreditTotal;
        aftFileObj.Total_Debit_Amount__c = this.amountDebitTotal;
        aftFileObj.Credit_Transaction_Count__c = this.creditTransactionCount;
        aftFileObj.Debit_Transaction_Count__c = this.debitTransactionCount;
        update aftFileObj;
        aftFileData = aftFileHeaderStr + aftFileDetailStr + aftFileTrailerStr;
        return aftFileData;
    }
    
    
    public class CWBFileSetting{
        public Integer fileNumber{get; set;}
        public String AccountNumberforReturns{get; set;}
        public String DestinationDataCentre{get; set;}
        public String InstitutionalIDforReturns{get; set;}
        public String OriginatorId{get; set;}
        public String OriginatorLongName{get; set;}
        public String OriginatorShortName{get; set;}
    }
}