force-app/main/default/objects/Underwriter_Evaluation_History__c/Underwriter_Evaluation_History__c.object-meta.xml
<CustomObject>
    <description>This object will record history of underwriter evaluation on update.</description>
    <label>Underwriter Evaluation History</label>
    <nameField>
        <displayFormat>URH-{000}</displayFormat>
        <label>Underwriter Evaluation History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Underwriter Evaluation Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Underwriter_Evaluation_History__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Underwriter Evaluation Histories</relationshipLabel>
    <relationshipName>Underwriter_Evaluation_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Underwriter_Evaluation_History__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Underwriter_Evaluation_History__c/fields/HistoryCreateDate__c.field-meta.xml
<CustomField>
    <fullName>HistoryCreateDate__c</fullName>
    <formula>DATEVALUE(CreatedDate)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HistoryCreateDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Underwriter_Evaluation_History__c/fields/New_Value__c.field-meta.xml
<CustomField>
    <fullName>New_Value__c</fullName>
    <label>New Value</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Underwriter_Evaluation_History__c/fields/Old_Value__c.field-meta.xml
<CustomField>
    <fullName>Old_Value__c</fullName>
    <label>Old Value</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/UnderwriterEvaluationHistoryCtrl.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 09-28-2020
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   09-18-2020   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public with sharing class UnderwriterEvaluationHistoryCtrl {
    @AuraEnabled
    public static List<Underwriter_Evaluation_History__c> UnderwriterEvaluationHistory(String AccountId){
        String query = 'SELECT Field_Name__c,New_Value__c, Old_Value__c, CreatedBy.Name, HistoryCreateDate__c FROM Underwriter_Evaluation_History__c WHERE Account__c =: AccountId';
        query += ' ORDER BY Createddate DESC';
        List<Underwriter_Evaluation_History__c> History = Database.query(query);
        return History;
    }
}