force-app/main/default/objects/Historical_Data__c/Historical_Data__c.object-meta.xml
<CustomObject>
    <label>Historical Data</label>
    <nameField>
        <displayFormat>HD-{00000000}</displayFormat>
        <label>Historical Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Historical_Data__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Historical Data</relationshipLabel>
    <relationshipName>Historical_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Long_Name__c</fullName>
        <formula>Name &amp;&quot; - &quot;&amp; TEXT(Loan_Requests__c) &amp; &quot; - &quot;&amp; TEXT(Loan_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Long Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/HistoricalDataController.cls
public class HistoricalDataController {
    
    @AuraEnabled
    public static List<sObject> searchHistoricalData(String recordId){
        
        List<Historical_Data__c> hdList=
            new List<Historical_Data__c>([SELECT Id,Opportunity__c,Opportunity__r.Name ,Opportunity__r.Opportunity_Long_Name__c 
                                          FROM Historical_Data__c 
                                          WHERE Opportunity__r.AccountId =:recordId]);
        system.debug(hdList);
        return hdList;
    }
    
}