force-app/main/default/objects/Assessment_Provider_Schedule__c/Assessment_Provider_Schedule__c.object-meta.xml
<CustomObject>
    <label>Assessment Provider Schedule</label>
    <nameField>
        <displayFormat>APS-{0000}</displayFormat>
        <label>Assessment Provider Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Provider Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Law_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Law Firm</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>Account.Account_Type__c</field>
                <operation>equals</operation>
                <value>Lawyer, Law Firm</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Law Firm</value>
            </filterItems>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Law Firm</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Clients</relationshipLabel>
        <relationshipName>Clients</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Lawyers</fullName>
        <active>true</active>
        <description>Use this record type to track lawyers</description>
        <label>Lawyers</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Law_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Law Firm</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Referred Cases</relationshipLabel>
        <relationshipName>Referred_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lawyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lawyer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referred Cases</relationshipLabel>
        <relationshipName>Referred_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_of_Loan__c</fullName>
        <label>Type of Loan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Facility Loan</fullName>
                </value>
                <value>
                    <fullName>Lump-Sum</fullName>
                    <default>true</default>
                    <label>Lump-Sum</label>
                </value>
                <value>
                    <fullName>Treatment Loan</fullName>
                </value>
                <value>
                    <fullName>Treatment Loan 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Assessment_Provider__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Provider</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Assessment Provider account must be of type Assessment Provider</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Assessment Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assessment Provider Referred Cases</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AssessmentProviderScheduleCtlr.cls
public with sharing class AssessmentProviderScheduleCtlr {
    
    @AuraEnabled
    public static void createAssessmentSchedulesbyLawFirm(Id recordId, Id lookupId, Decimal discount){
        
        try{
            Id lawyerRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Lawyers').getRecordTypeId();
            
            List<Assessment_Provider_Schedule__c> assessmentSchedules = new List<Assessment_Provider_Schedule__c>();
            for(Contact lawyer : [SELECT Id, Name FROM Contact WHERE AccountId = :lookupId 
                                  AND RecordTypeId =:lawyerRecordTypeId]){
                                      assessmentSchedules.add(
                                          new Assessment_Provider_Schedule__c(
                                              Assessment_Provider__c = recordId,
                                              Lawyer__c = lawyer.Id,
                                              Discount__c = discount
                                          )
                                      );
                                  }
            if(!assessmentSchedules.isEmpty())
                insert assessmentSchedules;
            
            List<Opportunity> oppList = [SELECT Id, Discount_Rate__c FROM Opportunity 
                                        WHERE Law_Firm__c =: lookupId AND StageName != 'Closed With Loan'
                                        AND StageName != 'Closed No Loan' AND StageName != 'TESTING'
                                        AND Type_of_Loan__c = 'Assessment'];
                                        
            for(Opportunity opp : oppList){
                opp.Discount_Rate__c = discount;
            }
            if(!oppList.isEmpty()){
                update oppList;
            }
        }catch (Exception e){
            system.debug('Error : ' + e.getMessage() + ' ' + e.getLineNumber());
            system.debug(e.getStackTraceString());
            throw new AuraHandledException('Error:'+e.getMessage());
        }        
    }
    
    @AuraEnabled
    public static void createAssessmentSchedules(Id recordId, Id lookupId, Decimal discount){
        
        try{
            insert new Assessment_Provider_Schedule__c(
                Assessment_Provider__c = recordId,
                Lawyer__c = lookupId,
                Discount__c = discount
            );

            List<Opportunity> oppList = [SELECT Id, Discount_Rate__c FROM Opportunity 
                                        WHERE Lawyer__c =: lookupId AND StageName != 'Closed With Loan'
                                        AND StageName != 'Closed No Loan' AND StageName != 'TESTING'
                                        AND Type_of_Loan__c = 'Assessment'];
                                        
            for(Opportunity opp : oppList){
                opp.Discount_Rate__c = discount;
            }
            if(!oppList.isEmpty()){
                update oppList;
            }
        }catch (Exception e){
            system.debug('Error : ' + e.getMessage() );
            throw new AuraHandledException('Error:'+e.getMessage());
        }        
    }
    
    @AuraEnabled
    public static Account getAssessmentProviderInfo(Id recordId){
        return [SELECT Id, Name FROM Account WHERE Id =:recordId];
    }
    
    @AuraEnabled
    public static User getCurrentUserInfo(){
        return [SELECT Id, Can_Edit_Assessment_Schedule__c FROM User 
                WHERE Id = :UserInfo.getUserId()];
    }
    
    @AuraEnabled
    public static List<Assessment_Provider_Schedule__c> getAssessmentSchedules(Id assessmentProviderId){
        
        return [SELECT Id, Name, Assessment_Provider__c, Assessment_Provider__r.Name, Lawyer__c, 
                Lawyer__r.Name, Discount__c, CreatedDate, CreatedBy.Name, LastModifiedDate, LastModifiedBy.Name
                FROM Assessment_Provider_Schedule__c
                WHERE Assessment_Provider__c = :assessmentProviderId];
    }
    
    @AuraEnabled
    public static List<Assessment_Provider_Schedule__c> getAssessmentSchedulesByLawyer(Id lawyerId){
        
        return [SELECT Id, Name, Assessment_Provider__c, Assessment_Provider__r.Name, Lawyer__c, 
                Lawyer__r.Name, Discount__c, CreatedDate, CreatedBy.Name, LastModifiedDate, LastModifiedBy.Name 
                FROM Assessment_Provider_Schedule__c
                WHERE Lawyer__c = :lawyerId];
    }
}