force-app/main/default/objects/Assessment_Provider_Schedule__c/Assessment_Provider_Schedule__c.object-meta.xml
<CustomObject>
    <label>Assessment Provider Schedule</label>
    <nameField>
        <displayFormat>APS-{0000}</displayFormat>
        <label>Assessment Provider Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Provider Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Law_Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Law Firm</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Referred Cases</relationshipLabel>
        <relationshipName>Referred_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lawyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lawyer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referred Cases</relationshipLabel>
        <relationshipName>Referred_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_of_Loan__c</fullName>
        <label>Type of Loan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Facility Loan</fullName>
                </value>
                <value>
                    <fullName>Lump-Sum</fullName>
                    <default>true</default>
                    <label>Lump-Sum</label>
                </value>
                <value>
                    <fullName>Treatment Loan</fullName>
                </value>
                <value>
                    <fullName>Treatment Loan 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Assessment_Provider__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Provider</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Assessment Provider account must be of type Assessment Provider</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Assessment Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assessment Provider Referred Cases</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHandler.cls
public with sharing class OpportunityTriggerHandler {
    
    
    public static void setDiscountschedule(List<Opportunity> newOpps, Map<Id,Opportunity> oldMap, Boolean isInsert){
        
        List<Opportunity> selOpportunities = new List<Opportunity>();
        List<Assessment_Provider_Schedule__c> assessmentScheduleToInsert = new List<Assessment_Provider_Schedule__c>();
        Set<Id> assessmentProviderIds = new Set<Id>();
        Set<Id> lawyerIds = new Set<Id>();
        
        for(Opportunity opp : newOpps){
            if(opp.Type_of_Loan__c == 'Assessment' &&
               (isInsert || (!isInsert && (opp.Assessment_Provider__c != oldMap.get(opp.Id).Assessment_Provider__c ||
                                           opp.Lawyer__c != oldMap.get(opp.Id).Lawyer__c)))){
                                               
                                               selOpportunities.add(opp);
                                               assessmentProviderIds.add(opp.Assessment_Provider__c);
                                               lawyerIds.add(opp.Lawyer__c);
                                           }
        }
        
        if(!selOpportunities.isEmpty()){
            Map<String,Assessment_Provider_Schedule__c> discountscheduleMap = new Map<String, Assessment_Provider_Schedule__c>();
            for(Assessment_Provider_Schedule__c aps : [Select Id, Lawyer__c, Assessment_Provider__c, Discount__c
                                                       FROM Assessment_Provider_Schedule__c 
                                                       WHERE Assessment_Provider__c in :assessmentProviderIds
                                                       AND Lawyer__c in :lawyerIds order by CreatedDate asc]){
                                                           discountscheduleMap.put(aps.Assessment_Provider__c + '-' + aps.Lawyer__c, aps);
                                                       }
            
            
            for(Opportunity opp : selOpportunities){
                opp.Discount_Rate__c = 0;
                
                String key = opp.Assessment_Provider__c + '-' + opp.Lawyer__c;
                if(discountscheduleMap.containsKey(key)){
                    opp.Discount_Rate__c = discountscheduleMap.get(key).Discount__c;
                    
                }else if(opp.Assessment_Provider__c != null && opp.Law_Firm__c != null){
                    assessmentScheduleToInsert.add(
                        new Assessment_Provider_Schedule__c(
                            Assessment_Provider__c = opp.Assessment_Provider__c,
                            Lawyer__c = opp.Lawyer__c,
                            Discount__c = 0
                        )
                    );
                } 
            }
        }

        if(!assessmentScheduleToInsert.isEmpty())
            insert assessmentScheduleToInsert;
    }
}